### ISSUE TITLE
Mekanism and Agricraft don't play nice together

### ISSUE THREAD

**Issue by tyggna** [mekanism/Mekanism#5122]
This is an annoyance more than anything.  Agricraft and mekanism don't play nice and occasionally my sprinklers get converted into a mekanism gas tank.  Here's the traceback. (dedicated forge server)

```
[10:48:50] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ClassCastException: com.infinityraider.agricraft.tiles.irrigation.TileEntityChannelFull cannot be cast to mekanism.common.tile.TileEntityGasTank
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_171]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_171]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.ClassCastException: com.infinityraider.agricraft.tiles.irrigation.TileEntityChannelFull cannot be cast to mekanism.common.tile.TileEntityGasTank
        at mekanism.common.block.BlockGasTank.getPickBlock(BlockGasTank.java:285) ~[BlockGasTank.class:?]
        at mekanism.common.block.BlockGasTank.removedByPlayer(BlockGasTank.java:217) ~[BlockGasTank.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.removeBlock(PlayerInteractionManager.java:271) ~[or.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:324) ~[or.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_180785_a(PlayerInteractionManager.java:244) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:702) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[lp.class:?]
        at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[lp.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more

```
Versions this was found:
Agricraft 2.12.0-1.12.0-a5
Forge 1.12.2-14.23.4.2739
Mekanism 1.12.2-9.4.12.349

I opened a ticket with Agricraft too.  This is low-priority, it's just annoying.

**Comment by thiakil** [comment]
I honestly don't know how that would happen, as the tile at the position is somehow being turned into a sprinkler tile.

**Comment by thiakil** [comment]
I need to know a proper reproduction scenario for this in order to determine cause
