### ISSUE TITLE
Fatal error in SpongeForge 7.1.6 recommended build

### ISSUE THREAD

**Issue by mistek131995** [mekanism/Mekanism#5504]
After update I have this error on my server. SpongeForge devolpmers say "It looks like something is swallowing the NPE trace. This is outside of Sponge's code at this point." My be problem in your mod... The problem appeared after the update.

[debug-4.log](https://github.com/mekanism/Mekanism/files/3261899/debug-4.log)
[log.txt](https://github.com/mekanism/Mekanism/files/3261900/log.txt)

**Comment by thiakil** [comment]
Unless you can get a proper stack trace from it, there's nothing we can do. IMO not even enough to pin it on Mekanism, even if it was the only mod you updated.

It's quite odd that the caused by trace has no stacktrace attached. Definitely not caused by us.

**Comment by dualspiral** [comment]
There is a fuller trace towards the top of the log which I've fished out:

```
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_211]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:307) [SpongeImplHooks.class:1.12.2-2825-7.1.6]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjo000(MinecraftServer.java:3970) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NullPointerException
	at java.util.EnumMap.typeCheck(Unknown Source) ~[?:1.8.0_211]
	at java.util.EnumMap.put(Unknown Source) ~[?:1.8.0_211]
	at java.util.EnumMap.put(Unknown Source) ~[?:1.8.0_211]
	at mekanism.common.capabilities.CapabilityWrapperManager.getWrapper(CapabilityWrapperManager.java:22) ~[CapabilityWrapperManager.class:?]
	at mekanism.common.tile.transmitter.TileEntityUniversalCable.getCapability(TileEntityUniversalCable.java:340) ~[TileEntityUniversalCable.class:?]
	at mcp.mobius.waila.addons.capability.HUDHandlerEnergy.getNBTData(HUDHandlerEnergy.java:46) ~[HUDHandlerEnergy.class:?]
	at mcp.mobius.waila.network.MessageRequestTile$Handler.lambda$onMessage$0(MessageRequestTile.java:93) ~[MessageRequestTile$Handler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_211]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 7 more
```

which is the following:

https://github.com/mekanism/Mekanism/blob/d4e2724643f249d9915a79da9b653d5706d7004d/src/main/java/mekanism/common/capabilities/CapabilityWrapperManager.java#L20-L23

I would guess that `facing` is `null` here, causing that NPE (EnumMaps can't have null keys), but I'm not overly familiar with your mod otherwise, so I don't know in which scenarios that would happen in.

**Comment by thiakil** [comment]
That does indeed look like a prime suspect, thanks!
