### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by yaroslav4167** [mekanism/Mekanism#5534]
#### Version (make sure you are on the latest version before reporting):
**Mekanism:** 1.12.2-9.7.8.379

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[Hastebin](https://lww.page.link/HjCE)

How to disable this spam in console?

**Comment by thiakil** [comment]
Some info on your setup of Logistical Transporters and/or Logistical Sorters would help

**Comment by yaroslav4167** [comment]
My [config](https://lww.page.link/BsbR) of this mod.
I do not know where the Logistical Transporters and Logistical Sorters are located, as this is a public server.

**Comment by thiakil** [comment]
alrighty, well if we can't narrow down anything, it will have to wait until next release which will give us an exact code location to look into

**Comment by pupnewfster** [comment]
Hopefully https://github.com/mekanism/Mekanism/commit/3750d42c3e135c58faa4c6be756bdfc2c08c3671 will fix it, (which will be part of 9.7.9 when it gets released at some point). If not the added logging added will allow us to finish tracking it down in 9.7.9

**Comment by thiakil** [comment]
9.7.9 has been released, please update and let us know the new message if it continues

**Comment by yaroslav4167** [comment]
Now there not spam =)
After the server starting in console printing few warnings:
```
[13:28:35] [Server thread/WARN] [Mekanism]: 'TransitRequest' was wrapped around a non-IItemHandler inventory. This should not happen!
java.lang.Exception: null
	at mekanism.common.util.InventoryUtils.assertItemHandler(InventoryUtils.java:142) [InventoryUtils.class:?]
	at mekanism.common.content.transporter.TransitRequest.buildInventoryMap(TransitRequest.java:47) [TransitRequest.class:?]
	at mekanism.common.tile.TileEntityLogisticalSorter.onUpdate(TileEntityLogisticalSorter.java:126) [TileEntityLogisticalSorter.class:?]
	at mekanism.common.tile.prefab.TileEntityBasicBlock.func_73660_a(TileEntityBasicBlock.java:86) [TileEntityBasicBlock.class:?]
	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:257) [(CORE)spongeforge-1.12.2-2825-7.1.6.jar:1.12.2-2825-7.1.6]
	at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:3167) [oo.class:?]
	at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zme000(WorldServer.java:3151) [oo.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:6842) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2290) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[13:28:35] [Server thread/WARN] [Mekanism]:  - details: TileFissionController{tileType=alchemistry:fission_controller, world=WorldServer{Name=world, DimensionId=0, DimensionType=minecraft:overworld, DimensionTypeId=0}, pos=BlockPos{x=22, y=63, z=305}, blockMetadata=-1} BlockPos{x=22, y=63, z=305}
[13:28:36] [Server thread/INFO] [Sponge]: Unloading world [DIM_SPACESTATION3] (galacticraftcore:space_station/3)
[13:28:37] [Server thread/WARN] [Mekanism]: 'TransitRequest' was wrapped around a non-IItemHandler inventory. This should not happen!
java.lang.Exception: null
	at mekanism.common.util.InventoryUtils.assertItemHandler(InventoryUtils.java:142) [InventoryUtils.class:?]
	at mekanism.common.content.transporter.TransitRequest.buildInventoryMap(TransitRequest.java:47) [TransitRequest.class:?]
	at mekanism.common.tile.TileEntityLogisticalSorter.onUpdate(TileEntityLogisticalSorter.java:126) [TileEntityLogisticalSorter.class:?]
	at mekanism.common.tile.prefab.TileEntityBasicBlock.func_73660_a(TileEntityBasicBlock.java:86) [TileEntityBasicBlock.class:?]
	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:257) [(CORE)spongeforge-1.12.2-2825-7.1.6.jar:1.12.2-2825-7.1.6]
	at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:3167) [oo.class:?]
	at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zme000(WorldServer.java:3151) [oo.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:6842) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2290) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[13:28:37] [Server thread/WARN] [Mekanism]:  - details: TileFissionController{tileType=alchemistry:fission_controller, world=WorldServer{Name=world, DimensionId=0, DimensionType=minecraft:overworld, DimensionTypeId=0}, pos=BlockPos{x=22, y=63, z=305}, blockMetadata=9} BlockPos{x=22, y=63, z=305}
```

**Comment by pupnewfster** [comment]
I am going to look into this a bit more because at first glance it does seem that tile is properly implementing IItemHandler so the warning should not be getting thrown. One thing I did notice however is that when I added checks to ensure the tiles are not null I forgot to add a check to ensure it is pulling from an IItemHandler so if for example a logistical sorter gets placed against a Daylight Detector it would probably end up spamming the console again.

Actually thinking about this given it isn't spamming and only printed a few warnings when starting up it is probably because of my missing extra check for making sure the tile it thinks is an itemhandler is one, and the fact that the reactor *doesn't* have an itemhandler cap until the multiblock has formed which may not have happened when it first loaded.

**Comment by pupnewfster** [comment]
Version [9.8.0](https://www.curseforge.com/minecraft/mc-mods/mekanism/files/2746197) was just released and should sync to the twitch client within the next couple hours. It should make it so that it does not have the initial exceptions thrown when the server just starts.
