### ISSUE TITLE
Server Crash caused by CableUtils.emit in Gas Burning Generator

### ISSUE THREAD

**Issue by JayaramV-Hexaware** [mekanism/Mekanism#5541]
Version:
MekanismGenerators-1.12.2-9.7.5.376.jar
Mekanism-1.12.2-9.7.5.376.jar
MekanismTools-1.12.2-9.7.5.376.jar

Issue:

Server crash caused by Mekanism Gas Burning Generator in CableUtils.java , line 149

Scenario:
I have several gas burning generators in a compact dimension.  It's been running fine for a long time.  But crashed all of a sudden.  Appreciate a look-see and a possible patch please.

Crash Stack Trace:

`java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)
        at java.lang.Object.hashCode(Native Method)
        at java.util.HashMap.hash(HashMap.java:339)
        at java.util.HashMap.put(HashMap.java:612)
        at java.util.HashSet.add(HashSet.java:220)
        at mekanism.common.util.CableUtils.emit(CableUtils.java:149)
        at mekanism.generators.common.tile.TileEntityGenerator.onUpdate(TileEntityGenerator.java:64)
        at mekanism.generators.common.tile.TileEntityGasGenerator.onUpdate(TileEntityGasGenerator.java:55)
        at mekanism.common.tile.prefab.TileEntityBasicBlock.func_73660_a(TileEntityBasicBlock.java:86)
        at net.minecraft.world.World.func_72939_s(World.java:1835)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)`

**Comment by CraftalotReloaded** [comment]
This is not necessarily caused by mekanism, if the server watchdog kills the server literally anything can appear there

**Comment by thiakil** [comment]
Indeed, without actual profiling data, the crash means nothing except Mekanism was running when the server had enough of waiting

**Comment by rickyhoho** [comment]
i get a same problem in same version of mekanism

**Comment by rickyhoho** [comment]
My server crash when I just finish a Industrial Turbine

**Comment by rickyhoho** [comment]
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at mekanism.generators.common.content.turbine.TurbineFluidTank.getFluidAmount(TurbineFluidTank.java:113)
	at mekanism.generators.common.tile.turbine.TileEntityTurbineValve.getRedstoneLevel(TileEntityTurbineValve.java:417)
	at mekanism.generators.common.tile.turbine.TileEntityTurbineValve.onUpdate(TileEntityTurbineValve.java:67)
	at mekanism.common.tile.prefab.TileEntityBasicBlock.func_73660_a(TileEntityBasicBlock.java:86)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at mekanism.generators.common.content.turbine.TurbineFluidTank.getFluidAmount(TurbineFluidTank.java:113)
	at mekanism.generators.common.tile.turbine.TileEntityTurbineValve.getRedstoneLevel(TileEntityTurbineValve.java:417)
	at mekanism.generators.common.tile.turbine.TileEntityTurbineValve.onUpdate(TileEntityTurbineValve.java:67)
	at mekanism.common.tile.prefab.TileEntityBasicBlock.func_73660_a(TileEntityBasicBlock.java:86)

-- Block entity being ticked --
Details:
	Name: mekanismgenerators:turbine_valve // mekanism.generators.common.tile.turbine.TileEntityTurbineValve
	Block type: ID #927 (tile.Generator // mekanism.generators.common.block.BlockGenerator$1 // mekanismgenerators:generator)
	Block data value: 11 / 0xB / 0b1011
	Block location: World: (-129,79,-81), Chunk: (at 15,4,15 in -9,-6; contains blocks -144,0,-96 to -129,255,-81), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Actual block type: ID #927 (tile.Generator // mekanism.generators.common.block.BlockGenerator$1 // mekanismgenerators:generator)
	Actual block data value: 11 / 0xB / 0b1011
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: world
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 1615983321085731580
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-124,64,-56), Chunk: (at 4,4,8 in -8,-4; contains blocks -128,0,-64 to -113,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 3676166 game time, 560389 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

**Comment by rickyhoho** [comment]
The crash report is here

**Comment by rickyhoho** [comment]
> Indeed, without actual profiling data, the crash means nothing except Mekanism was running when the server had enough of waiting

i give you my crash report

**Comment by rickyhoho** [comment]
@thiakil

**Comment by thiakil** [comment]
No, @rickyhoho that is not the same crash as OP. Your is one that has already been fixed, you need to update Mekanism to the latest version

**Comment by rickyhoho** [comment]
> No, @rickyhoho that is not the same crash as OP. Your is one that has already been fixed (#5485 and its many duplicates), you need to update Mekanism to the latest version

thank you for reply
