### ISSUE TITLE
Metallurgic Infuser deletes redstone(or any other resource) and doesn't store it

### ISSUE THREAD

**Issue by sevsev9** [mekanism/Mekanism#5637]
#### Issue description:
When I want to use another resource in the MI I have to build a new one every time because it is locked to one resource due to a bug.

#### Steps to reproduce:
1. Insert coal
2. remove coal
3. insert redstone (or any other resource except previous)
4. deletes redstone and throws this exception
`[15:39:33] [Server thread/ERROR] [Mekanism]: Tried to increase infusion storage with an incompatible type
java.lang.Exception: null
        at mekanism.common.InfuseStorage.increase(InfuseStorage.java:58) [InfuseStorage.class:?]
        at mekanism.common.tile.TileEntityMetallurgicInfuser.onUpdate(TileEntityMetallurgicInfuser.java:94) [TileEntityMetallurgicInfuser.class:?]
        at mekanism.common.tile.prefab.TileEntityBasicBlock.func_73660_a(TileEntityBasicBlock.java:89) [TileEntityBasicBlock.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1835) [amu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]`

#### Version (make sure you are on the latest version before reporting):
**Forge: 14.25.5.2838** 
**Mekanism+Generators+Tools: 9.7.2.373** 
**MC: 1.12.2 ** 
**FTB Ultimate Reloaded: 1.8.0 **

**Comment by thiakil** [comment]
> make sure you are on the latest version before reporting
