### ISSUE TITLE
Digital Miner tick crashing game?

### ISSUE THREAD

**Issue by Secondriley** [mekanism/Mekanism#5641]
Im playing the astroblock modpack and all of a sudden my game crashed and this is the report, if anyone has any idea how to fix this it would help thank you.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  RandomPatches (randompatches-1.12.2-1.11.0.3.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.210.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  Ar_CorePlugin (additionalresources-1.9.4-0.2.0.28+47cd0bd_signed.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 9/14/19 11:23 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at ca.teamdman.discordintegration.PresenceEventHandler.onHarvest(PresenceEventHandler.java:165)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_141_PresenceEventHandler_onHarvest_BreakEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at mekanism.common.tile.TileEntityDigitalMiner.canMine(TileEntityDigitalMiner.java:372)
	at mekanism.common.tile.TileEntityDigitalMiner.onUpdate(TileEntityDigitalMiner.java:236)
	at mekanism.common.tile.prefab.TileEntityBasicBlock.func_73660_a(TileEntityBasicBlock.java:91)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at ca.teamdman.discordintegration.PresenceEventHandler.onHarvest(PresenceEventHandler.java:165)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_141_PresenceEventHandler_onHarvest_BreakEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at mekanism.common.tile.TileEntityDigitalMiner.canMine(TileEntityDigitalMiner.java:372)
	at mekanism.common.tile.TileEntityDigitalMiner.onUpdate(TileEntityDigitalMiner.java:236)
	at mekanism.common.tile.prefab.TileEntityBasicBlock.func_73660_a(TileEntityBasicBlock.java:91)

-- Block entity being ticked --
Details:
	Name: mekanism:digital_miner // mekanism.common.tile.TileEntityDigitalMiner
	Block type: ID #1911 (tile.MachineBlock // mekanism.common.block.BlockMachine$1 // mekanism:machineblock)
	Block data value: 4 / 0x4 / 0b0100
	Block location: World: (-1272,70,-1068), Chunk: (at 8,4,4 in -80,-67; contains blocks -1280,0,-1072 to -1265,255,-1057), Region: (-3,-3; contains chunks -96,-96 to -65,-65, blocks -1536,0,-1536 to -1025,255,-1025)
	Actual block type: ID #1911 (tile.MachineBlock // mekanism.common.block.BlockMachine$1 // mekanism:machineblock)
	Actual block data value: 4 / 0x4 / 0b0100
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New World
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 650 Drop: 0
	Level seed: -7230946477392902851
	Level generator: ID 07 - voidworld, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-10,228,0), Chunk: (at 6,14,0 in -1,0; contains blocks -16,0,0 to -1,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1971531 game time, 1971531 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 3482 (now: false), thunder time: 109808 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

**Comment by pupnewfster** [comment]
Pretty sure from the stack trace it is caused by another mod not handling fake players at all: `at ca.teamdman.discordintegration.PresenceEventHandler.onHarvest(PresenceEventHandler.java:165)
at` My guess it the person who made whatever discord integration mod that pack is using forgot that fake players exist and can fire events. The reason it shows that the miner is what is being ticked, is it fires a harvest event but never finishes ticking as it is unable to get any form of response about if it was able to harvest the block (success or failure)

**Comment by Secondriley** [comment]
Thank you @pupnewfster! I removed the discord mod itself cause I don't use it anyways and it worked, thanks for pointing that out 😄

**Comment by pupnewfster** [comment]
(It still would probably be a good idea to report it to the author of that mod so that they are able to fix it)

**Comment by TeamDman** [comment]
https://www.curseforge.com/minecraft/mc-mods/discord/files/2879457
The latest build should be fixed.
