### ISSUE TITLE
crash on launch 1.15.1-30.0.30

### ISSUE THREAD

**Issue by SDUBZ** [mekanism/Mekanism#5725]
java.lang.NullPointerException: Registry Object not present

Forge: 1.15.1-30.0.30
mekanism: Mekanism-1.15.1-9.9.0.391
MekanismGenerators-1.15.1-9.9.0.391
MekanismTools-1.15.1-9.9.0.391

crash log:
[crash-2020-01-07_22.08.46-client.txt](https://github.com/mekanism/Mekanism/files/4030351/crash-2020-01-07_22.08.46-client.txt)

logs:
[latest.log](https://github.com/mekanism/Mekanism/files/4030352/latest.log)

**Comment by pupnewfster** [comment]
The crash itself is not due to what the crashlog states so it is good that you included your latest log. Forge for 1.14+ has an issue where the crashlog it gives during startup is not always for the mod that caused the crash, because it does not stop loading on the first fatal error it comes across.

```
[22:08:44] [Render thread/ERROR]: Encountered exception executing deferred work
java.util.concurrent.CompletionException: java.lang.ArrayIndexOutOfBoundsException: 1
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:1.8.0_231]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:1.8.0_231]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_231]
	at net.minecraftforge.fml.DeferredWorkQueue.lambda$makeRunnable$6(DeferredWorkQueue.java:208) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_231]
	at java.util.concurrent.CompletableFuture.asyncRunStage(Unknown Source) ~[?:1.8.0_231]
	at java.util.concurrent.CompletableFuture.runAsync(Unknown Source) ~[?:1.8.0_231]
	at net.minecraftforge.fml.DeferredWorkQueue.makeRunnable(DeferredWorkQueue.java:206) ~[?:?]
	at net.minecraftforge.fml.DeferredWorkQueue.lambda$runTasks$4(DeferredWorkQueue.java:199) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_231]
	at java.util.concurrent.ConcurrentLinkedDeque$CLDSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:1.8.0_231]
	at net.minecraftforge.fml.DeferredWorkQueue.runTasks(DeferredWorkQueue.java:199) ~[?:?]
	at net.minecraftforge.fml.ModList.dispatchParallelEvent(ModList.java:151) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$static$2(ModList.java:98) ~[?:?]
	at net.minecraftforge.fml.LifecycleEventProvider.dispatch(LifecycleEventProvider.java:71) ~[?:?]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:197) ~[?:?]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$2(ClientModLoader.java:97) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:97) ~[?:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:393) ~[?:?]
	at net.minecraft.client.main.Main.main(SourceFile:164) ~[1.15.1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.15.1-30.0.30.jar:30.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at thelm.jaopca.data.DataCollector.collectData(DataCollector.java:63) ~[?:3.0.0.15]
	at thelm.jaopca.events.CommonEventHandler.lambda$onConstruct$0(CommonEventHandler.java:57) ~[?:3.0.0.15]
	... 35 more
```

is the crash so I am guessing if you remove JAOPCA it will work. If that is indeed the case you should report it to JAOPCA so that it can be fixed.

**Comment by pupnewfster** [comment]
Mentioned it to the JAOPCA dev and it should be fixed in https://www.curseforge.com/minecraft/mc-mods/jaopca/files/2856286
