### ISSUE TITLE
Charging slot exception

### ISSUE THREAD

**Issue by thiakil** [mekanism/Mekanism#5773]
Charging portable tele in creative energy cube, this happened in console when it became full (no crash). GUI was open at the time

```
java.lang.RuntimeException: Invalid stack for slot.
	at mekanism.common.inventory.slot.BasicInventorySlot.setStack(BasicInventorySlot.java:126) ~[Mekanism-1.15.main/:?] {re:classloading}
	at mekanism.common.inventory.slot.BasicInventorySlot.setStack(BasicInventorySlot.java:107) ~[Mekanism-1.15.main/:?] {re:classloading}
	at mekanism.common.inventory.container.slot.InventoryContainerSlot.putStack(InventoryContainerSlot.java:55) ~[Mekanism-1.15.main/:?] {re:classloading}
	at net.minecraft.inventory.container.Container.putStackInSlot(Container.java:456) ~[forge-1.15.1-30.0.36_mapped_snapshot_20200110-1.14.3-recomp.jar:?] {re:classloading}
	at net.minecraft.client.network.play.ClientPlayNetHandler.handleSetSlot(ClientPlayNetHandler.java:1151) ~[forge-1.15.1-30.0.36_mapped_snapshot_20200110-1.14.3-recomp.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.network.play.server.SSetSlotPacket.processPacket(SSetSlotPacket.java:26) ~[forge-1.15.1-30.0.36_mapped_snapshot_20200110-1.14.3-recomp.jar:?] {re:classloading}
	at net.minecraft.network.play.server.SSetSlotPacket.processPacket(SSetSlotPacket.java:11) ~[forge-1.15.1-30.0.36_mapped_snapshot_20200110-1.14.3-recomp.jar:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:19) ~[forge-1.15.1-30.0.36_mapped_snapshot_20200110-1.14.3-recomp.jar:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.run(ThreadTaskExecutor.java:140) ~[forge-1.15.1-30.0.36_mapped_snapshot_20200110-1.14.3-recomp.jar:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.run(RecursiveEventLoop.java:22) ~[forge-1.15.1-30.0.36_mapped_snapshot_20200110-1.14.3-recomp.jar:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.driveOne(ThreadTaskExecutor.java:110) ~[forge-1.15.1-30.0.36_mapped_snapshot_20200110-1.14.3-recomp.jar:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.drainTasks(ThreadTaskExecutor.java:97) ~[forge-1.15.1-30.0.36_mapped_snapshot_20200110-1.14.3-recomp.jar:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:887) ~[forge-1.15.1-30.0.36_mapped_snapshot_20200110-1.14.3-recomp.jar:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.run(Minecraft.java:520) ~[forge-1.15.1-30.0.36_mapped_snapshot_20200110-1.14.3-recomp.jar:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:176) ~[forge-1.15.1-30.0.36_mapped_snapshot_20200110-1.14.3-recomp.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_232] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_232] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232] {}
	at net.minecraftforge.userdev.FMLUserdevClientLaunchProvider.lambda$launchService$0(FMLUserdevClientLaunchProvider.java:55) ~[forge-1.15.1-30.0.36_mapped_snapshot_20200110-1.14.3-recomp.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at net.minecraftforge.userdev.LaunchTesting.main(LaunchTesting.java:101) [forge-1.15.1-30.0.36_mapped_snapshot_20200110-1.14.3-recomp.jar:?] {}
```

**Comment by pupnewfster** [comment]
Closing as 9.9.3 is now released and approved on curseforge.
