### ISSUE TITLE
Failure with Dank Storage Mod

### ISSUE THREAD

**Issue by MeinKraft** [mekanism/Mekanism#5789]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When using the latest Dank Storage mod (version 2.4) and Mekanism, Minecraft crashes

I should say that the latest Mekanism (9.9.3-394) fails with Dank Storage 2.3 and 2.4 with the same error - I reported here because Mekanism is mentioned in the Crash log

Mekanism 9.9.2-393 and Dank Storage 2.3 work fine together

#### Steps to reproduce:
1. Install Mekanism 9.9.2-393
2. Install Dank Storage 2.4
3. run Minecraft and crash

#### Version (make sure you are on the latest version before reporting):
**Forge:** 30.0.41
**Mekanism:** 9.9.2-393 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://pastebin.com/9f28C4gw

**Comment by pupnewfster** [comment]
Can you upload the entire `latest.log` I believe that this has to do with <https://github.com/MinecraftForge/MinecraftForge/issues/6374> in that it doesn't show the actual cause of the crash.

**Comment by MeinKraft** [comment]
https://pastebin.com/8k3yAz3q is the latest.log using Meka 9.9.3-394/DankStorage2.4

**Comment by Amcro** [comment]
@pupnewfster is right it's the forge issue also dank storage mod works fine with latest version of mekanism and version 2.2a of dank storage

**Comment by pupnewfster** [comment]
The actual crash shown in the latest log

```
[23:48:40] [modloading-worker-10/ERROR]: Failed to create mod instance. ModID: dankstorage, class tfar.dankstorage.DankStorage
java.lang.IllegalStateException: install mixin
    at tfar.dankstorage.DankStorage.<init>(DankStorage.java:52) ~[?:2.4]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
    at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51]
    at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:131) [?:30.0]
    at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$2205/1354114266.accept(Unknown Source) [?:30.0]
    at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
    at java.util.function.Consumer$$Lambda$2204/1614017388.accept(Unknown Source) [?:1.8.0_51]
    at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
    at java.util.function.Consumer$$Lambda$2204/1614017388.accept(Unknown Source) [?:1.8.0_51]
    at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) [?:?]
    at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:134) [?:?]
    at net.minecraftforge.fml.ModList$$Lambda$2316/1341754663.accept(Unknown Source) [?:?]
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_51]
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) [?:1.8.0_51]
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) [?:1.8.0_51]
    at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) [?:1.8.0_51]
    at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) [?:1.8.0_51]
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
```
