### ISSUE TITLE
1.15.2 crash on startup 

### ISSUE THREAD

**Issue by SpringyBoi** [mekanism/Mekanism#5826]
hi! so I'm writing this because a couple of features were causing Minecraft to crash on startup. I don't understand the exact details, so I'll just let the crash log explain it. Massive thanks if you can fix it! (P.S. don't make fun of my specs because I know they suck XD):
https://pastebin.com/bFZv6uQU

**Comment by pupnewfster** [comment]
Firstly please don't delete the format, as the version number is useful, and in the future either use gist or pastebin for uploading your logs. Also please upload your latest log as I believe something is causing a crash before this crashlog is generated.

**Comment by SpringyBoi** [comment]
Update: first of all; my apologies! as you might be able to tell this is my first time writing an issue/problem on a Minecraft mod. And another thing: after doing some more testing I thing there Isn't a problem with this mod, but instead the main Mekanism mod.

**Comment by pupnewfster** [comment]
??? This is the main Mekanism mod, and I still want the latest log file so I can point you at what is actually causing the issue.

**Comment by SpringyBoi** [comment]
[crash-2020-01-28_22.49.39-client.txt](https://github.com/mekanism/Mekanism/files/4126084/crash-2020-01-28_22.49.39-client.txt)
I'm sorry! I don't really use Pastebin and I can't be bothered to make an account at the moment, so I'm just gonna upload it as a file, but just in case anything goes wrong my Forge version is 31.0.1

**Comment by SpringyBoi** [comment]
The first thing it says is: 
java.lang.ExceptionInInitializerError: null
	at mekanism.api.providers.IGasProvider.getGasStack(IGasProvider.java:16) ~[?:?] {re:classloading}

And it keeps saying that it "Cannot create a GasStack from an unregistered gas"

**Comment by pupnewfster** [comment]
No I don't want your crash report you already gave that I want the file in the logs folder called `latest` or `latest.log`

**Comment by SpringyBoi** [comment]
[latest.log](https://github.com/mekanism/Mekanism/files/4126155/latest.log)

**Comment by SpringyBoi** [comment]
I found this. I hope this helps a little (if at all)

**Comment by pupnewfster** [comment]
As I thought something was causing a crash before hand and it was not showing properly in the crash log due to: https://github.com/MinecraftForge/MinecraftForge/issues/6374

You should report the bug to the RandomPatches mod as this crash is not actually due to Mekanism.

```
[28Jan2020 22:47:39.325] [Render thread/ERROR] [net.minecraftforge.coremod.transformer.CoreModBaseTransformer/COREMOD]: Error occurred applying transform of coremod patches/Entity.js function RandomPatches Entity Transformer
jdk.nashorn.internal.runtime.ECMAException: TypeError: Cannot set property "label" of undefined
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.Undefined.set(Undefined.java:157) ~[nashorn.jar:?]
	at jdk.nashorn.internal.scripts.Script$Recompilation$97$2465A$\^eval\_.patchRead(<eval>:122) ~[?:?]
	at jdk.nashorn.internal.scripts.Script$Recompilation$94$744AAA$\^eval\_.patch(<eval>:26) ~[?:?]
	at jdk.nashorn.internal.scripts.Script$Recompilation$93$1129A$\^eval\_.initializeCoreMod$transformer(<eval>:52) ~[?:?]
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:638) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:229) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:387) ~[nashorn.jar:?]
	at jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:110) ~[nashorn.jar:?]
	at net.minecraftforge.coremod.transformer.CoreModClassTransformer.runCoremod(CoreModClassTransformer.java:18) ~[coremods-2.0.0-milestone.1.jar:?]
	at net.minecraftforge.coremod.transformer.CoreModClassTransformer.runCoremod(CoreModClassTransformer.java:10) ~[coremods-2.0.0-milestone.1.jar:?]
	at net.minecraftforge.coremod.transformer.CoreModBaseTransformer.transform(CoreModBaseTransformer.java:38) [coremods-2.0.0-milestone.1.jar:?]
	at cpw.mods.modlauncher.TransformerHolder.transform(TransformerHolder.java:41) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.performVote(ClassTransformer.java:168) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:112) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:239) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:126) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96) [modlauncher-5.0.0-milestone.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at java.lang.ClassLoader.defineClass1(Native Method) [?:1.8.0_51]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) [?:1.8.0_51]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642) [?:1.8.0_51]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:127) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96) [modlauncher-5.0.0-milestone.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at java.lang.ClassLoader.defineClass1(Native Method) [?:1.8.0_51]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) [?:1.8.0_51]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642) [?:1.8.0_51]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:127) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96) [modlauncher-5.0.0-milestone.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_51]
	at net.minecraft.client.main.Main.main(SourceFile:166) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.0.1.jar:31.0]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$420/1747631271.call(Unknown Source) [forge-1.15.2-31.0.1.jar:31.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?]
```

**Comment by SpringyBoi** [comment]
Ok! I'm sorry for all of this trouble!
