### ISSUE TITLE
Client side crash

### ISSUE THREAD

**Issue by BedrockLegends** [mekanism/Mekanism#5946]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Launch Client on Mekanism 1.15.2-9.915.407 and it crashes with below issue

#### Steps to reproduce:
1.Launch game and it crashes
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.15.2
**Mekanism:** 1.15.2-9.9.15.407
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://gist.github.com/BedrockLegends/77546944e89f0b5bd05fe761fcc5a761
[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Please provide your latest.log file as it is currently impossible to tell if Mekanism is actually the cause of the crash or not due to the crash log provided not actually containing any relevant information (https://github.com/MinecraftForge/MinecraftForge/issues/6374).

**Comment by BedrockLegends** [comment]
https://gist.github.com/BedrockLegends/e311ba4d896d6b91e1172d5a49cacf19

**Comment by pupnewfster** [comment]
As I suspected this doesn't seem to have to do with Mekanism. The real crash/stack trace is below:

```
[15:27:45] [Render thread/ERROR]: Exception caught during firing event: net.minecraft.potion.Effect.construct(Lnet/minecraft/potion/EffectType;I)Lnet/minecraft/potion/Effect;
	Index: 6
	Listeners:
		0: NORMAL
		1: ASM: class com.qouteall.hiding_in_the_bushes.ModMainForge$RegistryEvents onItemRegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		2: ASM: class com.qouteall.hiding_in_the_bushes.ModMainForge$RegistryEvents onBlocksRegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		3: ASM: class com.qouteall.hiding_in_the_bushes.ModMainForge$RegistryEvents onDimensionRegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		4: ASM: class com.qouteall.hiding_in_the_bushes.ModMainForge$RegistryEvents onEntityRegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		5: ASM: class com.qouteall.hiding_in_the_bushes.ModMainForge$RegistryEvents onPotionRegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		6: ASM: class com.qouteall.hiding_in_the_bushes.ModMainForge$RegistryEvents onEffectRegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
java.lang.NoSuchMethodError: net.minecraft.potion.Effect.construct(Lnet/minecraft/potion/EffectType;I)Lnet/minecraft/potion/Effect;
	at net.minecraft.potion.Effect.lambda$static$0(Effect.java:517)
	at net.minecraft.potion.Effect$$Lambda$638/64931689.apply(Unknown Source)
	at com.qouteall.hiding_in_the_bushes.ModMainForge$RegistryEvents.onEffectRegistry(ModMainForge.java:492)
	at net.minecraftforge.eventbus.ASMEventHandler_173_RegistryEvents_onEffectRegistry_Register.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$2222/1047600772.accept(Unknown Source)
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65)
	at java.util.function.Consumer$$Lambda$2215/28125426.accept(Unknown Source)
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65)
	at java.util.function.Consumer$$Lambda$2215/28125426.accept(Unknown Source)
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112)
	at net.minecraftforge.fml.ModList.lambda$dispatchSynchronousEvent$5(ModList.java:125)
	at net.minecraftforge.fml.ModList$$Lambda$4306/1365077151.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at net.minecraftforge.fml.ModList.dispatchSynchronousEvent(ModList.java:125)
	at net.minecraftforge.fml.ModList.lambda$static$1(ModList.java:96)
	at net.minecraftforge.fml.ModList$$Lambda$2186/261855196.dispatchEvent(Unknown Source)
	at net.minecraftforge.fml.LifecycleEventProvider.dispatch(LifecycleEventProvider.java:71)
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:197)
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$24(ModLoader.java:189)
	at net.minecraftforge.fml.ModLoader$$Lambda$4368/1213830903.accept(Unknown Source)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:967)
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:189)
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$2(ClientModLoader.java:97)
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2100/1710341932.run(Unknown Source)
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113)
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2101/1209559976.run(Unknown Source)
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:97)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:393)
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$457/839457812.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

[15:27:45] [Render thread/ERROR]: Caught exception during event RegistryEvent.Register<minecraft:mob_effect> dispatch for modid immersive_portals
java.lang.NoSuchMethodError: net.minecraft.potion.Effect.construct(Lnet/minecraft/potion/EffectType;I)Lnet/minecraft/potion/Effect;
	at net.minecraft.potion.Effect.lambda$static$0(Effect.java:517) ~[?:?]
	at net.minecraft.potion.Effect$$Lambda$638/64931689.apply(Unknown Source) ~[?:?]
	at com.qouteall.hiding_in_the_bushes.ModMainForge$RegistryEvents.onEffectRegistry(ModMainForge.java:492) ~[?:0.6]
	at net.minecraftforge.eventbus.ASMEventHandler_173_RegistryEvents_onEffectRegistry_Register.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.0.0-milestone.1-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106) [?:31.1]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$2222/1047600772.accept(Unknown Source) [?:31.1]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$2215/28125426.accept(Unknown Source) [?:1.8.0_51]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$2215/28125426.accept(Unknown Source) [?:1.8.0_51]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) [?:?]
	at net.minecraftforge.fml.ModList.lambda$dispatchSynchronousEvent$5(ModList.java:125) [?:?]
	at net.minecraftforge.fml.ModList$$Lambda$4306/1365077151.accept(Unknown Source) [?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1249) [?:1.8.0_51]
	at net.minecraftforge.fml.ModList.dispatchSynchronousEvent(ModList.java:125) [?:?]
	at net.minecraftforge.fml.ModList.lambda$static$1(ModList.java:96) [?:?]
	at net.minecraftforge.fml.ModList$$Lambda$2186/261855196.dispatchEvent(Unknown Source) [?:?]
	at net.minecraftforge.fml.LifecycleEventProvider.dispatch(LifecycleEventProvider.java:71) [?:?]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:197) [?:?]
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$24(ModLoader.java:189) [?:?]
	at net.minecraftforge.fml.ModLoader$$Lambda$4368/1213830903.accept(Unknown Source) [?:?]
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:967) [?:?]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:189) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$2(ClientModLoader.java:97) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2100/1710341932.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2101/1209559976.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:97) [?:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:393) [?:?]
	at net.minecraft.client.main.Main.main(SourceFile:166) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.18.jar:31.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$457/839457812.call(Unknown Source) [forge-1.15.2-31.1.18.jar:31.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?]
```
