### ISSUE TITLE
Crash on Launch 1.15.2 Error: java.lang.NullPointerException: Registry Object not present

### ISSUE THREAD

**Issue by Iglesias-Leafwind** [mekanism/Mekanism#5959]
Issue description:
Saw mekanism in crash report that is why I am asking for help here. from noob programmer to pro programmer ;).
Btw: I think it is also a bug with:
MixinBootstrap-1.0.2.jar
and
immersive-portals-0.6(for mc 1.15 with forge).jar

Steps to reproduce:
1.I Launch minecraft
2.Click play.
3.Wait for FML early loading progress to finish
4.Minecraft opens and instantly crashes

Versions:
Forge-31.1.18
Mekanism-1.15.2-9.9.15.407 
MekanismGenerators-1.15.2-9.9.15.407
MekanismTools-1.15.2-9.9.15.407

Crash log and latest log:

CRASH REPORT
[crash-2020-03-11_19.02.03-client.txt](https://github.com/mekanism/Mekanism/files/4320293/crash-2020-03-11_19.02.03-client.txt)

LATEST LOG after CRASH REPORT
[latest.log](https://github.com/mekanism/Mekanism/files/4320289/latest.log)

**Comment by pupnewfster** [comment]
Seems to be a bug in Minecolonies/something breaking minecolonies.
```
[19:01:50] [modloading-worker-3/ERROR]: Failed to create mod instance. ModID: minecolonies, class com.minecolonies.coremod.MineColonies
java.lang.NoClassDefFoundError: com/ldtteam/structurize/client/gui/WindowBuildTool$FreeMode
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_51]
	at java.lang.Class.privateGetPublicMethods(Class.java:2902) ~[?:1.8.0_51]
	at java.lang.Class.getMethods(Class.java:1615) ~[?:1.8.0_51]
	at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:69) ~[eventbus-2.0.0-milestone.1-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:112) ~[eventbus-2.0.0-milestone.1-service.jar:?]
	at com.minecolonies.coremod.MineColonies.<init>(MineColonies.java:87) ~[?:0.10.716-RELEASE]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:131) [?:31.1]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$2175/1472719920.accept(Unknown Source) [?:31.1]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$2174/1012364136.accept(Unknown Source) [?:1.8.0_51]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$2174/1012364136.accept(Unknown Source) [?:1.8.0_51]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) [?:?]
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:134) [?:?]
	at net.minecraftforge.fml.ModList$$Lambda$2309/1349918930.accept(Unknown Source) [?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_51]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) [?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) [?:1.8.0_51]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
Caused by: java.lang.ClassNotFoundException: com.ldtteam.structurize.client.gui.WindowBuildTool$FreeMode
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:101) ~[modlauncher-5.0.0-milestone.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	... 30 more
```
