### ISSUE TITLE
1.15.2-[java.lang.ExceptionInInitializerError: null]

### ISSUE THREAD

**Issue by SDUBZ** [mekanism/Mekanism#5961]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
mekanism.api.chemical.gas.BasicGasTank.getEmptyStack(BasicGasTank.java:83) ~[?:?] {re:classloading}

#### Steps to reproduce:
1.load up with versions
2. get a lovely output 
3. no play game with mods :( 

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.15.2-31.1.18
**Mekanism:** Mekanism-1.15.2-9.9.15.407 plus addons 407

Crash:
[crash-2020-03-12_22.52.58-client.txt](https://github.com/mekanism/Mekanism/files/4324216/crash-2020-03-12_22.52.58-client.txt)

log:
[latest.log](https://github.com/mekanism/Mekanism/files/4324213/latest.log)

**Comment by pupnewfster** [comment]
```
[22:52:56] [Render thread/ERROR]: Exception caught during firing event: szewek.fl.util.FluxItemTier.<init>(IIFFILjava/lang/String;Lnet/minecraft/item/Item;)V
	Index: 2
	Listeners:
		0: NORMAL
		1: ASM: class szewek.flux.F recipes(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		2: ASM: class szewek.flux.F items(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		3: ASM: class szewek.flux.F blocks(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		4: ASM: class szewek.flux.F containers(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		5: ASM: class szewek.flux.F tiles(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		6: ASM: class szewek.flux.F professions(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		7: ASM: class szewek.flux.F pointsOfInterest(Lnet/minecraftforge/event/RegistryEvent$Register;)V
java.lang.NoSuchMethodError: szewek.fl.util.FluxItemTier.<init>(IIFFILjava/lang/String;Lnet/minecraft/item/Item;)V
	at szewek.flux.F$I.<clinit>(F.java:237)
	at szewek.flux.F.items(F.java:87)
	at net.minecraftforge.eventbus.ASMEventHandler_805_F_items_Register.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$2232/1108121945.accept(Unknown Source)
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65)
	at java.util.function.Consumer$$Lambda$2225/943533613.accept(Unknown Source)
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65)
	at java.util.function.Consumer$$Lambda$2225/943533613.accept(Unknown Source)
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112)
	at net.minecraftforge.fml.ModList.lambda$dispatchSynchronousEvent$5(ModList.java:125)
	at net.minecraftforge.fml.ModList$$Lambda$6191/595485100.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at net.minecraftforge.fml.ModList.dispatchSynchronousEvent(ModList.java:125)
	at net.minecraftforge.fml.ModList.lambda$static$1(ModList.java:96)
	at net.minecraftforge.fml.ModList$$Lambda$2196/1833678351.dispatchEvent(Unknown Source)
	at net.minecraftforge.fml.LifecycleEventProvider.dispatch(LifecycleEventProvider.java:71)
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:197)
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$24(ModLoader.java:189)
	at net.minecraftforge.fml.ModLoader$$Lambda$6284/1488109748.accept(Unknown Source)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:967)
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:189)
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$2(ClientModLoader.java:97)
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2110/452106777.run(Unknown Source)
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113)
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2111/945965626.run(Unknown Source)
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:97)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:393)
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$472/173783788.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

[22:52:56] [Render thread/ERROR]: Caught exception during event RegistryEvent.Register<minecraft:item> dispatch for modid flux
java.lang.NoSuchMethodError: szewek.fl.util.FluxItemTier.<init>(IIFFILjava/lang/String;Lnet/minecraft/item/Item;)V
	at szewek.flux.F$I.<clinit>(F.java:237) ~[?:4.10.0]
	at szewek.flux.F.items(F.java:87) ~[?:4.10.0]
	at net.minecraftforge.eventbus.ASMEventHandler_805_F_items_Register.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.0.0-milestone.1-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106) [?:31.1]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$2232/1108121945.accept(Unknown Source) [?:31.1]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$2225/943533613.accept(Unknown Source) [?:1.8.0_51]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$2225/943533613.accept(Unknown Source) [?:1.8.0_51]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) [?:?]
	at net.minecraftforge.fml.ModList.lambda$dispatchSynchronousEvent$5(ModList.java:125) [?:?]
	at net.minecraftforge.fml.ModList$$Lambda$6191/595485100.accept(Unknown Source) [?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1249) [?:1.8.0_51]
	at net.minecraftforge.fml.ModList.dispatchSynchronousEvent(ModList.java:125) [?:?]
	at net.minecraftforge.fml.ModList.lambda$static$1(ModList.java:96) [?:?]
	at net.minecraftforge.fml.ModList$$Lambda$2196/1833678351.dispatchEvent(Unknown Source) [?:?]
	at net.minecraftforge.fml.LifecycleEventProvider.dispatch(LifecycleEventProvider.java:71) [?:?]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:197) [?:?]
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$24(ModLoader.java:189) [?:?]
	at net.minecraftforge.fml.ModLoader$$Lambda$6284/1488109748.accept(Unknown Source) [?:?]
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:967) [?:?]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:189) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$2(ClientModLoader.java:97) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2110/452106777.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2111/945965626.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:97) [?:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:393) [?:?]
	at net.minecraft.client.main.Main.main(SourceFile:166) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.18.jar:31.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$472/173783788.call(Unknown Source) [forge-1.15.2-31.1.18.jar:31.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?]
```
