### ISSUE TITLE
[1.15.2]Client boot crash

### ISSUE THREAD

**Issue by EnterFor** [mekanism/Mekanism#5962]
I don't know what happened, it crashed during boot

#### Issue description:
https://paste.ubuntu.com/p/CTgDFpjZ66/

#### Version (make sure you are on the latest version before reporting):
Version information is in the report

**Comment by pupnewfster** [comment]
Please provide your latest log, as this crash report is invalid and is a side effect of https://github.com/MinecraftForge/MinecraftForge/issues/6374 so doesn't show any useful information.

**Comment by EnterFor** [comment]
> 请提供最新日志，因为此崩溃报告无效，并且是[MinecraftForge / MinecraftForge＃6374的](https://github.com/MinecraftForge/MinecraftForge/issues/6374)副作用，因此不会显示任何有用的信息。

[latest.log](https://github.com/mekanism/Mekanism/files/4324811/latest.log)

**Comment by pupnewfster** [comment]
Seems to have to do with minecolonies. I would check if there is an update available for their mod and install it if there is, otherwise you could try reporting it to them.
```
[net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: minecolonies, class com.minecolonies.coremod.MineColonies
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1214 column 4 path $.
	at com.google.gson.Gson.fromJson(Gson.java:902) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:852) ~[gson-2.8.0.jar:?]
	at com.ldtteam.structurize.util.LanguageHandler$LanguageCache.load(LanguageHandler.java:236) ~[?:0.10.274-ALPHA]
	at com.ldtteam.structurize.util.LanguageHandler$LanguageCache.access$400(LanguageHandler.java:207) ~[?:0.10.274-ALPHA]
	at com.ldtteam.structurize.util.LanguageHandler.loadLangPath(LanguageHandler.java:203) ~[?:0.10.274-ALPHA]
	at com.minecolonies.coremod.MineColonies.<init>(MineColonies.java:79) ~[?:0.10.753-BETA]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_241]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_241]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:131) ~[?:31.1]
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_241]
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_241]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:134) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) [?:1.8.0_241]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) [?:1.8.0_241]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) [?:1.8.0_241]
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.CountedCompleter.exec(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_241]
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1214 column 4 path $.
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[gson-2.8.0.jar:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:491) ~[gson-2.8.0.jar:?]
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:184) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?]
	... 25 more
```
