### ISSUE TITLE
my minecraft keeps crashing and coming up with this:     The game crashed whilst initializing game Error: java.lang.NullPointerException: Registry Object not present

### ISSUE THREAD

**Issue by weaponsmith777** [mekanism/Mekanism#5977]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
---- Minecraft Crash Report ----
// Why did you do that?

Time: 3/18/20 7:11 PM
Description: Initializing game

java.lang.NullPointerException: Registry Object not present
	at java.util.Objects.requireNonNull(Objects.java:228) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:91) ~[?:?] {re:classloading}
	at trapcraft.TrapcraftMod.registerBlockColors(TrapcraftMod.java:108) ~[?:2.7.0] {re:classloading}
	at trapcraft.TrapcraftMod$$Lambda$2442/1345055218.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2075/802062915.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168) ~[?:31.1] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$30(ModLoader.java:243) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader$$Lambda$2953/2020751256.accept(Unknown Source) ~[?:?] {}
	at java.util.HashMap.forEach(HashMap.java:1280) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:217) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:243) ~[?:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.onBlockColorsInit(ForgeHooksClient.java:204) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.color.BlockColors.func_186723_a(BlockColors.java:76) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:420) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:166) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.25.jar:31.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$413/361903111.call(Unknown Source) [forge-1.15.2-31.1.25.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:228)
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:91)
	at trapcraft.TrapcraftMod.registerBlockColors(TrapcraftMod.java:108)
	at trapcraft.TrapcraftMod$$Lambda$2442/1345055218.accept(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2075/802062915.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168)
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$30(ModLoader.java:243)
	at net.minecraftforge.fml.ModLoader$$Lambda$2953/2020751256.accept(Unknown Source)
	at java.util.HashMap.forEach(HashMap.java:1280)
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:217)
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:243)
	at net.minecraftforge.client.ForgeHooksClient.onBlockColorsInit(ForgeHooksClient.java:204)
	at net.minecraft.client.renderer.color.BlockColors.func_186723_a(BlockColors.java:76)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:420)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$413/361903111.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 624044000 bytes (595 MB) / 1405091840 bytes (1340 MB) up to 3008888832 bytes (2869 MB)
	CPUs: 4
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3228m -Xms256m -XX:PermSize=256m
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.25.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.25.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.4-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.25.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.25.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.25.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.25
	FML Language Providers: 
		javafml@31.1
		minecraft@1
		kotlinfml@1.5.0
	Mod List: 
		forge-1.15.2-31.1.25-client.jar Minecraft {minecraft@1.15.2 CREATE_REGISTRIES}
		Lightest-Lamp-Mod-1.15.2 (1).jar Lightest Lamps {lightestlamp@3.3.0 CREATE_REGISTRIES}
		Infinite-Trading-Mod-1.15.2 (1).jar Infinite Trading {inftrading@1.0 CREATE_REGISTRIES}
		Double-Doors-Mod-1.15.2 (1).jar Double Doors {doubledoors@1.2 CREATE_REGISTRIES}
		Just-Mob-Heads-Mod-1.15.2 (1).jar Just Mob Heads {jmh@2.2 CREATE_REGISTRIES}
		Inventory-Profiles-Mod-1.15.2 (1).jar Inventory Profiles {inventoryprofiles@0.2.0 CREATE_REGISTRIES}
		Useless-Mod-1.15.2 (1).jar Useless Mod {uselessmod@1.15.2-3.1.0 CREATE_REGISTRIES}
		Travel-Bag-Mod-1.15.2 (1).jar Travel Bag {travel_bag@1.1.0 CREATE_REGISTRIES}
		ShayBoxs-Durability101-Mod-1.15.2 (1).jar Durability101 {durability101@0.0.3 CREATE_REGISTRIES}
		Lollipop-Library-1.15.2 (1).jar Lollipop {lollipop@1.0.1 CREATE_REGISTRIES}
		Upsizer-Mod-1.15.2 (1).jar Upsizer {upsizer@5.1.0 CREATE_REGISTRIES}
		Snad-Mod-1.15.2 (1).jar Snad {snad@1.8.3.3a CREATE_REGISTRIES}
		Advanced-Mining-Dimension-Mod-1.15.2 (1).jar Mining World {mining_dimension@1.15.2-1.0.1 CREATE_REGISTRIES}
		Villager-Names-Mod-1.15.2 (1).jar Villager Names {vilnames@2.0 CREATE_REGISTRIES}
		jei-1.15.2-6.0.0.2 (1).jar Just Enough Items {jei@6.0.0.2 CREATE_REGISTRIES}
		Goblin-Traders-Mod-1.15.2 (1).jar Goblin Traders {goblintraders@1.2.0 CREATE_REGISTRIES}
		Simply-Backpacks-Mod-1.15.2 (1).jar Simply Backpacks {simplybackpacks@1.15.2-1.4.0 CREATE_REGISTRIES}
		Random-Enchants-Mod-1.15.2 (1).jar Random Enchants {randomenchants@3.1.0 ERROR}
		Trapcraft-Mod-1.15.2 (1).jar Trapcraft {trapcraft@2.7.0 CREATE_REGISTRIES}
		Inventory-Tweaks-Reborn-Mod-1.15.2 (1).jar Inventory Tweaks Reborn {invtweaks@1.15.2-1.0.1 CREATE_REGISTRIES}
		ForgeEndertech-1.15.2 (1).jar Forge Endertech {forgeendertech@6.0.0.0 CREATE_REGISTRIES}
		Advanced-Finders-Mod-1.15.2 (1).jar Advanced Finders {adfinders@4.0.0.0 CREATE_REGISTRIES}
		Large-Ore-Deposits-Mod-1.15.2 (1).jar Large Ore Deposits {adlods@3.0.0.0 CREATE_REGISTRIES}
		Carrots-Library-1.15.2 (1).jar Carrots Lib {carrots@2.5.0b1 CREATE_REGISTRIES}
		VanillaFoodPantry-Mod-1.15.2 (1).jar Vanilla Food Pantry {vanillafoodpantry@5.5.0b1 CREATE_REGISTRIES}
		Ores-Above-Diamonds-Mod-1.15.2 (1).jar Ores Above Diamonds {oresabovediamonds@3.0 CREATE_REGISTRIES}
		JourneyMap-Mod-1.15.2-Unlimited (1).jar Journeymap {journeymap@1.15.2-5.7.0beta1 CREATE_REGISTRIES}
		Ore-Excavation-Mod-1.15.2 (1).jar Ore Excavation {oreexcavation@NONE CREATE_REGISTRIES}
		Elementary-Staffs-Mod-1.15.2 (1).jar Elementary Staffs {element@1.6 CREATE_REGISTRIES}
		Powah-Mod-1.15.2 (1).jar Powah {powah@1.0.1 CREATE_REGISTRIES}
		Just-Player-Head-Mod-1.15.2 (1).jar Just Player Heads {jph@1.0 CREATE_REGISTRIES}
		Mutant-Beasts-Mod-1.15.2 (1).jar Mutant Beasts {mutantbeasts@1.15.2-1.0.1 CREATE_REGISTRIES}
		Inventory-Crafting-Grid-Mod-1.15.2 (1).jar invcrafting {invcrafting@1.15.2-1.1.0 CREATE_REGISTRIES}
		Dragon-Drops-Elytra-Mod-1.15.2 (1).jar Dragon Drops Elytra {dragondropsel@1.0 CREATE_REGISTRIES}
		Nether-Portal-Spread-Mod-1.15.2 (1).jar Nether Portal Spread {netherpspr@2.1 CREATE_REGISTRIES}
		Hwyla-Mod-1.15.2 (1).jar Waila {waila@version CREATE_REGISTRIES}
		Extra-Disks-Mod-1.15.2 (1).jar Extra Disks {extradisks@1.15.1-1.2 CREATE_REGISTRIES}
		forge-1.15.2-31.1.25-universal.jar Forge {forge@31.1.25 CREATE_REGISTRIES}
		Bountiful-Mod-1.15.2 (1).jar Bountiful {bountiful@3.0.0-1.15.2 CREATE_REGISTRIES}
		Refined-Storage-Mod-1.15.2 (1).jar Refined Storage {refinedstorage@1.8.1 CREATE_REGISTRIES}
		Healing-Campfire-Mod-1.15.2 (1).jar Healing Campfire {healingcf@1.7 CREATE_REGISTRIES}
		Iron-Chests-Mod-1.15.2 (1).jar Iron Chests {ironchest@1.15.2-10.0.1 CREATE_REGISTRIES}
		Simple-Diving-Gear-Mod-1.15.2 (1).jar Simple Diving Gear {simpledivegear@4.0.1 mc 1.15.2 CREATE_REGISTRIES}
	Launched Version: forge-31.1.25
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics 620 GL version 4.5.0 - Build 23.20.16.4973, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 4x Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
In the future please either use pastebin or gist. I do not enjoy scrolling through a mile of text just to get to the bottom. Also please provide your latest.log as this crash report is invalid due to https://github.com/MinecraftForge/MinecraftForge/issues/6374
