### ISSUE TITLE
Rotary Condensentrator causing game to crash

### ISSUE THREAD

**Issue by Zec-Wicks** [mekanism/Mekanism#5980]
#5547 

# Issue description:
whenever i join a modded forge server and a rotary condensentrator is placed down, i join for a moment, then my game saves and crashes. if i place down a rotary condensentrator i crash in the same way.

#### Steps to reproduce:
1. join server with placed rotary condensentrator
2. crash

1a. join server with no rotary condensentrator
2a. place rotary condensentrator
3a. crash

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 21/03/20 2:14 PM
Description: Tesselating block model

java.lang.ArrayIndexOutOfBoundsException: 8191
	at net.minecraft.client.renderer.chunk.ChunkRenderCache.func_180495_p(SourceFile:100) ~[?:?] {re:classloading}
	at mekanism.common.block.BlockBounding.func_220053_a(BlockBounding.java:202) ~[?:?] {re:classloading}
	at net.minecraft.block.BlockState.func_215700_a(BlockState.java:197) ~[?:?] {re:classloading}
	at net.minecraft.block.BlockState.func_196954_c(BlockState.java:193) ~[?:?] {re:classloading}
	at net.minecraft.block.Block.func_200123_i(Block.java:426) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.block.BlockState.func_200131_a(BlockState.java:86) ~[?:?] {re:classloading}
	at net.minecraft.block.Block.func_200011_d(Block.java:434) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.block.BlockState.func_200016_a(BlockState.java:90) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.BlockModelRenderer$AmbientOcclusionFace.func_228807_a_(BlockModelRenderer.java:308) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.BlockModelRenderer.func_228799_a_(BlockModelRenderer.java:122) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelSmooth(BlockModelRenderer.java:83) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:51) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderModel(BlockRendererDispatcher.java:62) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_228940_a_(ChunkRenderDispatcher.java:527) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_225618_a_(ChunkRenderDispatcher.java:449) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender.func_228936_k_(ChunkRenderDispatcher.java:383) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_228902_a_(ChunkRenderDispatcher.java:164) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228437_a_(WorldRenderer.java:784) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:887) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:600) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:422) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:925) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:554) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.27.jar:31.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$407/1526305386.call(Unknown Source) [forge-1.15.2-31.1.27.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.chunk.ChunkRenderCache.func_180495_p(SourceFile:100)
	at mekanism.common.block.BlockBounding.func_220053_a(BlockBounding.java:202)
	at net.minecraft.block.BlockState.func_215700_a(BlockState.java:197)
	at net.minecraft.block.BlockState.func_196954_c(BlockState.java:193)
	at net.minecraft.block.Block.func_200123_i(Block.java:426)
	at net.minecraft.block.BlockState.func_200131_a(BlockState.java:86)
	at net.minecraft.block.Block.func_200011_d(Block.java:434)
	at net.minecraft.block.BlockState.func_200016_a(BlockState.java:90)
	at net.minecraft.client.renderer.BlockModelRenderer$AmbientOcclusionFace.func_228807_a_(BlockModelRenderer.java:308)
	at net.minecraft.client.renderer.BlockModelRenderer.func_228799_a_(BlockModelRenderer.java:122)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelSmooth(BlockModelRenderer.java:83)

-- Block model being tesselated --
Details:
	Block: Block{mekanism:rotary_condensentrator}[active=false,facing=north,waterlogged=false]
	Block location: World: (459,23,-7025), Chunk: (at 11,1,15 in 28,-440; contains blocks 448,0,-7040 to 463,255,-7025), Region: (0,-14; contains chunks 0,-448 to 31,-417, blocks 0,0,-7168 to 511,255,-6657)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:51)

-- Block being tesselated --
Details:
	Block: Block{mekanism:rotary_condensentrator}[active=false,facing=north,waterlogged=false]
	Block location: World: (459,23,-7025), Chunk: (at 11,1,15 in 28,-440; contains blocks 448,0,-7040 to 463,255,-7025), Region: (0,-14; contains chunks 0,-448 to 31,-417, blocks 0,0,-7168 to 511,255,-6657)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderModel(BlockRendererDispatcher.java:62)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_228940_a_(ChunkRenderDispatcher.java:527)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_225618_a_(ChunkRenderDispatcher.java:449)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender.func_228936_k_(ChunkRenderDispatcher.java:383)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_228902_a_(ChunkRenderDispatcher.java:164)
	at net.minecraft.client.renderer.WorldRenderer.func_228437_a_(WorldRenderer.java:784)
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:887)
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:600)

-- Affected level --
Details:
	All players: 2 total; [ClientPlayerEntity['Zec_Wicks'/38224, l='MpServer', x=459.65, y=23.00, z=-7025.70], RemoteClientPlayerEntity['Super_Craft1001'/10132, l='MpServer', x=458.07, y=25.00, z=-7022.50]]
	Chunk stats: Client Chunk Cache: 729, 483
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 3156828361752724329
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (224,66,176), Chunk: (at 0,4,0 in 14,11; contains blocks 224,0,176 to 239,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 4822051 game time, 1463279 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:442)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1764)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:568)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$407/1526305386.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 885608536 bytes (844 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.27.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.27.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.4-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.27.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.27.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.27.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.27
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		forge-1.15.2-31.1.27-client.jar Minecraft {minecraft@1.15.2 DONE}
		Mekanism-Mod-Core-1.15.2.jar Mekanism {mekanism@9.9.5 DONE}
		forge-1.15.2-31.1.27-universal.jar Forge {forge@31.1.27 DONE}
		Mekanism-Mod-Tools-1.15.2.jar Mekanism: Tools {mekanismtools@9.9.5 DONE}
		Xaeros_Minimap_20.5.1_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.5.1 DONE}
		Mekanism-Mod-Generators-1.15.2.jar Mekanism: Generators {mekanismgenerators@9.9.5 DONE}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 DONE}
	Launched Version: 1.15.2-forge-31.1.27
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1070 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 442.19, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 1600 Six-Core Processor 

If a solution to this issue could be found, i would be extremely grateful.
Thanks!

**Comment by pupnewfster** [comment]
Update mekanism that is an ancient version for 1.15, not sure if you will be able to directly load your world, you probably are better off starting a new one. Otherwise read through all the changelogs for how to properly update your world to make sure it will properly load.
