### ISSUE TITLE
Can't start minecraft-Minecraft crashed

### ISSUE THREAD

**Issue by HastumeMiku** [mekanism/Mekanism#5993]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 27/03/20 12:42
Description: Initializing game

java.lang.NullPointerException: Registry Object not present
	at java.util.Objects.requireNonNull(Objects.java:228) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:91) ~[?:?] {re:classloading}
	at mekanism.common.registration.WrappedRegistryObject.get(WrappedRegistryObject.java:23) ~[?:?] {re:classloading}
	at mekanism.common.registration.impl.ParticleTypeRegistryObject.getParticleType(ParticleTypeRegistryObject.java:17) ~[?:?] {re:classloading}
	at mekanism.client.ClientRegistration.registerParticleFactories(ClientRegistration.java:343) ~[?:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_384_ClientRegistration_registerParticleFactories_ParticleFactoryRegisterEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168) ~[?:31.1] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$30(ModLoader.java:243) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader$$Lambda$2462/1054220477.accept(Unknown Source) ~[?:?] {}
	at java.util.HashMap.forEach(HashMap.java:1280) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:217) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:243) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:438) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:shouldersurfing:coremodone,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:166) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.18.jar:31.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$421/2034411604.call(Unknown Source) [forge-1.15.2-31.1.18.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:228)
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:91)
	at mekanism.common.registration.WrappedRegistryObject.get(WrappedRegistryObject.java:23)
	at mekanism.common.registration.impl.ParticleTypeRegistryObject.getParticleType(ParticleTypeRegistryObject.java:17)
	at mekanism.client.ClientRegistration.registerParticleFactories(ClientRegistration.java:343)
	at net.minecraftforge.eventbus.ASMEventHandler_384_ClientRegistration_registerParticleFactories_ParticleFactoryRegisterEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168)
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$30(ModLoader.java:243)
	at net.minecraftforge.fml.ModLoader$$Lambda$2462/1054220477.accept(Unknown Source)
	at java.util.HashMap.forEach(HashMap.java:1280)
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:217)
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:243)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:438)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$421/2034411604.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3033023616 bytes (2892 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.18
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 LOAD_REGISTRIES}
		Ma-Enchants-1.15.2-3.0.0 - Copy.jar Ma Enchants {ma-enchants@1.15.2-3.0.0 LOAD_REGISTRIES}
		Cucumber-1.15.2-3.0.1.jar Cucumber Library {cucumber@3.0.1 LOAD_REGISTRIES}
		TrashSlot_1.15.2-11.0.0.jar TrashSlot {trashslot@11.0.0 LOAD_REGISTRIES}
		torchslabmod-1.15.1_v1.5.jar Torch Slab Mod {torchslabmod@1.5.0 LOAD_REGISTRIES}
		NetherPortalFix_1.15.2-6.0.0.jar NetherPortalFix {netherportalfix@6.0.0 LOAD_REGISTRIES}
		GoodSkeletonDontStrafe-v1.1.2-1.15.1.jar Good Skeletons Don't Strafe {goodskeletonsdontstrafe@1.1.2 LOAD_REGISTRIES}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 LOAD_REGISTRIES}
		SwordBlockingCombat-v1.3-1.15.2.jar Sword Blocking Combat {swordblockingcombat@1.3 LOAD_REGISTRIES}
		DoggyTalents-1.15.2-1.15.2.3.jar Doggy Talents {doggytalents@1.15.2.3 LOAD_REGISTRIES}
		extrabows-v1.15.2+b1 - Copy.jar Extra Bows {extrabows@v1.15.2 b1 LOAD_REGISTRIES}
		ProjectE-1.15.2-PE1.0.2B - Copy.jar ProjectE {projecte@1.0.2B LOAD_REGISTRIES}
		Mekanism-1.15.2-9.9.17.409.jar Mekanism {mekanism@9.9.17 LOAD_REGISTRIES}
		IndustrialAgriculture[Core]-1.15.2-1.5.4.jar Industrial Agriculture {industrialagriculture@1.15.2-1.5.4 LOAD_REGISTRIES}
		KleeSlabs_1.15.2-8.0.0.jar KleeSlabs {kleeslabs@8.0.0 LOAD_REGISTRIES}
		BowInfinityFix-1.15.2-rv8.jar Bow Infinity Fix {bowinfinityfix@rv8 LOAD_REGISTRIES}
		IronJetpacks-1.15.2-3.0.0 - Copy.jar Iron Jetpacks {ironjetpacks@3.0.0 LOAD_REGISTRIES}
		XaerosWorldMap_1.5.5_Forge_1.15.2.jar Xaero's World Map {xaeroworldmap@1.5.5 LOAD_REGISTRIES}
		RingOfRepair-1.15.2-1.1.16 - Copy.jar Ring of Repair {ring_of_repair@1.1.16 LOAD_REGISTRIES}
		LightOverlay-4.2.jar Light Overlay Forge {lightoverlay-forge@4.2 LOAD_REGISTRIES}
		Controlling-6.1.1.jar Controlling {controlling@6.1.1 LOAD_REGISTRIES}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 LOAD_REGISTRIES}
		NoFog-1.15b1.jar NoFog {nofog@1.0.1 LOAD_REGISTRIES}
		NaturesCompass-1.15.2-1.8.4 - Copy.jar Nature's Compass {naturescompass@1.15.2-1.8.4 LOAD_REGISTRIES}
		SimpleStorageNetwork-1.15.2-0.2.4 - Copy.jar Simple Storage Network {storagenetwork@1.15.2-0.2.4 LOAD_REGISTRIES}
		SereneSeasons-1.15.2-3.0.0.66-universal - Copy.jar Serene Seasons {sereneseasons@1.15.2-3.0.0.65 LOAD_REGISTRIES}
		VanillaTweaks-1.15.2.1.5.18.jar VanillaTweaks {vanillatweaks@1.15.2.1.5.18 LOAD_REGISTRIES}
		FarmingForBlockheads_1.15.2-6.1.0 - Copy.jar Farming for Blockheads {farmingforblockheads@6.1.0 LOAD_REGISTRIES}
		RingOfTeleport-1.15.2-1.1.16 - Copy.jar Ring of Teleport {ring_of_teleport@1.1.16 LOAD_REGISTRIES}
		LightingWand-1.15.2-1.4.2 - Copy.jar Lighting Wand {lightingwand@1.4.2 LOAD_REGISTRIES}
		MekanismGenerators-1.15.2-9.9.17.409.jar Mekanism: Generators {mekanismgenerators@9.9.17 LOAD_REGISTRIES}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version LOAD_REGISTRIES}
		WaterStrainer-1.15.1-8.0.0.jar Water Strainer {waterstrainer@1.15.1-8.0.0 LOAD_REGISTRIES}
		SnowRealMagic-1.15.2-1.7.2.jar Snow! Real Magic! {snowrealmagic@1.7.2 LOAD_REGISTRIES}
		Kiwi-1.15.2-2.6.5.jar Kiwi {kiwi@2.6.5 LOAD_REGISTRIES}
		immersive-portals-0.8(forMc1.15withForge).jar Immersive Portals {immersive_portals@0.8 ERROR}
		extradisks-1.15.1-1.2 - Copy.jar Extra Disks {extradisks@1.15.1-1.2 LOAD_REGISTRIES}
		BetterThanMending-1.4.0.jar BetterThanMending {betterthanmending@1.4.0 LOAD_REGISTRIES}
		forge-1.15.2-31.1.18-universal.jar Forge {forge@31.1.18 LOAD_REGISTRIES}
		refinedstorage-1.8.1 - Copy.jar Refined Storage {refinedstorage@1.8.1 LOAD_REGISTRIES}
		MysticalAgriculture-1.15.2-3.0.0.jar Mystical Agriculture {mysticalagriculture@3.0.0 LOAD_REGISTRIES}
		ironchest-1.15.2-10.0.2 - Copy.jar Iron Chests {ironchest@1.15.2-10.0.1 LOAD_REGISTRIES}
		SimpleDivingGear-4.0.1+mc+1.15.2 - Copy.jar Simple Diving Gear {simpledivegear@4.0.1 mc 1.15.2 LOAD_REGISTRIES}
		forge-1.15.2-31.1.18-client.jar Minecraft {minecraft@1.15.2 LOAD_REGISTRIES}
		industrial-foregoing-1.15.2-2.2.1-f27c515 - Copy.jar Industrial Foregoing {industrialforegoing@2.2.1 LOAD_REGISTRIES}
		torchmaster-2.1.1-rc0.jar Torchmaster {torchmaster@2.1.1-rc0 LOAD_REGISTRIES}
		swingthroughgrass-1.15.2-1.4.0.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.0 LOAD_REGISTRIES}
		AmbientSounds_v3.0.17_mc1.15.2.jar Ambient Sounds {ambientsounds@3.0.3 LOAD_REGISTRIES}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 LOAD_REGISTRIES}
		titanium-1.15.2-2.3.6.jar Titanium {titanium@2.3.6 LOAD_REGISTRIES}
		BiomesOPlenty-1.15.2-10.0.0.345-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.342 LOAD_REGISTRIES}
		MekanismAdditions-1.15.2-9.9.17.409.jar Mekanism: Additions {mekanismadditions@9.9.17 LOAD_REGISTRIES}
		Durability101-1.15-0.0.3.jar Durability101 {durability101@0.0.3 LOAD_REGISTRIES}
		ShoulderSurfing-1.15.2-1.22.jar Shoulder Surfing {shouldersurfing@1.15.2-1.22 LOAD_REGISTRIES}
		RingOfGrowth-1.15.2-1.1.16 - Copy.jar Ring of Growth {ring_of_growth@1.1.16 LOAD_REGISTRIES}
		ceilingtorch-1.15.2-v1.5.jar Ceiling Torch {ceilingtorch@v1.5 LOAD_REGISTRIES}
		simplybackpacks-1.15.2-1.4.0.jar Simply Backpacks {simplybackpacks@1.15.2-1.4.0 LOAD_REGISTRIES}
		Xaeros_Minimap_20.4.0.1_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.4.0.1 LOAD_REGISTRIES}
		RingOfBlink-1.15.2-1.1.15 - Copy.jar Ring of Blink {ring_of_blink@1.1.15 LOAD_REGISTRIES}
		FastWorkbench-1.15.1-3.0.0.jar FastWorkbench {fastbench@3.0.0 LOAD_REGISTRIES}
		ClothConfig2-2.0.jar Cloth Config Forge v2 API {cloth-config2@2.0 LOAD_REGISTRIES}
		RingOfMiner-1.15.2-1.1.15 - Copy.jar Ring of Miner {ring_of_miner@1.1.15 LOAD_REGISTRIES}
		[1.15.2]+SecurityCraft+v1.8.17 - Copy.jar SecurityCraft {securitycraft@v1.8.17 LOAD_REGISTRIES}
		torcherino-10.0.1.jar Torcherino {torcherino@10.0.1 LOAD_REGISTRIES}
		OreExcavation-1.7.149.jar Ore Excavation {oreexcavation@NONE LOAD_REGISTRIES}
		performant-1.15-1.7.jar Performant {performant@1.7 LOAD_REGISTRIES}
		DoubleSlabs-1.15-2.0.1.jar Double Slabs {doubleslabs@2.0.1 LOAD_REGISTRIES}
		libnonymous-1.15.2-1.1.1.5.jar Libnonymous {libnonymous@1.1.1.5 LOAD_REGISTRIES}
		BonsaiTrees-2.1.2.6.jar Bonsai Trees 2 {bonsaitrees2@2.1.2.6 LOAD_REGISTRIES}
		RingOfEnderchest-1.15.2-1.1.16 - Copy.jar Ring of Enderchest {ring_of_enderchest@1.1.16 LOAD_REGISTRIES}
		MekanismTools-1.15.2-9.9.17.409.jar Mekanism: Tools {mekanismtools@9.9.17 LOAD_REGISTRIES}
		FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 LOAD_REGISTRIES}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 LOAD_REGISTRIES}
		AI-Improvements-1.15.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 LOAD_REGISTRIES}
		simplecoloredblocks-2.0.0 - Copy.jar Simple Colored Blocks {simplecoloredblocks@2.0.0 LOAD_REGISTRIES}
		RingOfAttraction-1.15.2-1.1.19 - Copy.jar Ring of Attraction {ring_of_attraction@1.1.19 LOAD_REGISTRIES}
		XL-Food-Mod-1.15.2-2.2.2.jar XL Food Mod {xlfoodmod@2.2.2 LOAD_REGISTRIES}
		refinedstorageaddons-0.6.1 - Copy.jar Refined Storage Addons {refinedstorageaddons@0.6.1 LOAD_REGISTRIES}
		FastLeafDecay-v20.jar FastLeafDecay {fastleafdecay@v20 LOAD_REGISTRIES}
		SoundFilters-0.13_for_1.15.2.jar Sound Filters {soundfilters@0.13_for_1.15.2 LOAD_REGISTRIES}
		SuperTools-1.1_1.15.2.jar Super Tools {supertools@1.1 LOAD_REGISTRIES}
		Cyclic-1.15.2-0.1.10 - Copy.jar Cyclic {cyclic@1.15.2-0.1.10 LOAD_REGISTRIES}
		bigbuckets-1.1.0.jar BigBuckets {bigbuckets@1.1.0 LOAD_REGISTRIES}
	Kiwi Modules: 
		kiwi:contributors
		snowrealmagic:snowrealmagic
	Launched Version: 1.15.2-forge-31.1.18
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) UHD Graphics 620 GL version 4.6.0 - Build 27.20.100.7922, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 8x Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz

**Comment by pupnewfster** [comment]
Please use pastebin or gist in the future so it is easier to read the log. Secondly please provide your latest.log file due to the fact this log gives no useful information due to: https://github.com/MinecraftForge/MinecraftForge/issues/6374
