### ISSUE TITLE
basic fluid tank error

### ISSUE THREAD

**Issue by AceSkym** [mekanism/Mekanism#6054]
The game crashed whilst initializing game
Error: java.lang.NullPointerException: Registry Object not present: mekanism:basic_fluid_tank

This is upon new install of the mod into a clean game.

Forge version 31.1.40
Minecraft 1.15.2
Mekanism-1.15.2-9.9.18.410

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 4/12/20 3:20 PM
Description: Initializing game

java.lang.NullPointerException: Registry Object not present: mekanism:basic_fluid_tank
	at java.util.Objects.requireNonNull(Objects.java:290) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:91) ~[?:?] {re:classloading}
	at mekanism.common.registration.DoubleWrappedRegistryObject.getPrimary(DoubleWrappedRegistryObject.java:23) ~[?:?] {re:classloading}
	at mekanism.common.registration.impl.BlockRegistryObject.getBlock(BlockRegistryObject.java:19) ~[?:?] {re:classloading}
	at mekanism.client.ClientRegistrationUtil.registerBlockColorHandler(ClientRegistrationUtil.java:108) ~[?:?] {re:classloading}
	at mekanism.client.ClientRegistration.registerItemColorHandlers(ClientRegistration.java:352) ~[?:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_680_ClientRegistration_registerItemColorHandlers_Item.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168) ~[?:31.1] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$30(ModLoader.java:243) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader$$Lambda$5984/207471579.accept(Unknown Source) ~[?:?] {}
	at java.util.HashMap.forEach(HashMap.java:1280) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:217) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:243) ~[?:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.onItemColorsInit(ForgeHooksClient.java:211) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.color.ItemColors.func_186729_a(ItemColors.java:84) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:421) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:166) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.40.jar:31.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$431/1398428044.call(Unknown Source) [forge-1.15.2-31.1.40.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}

**Comment by pupnewfster** [comment]
Please use gist or pastebin to make reading logs easier. This crash report provides no useful information due to https://github.com/MinecraftForge/MinecraftForge/issues/6374 so please provide your latest log
