### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by ppoozl** [mekanism/Mekanism#6060]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Server keep report Division by zero
didn't crash

#### Steps to reproduce:
1.unknown

#### Version (make sure you are on the latest version before reporting):
**Forge:31.1.44
**Mekanism:9.9.19.411
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
[13Apr2020 12:43:13.850] [Server thread/FATAL] [net.minecraft.world.World/]: ---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 4/13/20 12:43 PM
Description: Ticking block entity

java.lang.ArithmeticException: Division by zero
	at mekanism.api.math.FloatingLong.divideEquals(FloatingLong.java:329) ~[?:?] {re:classloading}
	at mekanism.api.math.FloatingLong.divide(FloatingLong.java:471) ~[?:?] {re:classloading}
	at mekanism.api.math.FloatingLong.divide(FloatingLong.java:503) ~[?:?] {re:classloading}
	at mekanism.common.tile.TileEntityThermalEvaporationController.lambda$createNewCachedRecipe$5(TileEntityThermalEvaporationController.java:244) ~[?:?] {re:classloading}
	at mekanism.api.recipes.cache.CachedRecipe.process(CachedRecipe.java:114) ~[?:?] {re:classloading}
	at mekanism.common.tile.TileEntityThermalEvaporationController.onUpdateServer(TileEntityThermalEvaporationController.java:167) ~[?:?] {re:classloading}
	at mekanism.common.tile.base.TileEntityMekanism.func_73660_a(TileEntityMekanism.java:519) ~[?:?] {re:classloading}
	at net.minecraft.world.World.func_217391_K(World.java:473) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:368) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at mekanism.api.math.FloatingLong.divideEquals(FloatingLong.java:329)
	at mekanism.api.math.FloatingLong.divide(FloatingLong.java:471)
	at mekanism.api.math.FloatingLong.divide(FloatingLong.java:503)
	at mekanism.common.tile.TileEntityThermalEvaporationController.lambda$createNewCachedRecipe$5(TileEntityThermalEvaporationController.java:244)
	at mekanism.api.recipes.cache.CachedRecipe.process(CachedRecipe.java:114)
	at mekanism.common.tile.TileEntityThermalEvaporationController.onUpdateServer(TileEntityThermalEvaporationController.java:167)
	at mekanism.common.tile.base.TileEntityMekanism.func_73660_a(TileEntityMekanism.java:519)

-- Block entity being ticked --
Details:
	Name: mekanism:thermal_evaporation_controller // mekanism.common.tile.TileEntityThermalEvaporationController
	Block: Block{mekanism:thermal_evaporation_controller}[active=true,facing=north]
	Block location: World: (-2392,24,-1447), Chunk: (at 8,1,9 in -150,-91; contains blocks -2400,0,-1456 to -2385,255,-1441), Region: (-5,-3; contains chunks -160,-96 to -129,-65, blocks -2560,0,-1536 to -2049,255,-1025)
	Block: Block{mekanism:thermal_evaporation_controller}[active=true,facing=north]
	Block location: World: (-2392,24,-1447), Chunk: (at 8,1,9 in -150,-91; contains blocks -2400,0,-1456 to -2385,255,-1441), Region: (-5,-3; contains chunks -160,-96 to -129,-65, blocks -2560,0,-1536 to -2049,255,-1025)
Stacktrace:
	at net.minecraft.world.World.func_217391_K(World.java:473)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:368)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
	at java.lang.Thread.run(Unknown Source)

**Comment by pupnewfster** [comment]
#6057

**Comment by pupnewfster** [comment]
Ignore me I am blind, misread the log

**Comment by pupnewfster** [comment]
Fixed in 9.9.20
