### ISSUE TITLE
jumping and falling on top of a cable.         jumping and falling on top of a cable. the game crashed (client) but the server continued

### ISSUE THREAD

**Issue by jerdm** [mekanism/Mekanism#6064]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
jumping and falling on top of a cable. jumping and falling on top of a cable. the game crashed (client) but the server continued

#### Steps to reproduce:
1. by jumping over a cable, the game crashed
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.43
**Mekanism:** 9.9.20.412
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 13/04/20 03:14 PM
Description: Unexpected error

java.lang.IllegalAccessError: tried to access class net.minecraft.client.renderer.model.ModelRenderer$TexturedQuad from class mekanism.client.model.ExtendedModelRenderer
	at mekanism.client.model.ExtendedModelRenderer.renderWireFrame(ExtendedModelRenderer.java:38) ~[?:?] {re:classloading}
	at mekanism.client.model.ExtendedModelRenderer.render(ExtendedModelRenderer.java:22) ~[?:?] {re:classloading}
	at mekanism.client.model.ModelSolarNeutronActivator.render(ModelSolarNeutronActivator.java:373) ~[?:?] {re:classloading}
	at mekanism.client.model.ModelSolarNeutronActivator.renderWireFrame(ModelSolarNeutronActivator.java:368) ~[?:?] {re:classloading}
	at mekanism.client.render.tileentity.RenderSolarNeutronActivator.renderWireFrame(RenderSolarNeutronActivator.java:47) ~[?:?] {re:classloading}
	at mekanism.client.render.RenderTickHandler.configurableMachine(RenderTickHandler.java:248) ~[?:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_908_RenderTickHandler_configurableMachine_HighlightBlock.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:168) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1038) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:voxelmap:transformerName,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:600) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:422) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:925) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) ~[1.15.2-forge-31.1.43.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.15.2-31.1.43.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241] {}
	at net.minecraft.a.m.main(Unknown Source) [laulib-1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at mekanism.client.model.ExtendedModelRenderer.renderWireFrame(ExtendedModelRenderer.java:38)
	at mekanism.client.model.ExtendedModelRenderer.render(ExtendedModelRenderer.java:22)
	at mekanism.client.model.ModelSolarNeutronActivator.render(ModelSolarNeutronActivator.java:373)
	at mekanism.client.model.ModelSolarNeutronActivator.renderWireFrame(ModelSolarNeutronActivator.java:368)
	at mekanism.client.render.tileentity.RenderSolarNeutronActivator.renderWireFrame(RenderSolarNeutronActivator.java:47)
	at mekanism.client.render.RenderTickHandler.configurableMachine(RenderTickHandler.java:248)
	at net.minecraftforge.eventbus.ASMEventHandler_908_RenderTickHandler_configurableMachine_HighlightBlock.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:168)
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1038)
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:600)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['JKMD'/1605, l='MpServer', x=-17.13, y=66.67, z=52.62]]
	Chunk stats: Client Chunk Cache: 361, 196
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: -4496982209240687827
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (128,63,-240), Chunk: (at 0,3,0 in 8,-15; contains blocks 128,0,-240 to 143,255,-225), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 274063 game time, 315670 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:442)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1764)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:573)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.a.m.main(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1190237328 bytes (1135 MB) / 3221225472 bytes (3072 MB) up to 3221225472 bytes (3072 MB)
	CPUs: 4
	JVM Flags: 9 total; -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:+IgnoreUnrecognizedVMOptions -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.43.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.43.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.4-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.43.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.43.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.43.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.2.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.43
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		UnionLib-1.15.2-1.0.0.jar UnionLib {unionlib@1.0.0 DONE}
		justenoughbeacons-2.0.jar Just Enough Beacons {justenoughbeacons@2.0 DONE}
		NetherPortalFix_1.15.2-6.0.0.jar NetherPortalFix {netherportalfix@6.0.0 DONE}
		extratrades-1.1.jar Extra Trades {extratrades@1.1 DONE}
		ForgeEndertech-1.15.2-6.0.2.0-build.0018.jar Forge Endertech {forgeendertech@6.0.2.0 DONE}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 DONE}
		rangedpumps-0.7.1.jar Ranged Pumps {rangedpumps@0.7.1 DONE}
		Bookshelf-1.15.2-5.3.9.jar Bookshelf {bookshelf@5.3.9 DONE}
		u_team_core-1.15.2-2.11.0.156.jar U Team Core {uteamcore@2.11.0.156 DONE}
		Apotheosis-1.15.2-3.0.7.jar Apotheosis {apotheosis@3.0.7 DONE}
		MekanismGenerators-1.15.2-9.9.19.411.jar Mekanism: Generators {mekanismgenerators@9.9.19 DONE}
		WaterStrainer-1.15.1-8.0.0.jar Water Strainer {waterstrainer@1.15.1-8.0.0 DONE}
		speedyhoppers-1.15.2-2.jar Speedy Hoppers {speedyhoppers@1.15.2-2 DONE}
		VTweaks-1.15.2-3.1.6.jar V-Tweaks {vtweaks@3.1.5 DONE}
		FpsReducer-mc1.15.2-1.14.1.jar FPS Reducer {fpsreducer@mc1.15.2-1.14.1 DONE}
		ExpOreMod-1.15.2-1.1.jar Exp Ore Block {exp_ore@1.1 DONE}
		respawnablepets-1.1.jar Respawnable Pets {respawnablepets@1.1 DONE}
		NoIncreasingRepairCost-1.15.2-1.0.0.jar No Increasing Repair Cost {noincreasingrepaircost@NONE DONE}
		MoreMekanismOres-1.15.2-1.0.4.1.jar More Mekanism Ores {mmko@1.15.2-1.0.2 DONE}
		refinedstorage-1.8.1.jar Refined Storage {refinedstorage@1.8.1 DONE}
		extendedfurnace-2.2.jar Extended Furnace {extendedfurnace@2.2 DONE}
		useful_backpacks-1.15.2-1.9.4.63.jar Useful Backpacks {usefulbackpacks@1.9.4.63 DONE}
		BiomesOPlenty-1.15.2-10.0.0.345-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.342 DONE}
		MekanismAdditions-1.15.2-9.9.19.411.jar Mekanism: Additions {mekanismadditions@9.9.19 DONE}
		wtbw_lib-1.15.2-1.0.17.jar WTBW Library {wtbw_lib@1.0.17 DONE}
		simplylight-1.15.2-0.9.0.jar Simply Light {simplylight@1.15.2-0.9.0 DONE}
		SolarFluxReborn-1.15.2-15.0.0.jar Solar Flux Reborn {solarflux@15.0.0 DONE}
		curios-FORGE-1.15.2-2.0.2.1.jar Curios API {curios@FORGE-1.15.2-2.0.2.1 DONE}
		Patchouli-1.15.2-1.2-28.jar Patchouli {patchouli@1.15.2-1.2-28 DONE}
		minecraft2discord-1.15.2-1.1.5.jar Minecraft2Discord {minecraft2discord@1.15.2-1.1.5 DONE}
		tombstone-4.3.4-1.15.2.jar Corail Tombstone {tombstone@4.3.4 DONE}
		obfuscate-0.4.1-1.15.2.jar Obfuscate {obfuscate@0.4.1 DONE}
		vehicle-mod-0.43.5-1.15.2.jar MrCrayfish's Vehicle Mod {vehicle@0.43.5 DONE}
		expandedstorage-1.1.8+1.15.2.jar Expanded Storage {expandedstorage@1.1.8+1.15.2 DONE}
		PowderPower-1.15.2-3.1.56.jar Powder Power {powder_power@3.1.56 DONE}
		MekanismTools-1.15.2-9.9.19.411.jar Mekanism: Tools {mekanismtools@9.9.19 DONE}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		incubation-1.0.2-1.15.2.jar Incubation {incubation@1.0.2 DONE}
		ServerTabInfo-1.15.2-1.2.6.jar Server Tab Info {servertabinfo@1.2.6 DONE}
		QuarkOddities-1.15.2.jar Quark Oddities {quarkoddities@1.15.2 DONE}
		AdFinders-1.15.2-4.0.5.0-build.0020.jar Advanced Finders {adfinders@4.0.5.0 DONE}
		Ma-Enchants-1.15.2-3.0.0.jar Ma Enchants {ma-enchants@1.15.2-3.0.0 DONE}
		berry_good-2.0.0.jar Berry Good {berry_good@2.0 DONE}
		Z'Enchants-1.0.jar Z'Enchants {zenchants@1.0 DONE}
		Overloaded-1.15.2-0.0.86.jar Overloaded {overloaded@1.15.2-0.0.84 DONE}
		bambooblocks-1.15.2-1.3.jar Bamboo Blocks {bambooblocks@1.2.11 DONE}
		jei-1.15.2-6.0.0.3.jar Just Enough Items {jei@6.0.0.3 DONE}
		JustEnoughCalculation-1.15.2-3.6.1.jar Just Enough Calculation {jecalculation@3.6.1 DONE}
		buzzierbees-1.4.jar Buzzier Bees {buzzierbees@1.4 DONE}
		AttributeFix-1.15.2-7.0.2.jar AttributeFix {attributefix@7.0.2 DONE}
		goblintraders-1.2.0-1.15.2.jar Goblin Traders {goblintraders@1.2.0 DONE}
		Mekanism-1.15.2-9.9.19.411.jar Mekanism {mekanism@9.9.19 DONE}
		Upgrade-Aquatic-1.15.2-v1.5.1.jar Upgrade Aquatic {upgrade_aquatic@1.5.1 DONE}
		bloomful-1.15.2-1.3.2.jar Bloomful {bloomful@NONE DONE}
		extraboats-1.3.2-1.15.2.jar Extra Boats {extraboats@1.3.2 DONE}
		Clumps-5.0.2.jar Clumps {clumps@5.0.2 DONE}
		OresAboveDiamonds+1.15+v3.3.jar Ores Above Diamonds {oresabovediamonds@3.2 DONE}
		BotanyPots-1.15.2-2.0.6.jar BotanyPots {botanypots@2.0.6 DONE}
		DungeonCrawl-1.15.2-1.6.3.jar Dungeon Crawl {dungeoncrawl@1.6.3 DONE}
		branders-wellfedmod-1.15.2-1.2.0.jar Well Fed - quality food! {wellfedmod@1.2.0 DONE}
		The-Endergetic-Expansion-1.15.2-v1.2.5.jar The Endergetic Expansion {endergetic@1.2.1 DONE}
		ChrispyMod-1.15.2-0.8.0.jar The Chrispy Mod {chrispymod@0.8.0 DONE}
		HarderBranchMining-1.15.2-2.0.0.8.jar Harder Branch Mining Mod {hbm@2.0.0.8 DONE}
		CraftTweaker-1.15.2-6.0.0.13.jar CraftTweaker {crafttweaker@6.0.0.13 DONE}
		extradisks-1.15.1-1.2.jar Extra Disks {extradisks@1.15.1-1.2 DONE}
		swampexpansion-1.15.2-1.5.1.jar Swamp Expansion {swampexpansion@NONE DONE}
		strongfarmland-1.15.2-1.0.0.jar Stronger Farmland Mod {strongfarmland@1.15.2-1.0.0 DONE}
		forge-1.15.2-31.1.43-universal.jar Forge {forge@31.1.43 DONE}
		wtbw_core-1.15.2-1.0.16.jar WTBW Core {wtbw_core@1.0.16 DONE}
		wtbw_tools-1.15.2-1.0.19.jar WTBW Tools {wtbw_tools@1.0.19 DONE}
		tl_skin_cape_1.15.2-1.8.jar TLSkinCape {tlskincape@1.6 DONE}
		sounddeviceoptions-1.3.0.jar Sound Device Options {sounddeviceoptions@1.3.0 DONE}
		CraftingTweaks_1.15.1-11.0.0.jar Crafting Tweaks {craftingtweaks@11.0.0 DONE}
		forge-1.15.2-31.1.43-client.jar Minecraft {minecraft@1.15.2 DONE}
		EnchantmentDescriptions-1.15.2-2.0.5.jar EnchantmentDescriptions {enchdesc@2.0.5 DONE}
		theoneprobe-1.15-2.0.2.jar The One Probe {theoneprobe@1.15-2.0.2 DONE}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		compactores-1.15.2-2.1.1.jar Compact Ores {compactores@2.1.1 DONE}
		wtbw_machines-1.15.2-1.0.19.jar WTBW Machines {wtbw_machines@1.0.19 DONE}
		C.O.M.B.A.T-1.15.2-4.5.0.jar C.O.M.B.A.T {combat@4.5.0 DONE}
		OverpowderedPickles-1.15.2-1.0.0.jar OverpoweredPickles {overpowered_pickles@1.0.0 DONE}
		AdLods-1.15.2-3.0.1.0-build.0008.jar Large Ore Deposits {adlods@3.0.1.0 DONE}
		atmospheric-1.15.2-1.2.1.jar Atmospheric {atmospheric@1.2.1 DONE}
		flux-4.13.1.jar Flux {flux@4.13.1 DONE}
		fl-3.2.0.jar Flux Library {fl@3.2.0 DONE}
		wtbw_decoration-1.15.2-1.0.14.jar WTBW Decoration {wtbw_decoration@1.0.14 DONE}
		FastWorkbench-1.15.1-3.0.0.jar FastWorkbench {fastbench@3.0.0 DONE}
		autumnity-1.1.1-1.15.2.jar Autumnity {autumnity@1.1.1 DONE}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 DONE}
		Quark-r2.1-230.jar Quark {quark@r2.1-230 DONE}
		Charm-1.15.2-1.5.5.jar Charm {charm@1.15.2-1.5.5 DONE}
		Strange-1.15.2-1.0.0-beta.2.jar Strange {strange@1.15.2-1.0.0-beta.2 DONE}
		[1.15.2]+SecurityCraft+v1.8.17.jar SecurityCraft {securitycraft@v1.8.17 DONE}
		performant-1.15-2.04m.jar Performant {performant@2.04m DONE}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		engineersdecor-1.15.2-1.0.20-b4.jar Engineer's Decor {engineersdecor@1.0.20-b4 DONE}
		DurabilityViewer-1.15.2-forge31.1.30-1.7.jar Giselbaers Durability Viewer {durabilityviewer@NONE DONE}
		XL-Food-Mod-1.15.2-2.2.2.jar XL Food Mod {xlfoodmod@2.2.2 DONE}
		forgemod_VoxelMap-1.9.16_for_1.15.2.jar VoxelMap {voxelmap@1.9.16 DONE}
		refinedstorageaddons-0.6.1.jar Refined Storage Addons {refinedstorageaddons@0.6.1 DONE}
		CraftingCraft_1.15.1-8.0.0.jar CraftingCraft {craftingcraft@8.0.0 DONE}
		Ma-Essentials-1.15.2-3.0.2.jar Ma Essentials {ma-essentials@1.15.2-3.0.2 DONE}
		SolarGeneration-1.15.2-1.2.0.jar Solar Generation {solargeneration@1.2.0 DONE}
		LegendOfHerobrine-1.15.2-0.3.2.jar The Legend of Herobrine {herobrine@0.3.2 DONE}
		supertools-1.15.2-1.0.jar Vanilla+ Tools {supertools@version DONE}
	Launched Version: 1.15.2-forge-31.1.43
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1650/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.75, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Español (España)
	CPU: 4x Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
1. Use gist/pastebin for logs
2. Update. You claim to be using 9.9.20, but your crash log says you are using 9.9.19
