### ISSUE TITLE
Digital miner causes render crash when placed

### ISSUE THREAD

**Issue by wanderingmage** [mekanism/Mekanism#6077]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Digital miner causes render crash when placed.

#### Steps to reproduce:
1. place digital miner

#### Version (make sure you are on the latest version before reporting):
**Forge: 31.1.43** 
**Mekanism: 9.9.19.411** 
**Other relevant version:** 

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 4/18/20 12:55 AM
Description: Unexpected error

java.lang.IllegalAccessError: tried to access class net.minecraft.client.renderer.model.ModelRenderer$TexturedQuad from class mekanism.client.model.ExtendedModelRenderer
	at mekanism.client.model.ExtendedModelRenderer.renderWireFrame(ExtendedModelRenderer.java:38) ~[?:?] {re:classloading}
	at mekanism.client.model.ExtendedModelRenderer.render(ExtendedModelRenderer.java:22) ~[?:?] {re:classloading}
	at mekanism.client.model.ModelDigitalMiner.render(ModelDigitalMiner.java:453) ~[?:?] {re:classloading}
	at mekanism.client.model.ModelDigitalMiner.renderWireFrame(ModelDigitalMiner.java:449) ~[?:?] {re:classloading}
	at mekanism.client.render.tileentity.RenderDigitalMiner.renderWireFrame(RenderDigitalMiner.java:52) ~[?:?] {re:classloading}
	at mekanism.client.render.RenderTickHandler.configurableMachine(RenderTickHandler.java:248) ~[?:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_98_RenderTickHandler_configurableMachine_HighlightBlock.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:168) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1038) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:600) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:422) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:925) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) ~[1.15.2-forge-31.1.43.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.15.2-31.1.43.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at mekanism.client.model.ExtendedModelRenderer.renderWireFrame(ExtendedModelRenderer.java:38)
	at mekanism.client.model.ExtendedModelRenderer.render(ExtendedModelRenderer.java:22)
	at mekanism.client.model.ModelDigitalMiner.render(ModelDigitalMiner.java:453)
	at mekanism.client.model.ModelDigitalMiner.renderWireFrame(ModelDigitalMiner.java:449)
	at mekanism.client.render.tileentity.RenderDigitalMiner.renderWireFrame(RenderDigitalMiner.java:52)
	at mekanism.client.render.RenderTickHandler.configurableMachine(RenderTickHandler.java:248)
	at net.minecraftforge.eventbus.ASMEventHandler_98_RenderTickHandler_configurableMachine_HighlightBlock.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:168)
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1038)
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:600)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['wanderingmage'/197, l='MpServer', x=-4.51, y=72.00, z=-115.32]]
	Chunk stats: Client Chunk Cache: 841, 550
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 4560400300666170614
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (32,64,-128), Chunk: (at 0,4,0 in 2,-8; contains blocks 32,0,-128 to 47,255,-113), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 2278328 game time, 3316274 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:442)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1764)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:573)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4536482496 bytes (4326 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.43.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.43.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.4-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.43.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.43.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.43.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.43
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		forge-1.15.2-31.1.43-client.jar Minecraft {minecraft@1.15.2 DONE}
		Cucumber-1.15.2-3.0.4.jar Cucumber Library {cucumber@3.0.4 DONE}
		worldedit-forge-mc1.15.2-7.1.0.jar WorldEdit {worldedit@7.1.0;48cc31c DONE}
		MekanismTools-1.15.2-9.9.19.411.jar Mekanism: Tools {mekanismtools@9.9.19 DONE}
		MekanismAdditions-1.15.2-9.9.19.411.jar Mekanism: Additions {mekanismadditions@9.9.19 DONE}
		MekanismGenerators-1.15.2-9.9.19.411.jar Mekanism: Generators {mekanismgenerators@9.9.19 DONE}
		Hwyla-forge-1.10.7-B71_1.15.1.jar Waila {waila@version DONE}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 DONE}
		metalbarrels-2.1.jar Metal Barrels {metalbarrels@2.1 DONE}
		Mekanism-1.15.2-9.9.19.411.jar Mekanism {mekanism@9.9.19 DONE}
		forge-1.15.2-31.1.43-universal.jar Forge {forge@31.1.43 DONE}
		FastLeafDecay-v22.jar FastLeafDecay {fastleafdecay@v22 DONE}
		corail_woodcutter-1.1.1-1.15.2.jar Corail Woodcutter {corail_woodcutter@1.1.1 DONE}
		Xaeros_Minimap_20.5.0_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.5.0 DONE}
		XaerosWorldMap_1.5.5_Forge_1.15.2.jar Xaero's World Map {xaeroworldmap@1.5.5 DONE}
		MysticalAgriculture-1.15.2-3.0.1.jar Mystical Agriculture {mysticalagriculture@3.0.1 DONE}
		ironchest-1.15.2-10.0.2.jar Iron Chests {ironchest@1.15.2-10.0.1 DONE}
	Launched Version: 1.15.2-forge-31.1.43
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 960/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.87, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, mod_resources, file/John Smith Legacy JSC 1.15.2 v4.zip
	Current Language: English (US)
	CPU: 8x AMD FX(tm)-8350 Eight-Core Processor

**Comment by thiakil** [comment]
Update Mekanism
