### ISSUE TITLE
Error while loading, mekanism:basic_fluid_tank, color/Bucket Mode

### ISSUE THREAD

**Issue by SkyeMors** [mekanism/Mekanism#6133]
Game started not being able to load (to the game itself, it loads the Minecraft portion after the Forge preloader finishes), I SUSPECT (but have no way of proving) that it has to do with if a Fluid Tank being held is in Bucket Mode or not, and if that color variant is registered. Or something, I have yet to look at mod contents.
Wouldn't think it would be a mod conflict as no new mods were introduced nor updated between it working flawlessly and it refusing to load the game (not world, can't even get to that point), and the only thing I can think of that would be related time-wise, is discovering that the tanks had Bucket Mode, and using that often.

Another possibility is the Resource pack I have, VanillaTweaks, which I will end up posting over there if it ends up not being an issue with Mekanism.

Log:
https://pastebin.com/BC6hC69v

**Comment by pupnewfster** [comment]
This has nothing to do with mekanism https://github.com/MinecraftForge/MinecraftForge/issues/6374

please provide your latest log as that contains the actual crash.

**Comment by SkyeMors** [comment]
Sorry, that was the crash report and not the Log, wasn't it. Been a while. Log said Mekanism, I was messing with Mekanism, I had no reason to believe that Forge would out of the blue for no reason start having issues and point me towards... Mekanism.
[2020-05-04-12.log.gz](https://github.com/mekanism/Mekanism/files/4578511/2020-05-04-12.log.gz)

**Comment by pupnewfster** [comment]
That is not your latest log, it should be called `latest.log` (or just `latest` if you have file extensions hidden). The log you shared was for a time it successfully loaded.

**Comment by SkyeMors** [comment]
[latest.log](https://github.com/mekanism/Mekanism/files/4578606/latest.log)

**Comment by pupnewfster** [comment]
Looks like this is the cause:
```
[net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to register automatic subscribers. ModID: adfinders, class com.endertech.minecraft.mods.adfinders.AdFinders
java.lang.ExceptionInInitializerError: null
	at com.endertech.minecraft.mods.adfinders.finder.Renderer.<clinit>(Renderer.java:34) ~[?:1.15.2-4.0.5.0-build.0020]
	at com.endertech.minecraft.mods.adfinders.items.Finder$$Lambda$2656/694237930.call(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.DistExecutor.callWhenOn(DistExecutor.java:44) ~[?:?]
	at net.minecraft.item.Item.<init>(Item.java:103) ~[?:?]
	at com.endertech.minecraft.forge.items.ForgeItem.<init>(ForgeItem.java:39) ~[?:1.15.2-6.0.2.1-build.0024]
	at com.endertech.minecraft.forge.items.DamageableItem.<init>(DamageableItem.java:25) ~[?:1.15.2-6.0.2.1-build.0024]
	at com.endertech.minecraft.forge.items.EquipmentItem.<init>(EquipmentItem.java:32) ~[?:1.15.2-6.0.2.1-build.0024]
	at com.endertech.minecraft.forge.items.GlassMeter.<init>(GlassMeter.java:34) ~[?:1.15.2-6.0.2.1-build.0024]
	at com.endertech.minecraft.mods.adfinders.items.Finder.<init>(Finder.java:72) ~[?:1.15.2-4.0.5.0-build.0020]
	at com.endertech.minecraft.mods.adfinders.init.FinderType.<init>(FinderType.java:30) ~[?:1.15.2-4.0.5.0-build.0020]
	at com.endertech.minecraft.mods.adfinders.init.FinderType.<clinit>(FinderType.java:21) ~[?:1.15.2-4.0.5.0-build.0020]
```
