### ISSUE TITLE
Mekanism Crash

### ISSUE THREAD

**Issue by xvSasuke** [mekanism/Mekanism#6283]
ava.lang.NoSuchMethodError: mekanism.common.item.ItemJetpack.setTileEntityItemStackRenderer(Lnet/minecraft/client/renderer/tileentity/TileEntityItemStackRenderer;)V
	at mekanism.client.ClientProxy.registerItemRenders(ClientProxy.java:386)
	at mekanism.common.Mekanism.registerModels(Mekanism.java:306)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_197_Mekanism_registerModels_ModelRegistryEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.client.FMLClientHandler.fireSidedRegistryEvents(FMLClientHandler.java:1095)
	at net.minecraftforge.fml.common.FMLCommonHandler.fireSidedRegistryEvents(FMLCommonHandler.java:757)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

or 

Error: java.lang.NoSuchMethodError: mekanism.common.item.ItemJetpack.setTileEntityItemStackRenderer(Lnet/minecraft/client/renderer/tileentity/TileEntityItemStackRenderer;)V

**Comment by pupnewfster** [comment]
1.12 is not supported anymore and you gave so little information that I can't even suggest what the problem might be.

**Comment by xvSasuke** [comment]
i dont have more information that it.
