### ISSUE TITLE
Registry Object not present: mekanism:qio_drive_array

### ISSUE THREAD

**Issue by PItlosTails** [mekanism/Mekanism#6302]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 11.07.20 23:45
Description: Initializing game

java.lang.NullPointerException: Registry Object not present: mekanism:qio_drive_array
	at java.util.Objects.requireNonNull(Objects.java:290) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:120) ~[?:?] {re:classloading}
	at mekanism.common.registration.DoubleWrappedRegistryObject.getPrimary(DoubleWrappedRegistryObject.java:23) ~[?:10.0.0] {re:classloading}
	at mekanism.common.registration.impl.BlockRegistryObject.getBlock(BlockRegistryObject.java:19) ~[?:10.0.0] {re:classloading}
	at mekanism.client.ClientRegistrationUtil.registerBlockColorHandler(ClientRegistrationUtil.java:107) ~[?:10.0.0] {re:classloading}
	at mekanism.client.ClientRegistration.registerItemColorHandlers(ClientRegistration.java:368) ~[?:10.0.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_411_ClientRegistration_registerItemColorHandlers_Item.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168) ~[?:32.0] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:260) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader$$Lambda$5840/670626252.accept(Unknown Source) ~[?:?] {}
	at java.util.HashMap.forEach(HashMap.java:1280) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:218) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:260) ~[?:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.onItemColorsInit(ForgeHooksClient.java:170) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.color.ItemColors.func_186729_a(ItemColors.java:86) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:449) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.1-32.0.62.jar:32.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$429/827039307.call(Unknown Source) [forge-1.16.1-32.0.62.jar:32.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:290)
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:120)
	at mekanism.common.registration.DoubleWrappedRegistryObject.getPrimary(DoubleWrappedRegistryObject.java:23)
	at mekanism.common.registration.impl.BlockRegistryObject.getBlock(BlockRegistryObject.java:19)
	at mekanism.client.ClientRegistrationUtil.registerBlockColorHandler(ClientRegistrationUtil.java:107)
	at mekanism.client.ClientRegistration.registerItemColorHandlers(ClientRegistration.java:368)
	at net.minecraftforge.eventbus.ASMEventHandler_411_ClientRegistration_registerItemColorHandlers_Item.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168)
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:260)
	at net.minecraftforge.fml.ModLoader$$Lambda$5840/670626252.accept(Unknown Source)
	at java.util.HashMap.forEach(HashMap.java:1280)
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:218)
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:260)
	at net.minecraftforge.client.ForgeHooksClient.onItemColorsInit(ForgeHooksClient.java:170)
	at net.minecraft.client.renderer.color.ItemColors.func_186729_a(ItemColors.java:86)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:449)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$429/827039307.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3120938800 bytes (2976 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg

any way to fix this?

**Comment by pupnewfster** [comment]
If you are on Forge `32.0.62` start by updating to `32.0.63`, and if that still doesn't fix it please provide your latest log as the crash report does not contain any useful information due to https://github.com/MinecraftForge/MinecraftForge/issues/6374

**Comment by PItlosTails** [comment]
alright i heard (and experienced that 32.0.63 is even more unstable but its up to you. Still crashes and heres the log

---- Minecraft Crash Report ----
// My bad.

Time: 11.07.20 23:51
Description: Initializing game

java.lang.NullPointerException: Registry Object not present: mekanism:qio_drive_array
	at java.util.Objects.requireNonNull(Objects.java:290) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:120) ~[?:?] {re:classloading}
	at mekanism.common.registration.DoubleWrappedRegistryObject.getPrimary(DoubleWrappedRegistryObject.java:23) ~[?:10.0.0] {re:classloading}
	at mekanism.common.registration.impl.BlockRegistryObject.getBlock(BlockRegistryObject.java:19) ~[?:10.0.0] {re:classloading}
	at mekanism.client.ClientRegistrationUtil.registerBlockColorHandler(ClientRegistrationUtil.java:107) ~[?:10.0.0] {re:classloading}
	at mekanism.client.ClientRegistration.registerItemColorHandlers(ClientRegistration.java:368) ~[?:10.0.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_411_ClientRegistration_registerItemColorHandlers_Item.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168) ~[?:32.0] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:260) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader$$Lambda$5839/1054753422.accept(Unknown Source) ~[?:?] {}
	at java.util.HashMap.forEach(HashMap.java:1280) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:218) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:260) ~[?:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.onItemColorsInit(ForgeHooksClient.java:170) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.color.ItemColors.func_186729_a(ItemColors.java:86) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:449) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.1-32.0.63.jar:32.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$429/827039307.call(Unknown Source) [forge-1.16.1-32.0.63.jar:32.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:290)
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:120)
	at mekanism.common.registration.DoubleWrappedRegistryObject.getPrimary(DoubleWrappedRegistryObject.java:23)
	at mekanism.common.registration.impl.BlockRegistryObject.getBlock(BlockRegistryObject.java:19)
	at mekanism.client.ClientRegistrationUtil.registerBlockColorHandler(ClientRegistrationUtil.java:107)
	at mekanism.client.ClientRegistration.registerItemColorHandlers(ClientRegistration.java:368)
	at net.minecraftforge.eventbus.ASMEventHandler_411_ClientRegistration_registerItemColorHandlers_Item.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168)
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:260)
	at net.minecraftforge.fml.ModLoader$$Lambda$5839/1054753422.accept(Unknown Source)
	at java.util.HashMap.forEach(HashMap.java:1280)
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:218)
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:260)
	at net.minecraftforge.client.ForgeHooksClient.onItemColorsInit(ForgeHooksClient.java:170)
	at net.minecraft.client.renderer.color.ItemColors.func_186729_a(ItemColors.java:86)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:449)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$429/827039307.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4704241848 bytes (4486 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.1-32.0.63.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.63.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.1-32.0.63.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.63.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.16.1-32.0.63.jar fml TRANSFORMATIONSERVICE 
	FML: 32.0
	Forge: net.minecraftforge:32.0.63
	FML Language Providers: 
		javafml@32.0
		minecraft@1
	Mod List: 
		randomloot-2.0.4.jar Random Loot Mod {randomloot@2.0.4 CREATE_REGISTRIES}
		Ma-Enchants-1.16.1-3.2.1.jar Ma Enchants {ma-enchants@1.16.1-3.2.1 CREATE_REGISTRIES}
		NetherPortalFix_1.16.1-7.0.0.jar NetherPortalFix {netherportalfix@7.0.0 CREATE_REGISTRIES}
		mining-helmet-1.16.1-1.0.8.jar Mining Helmet {mining_helmet@1.0.8 CREATE_REGISTRIES}
		jei-1.16.1-7.0.0.6.jar Just Enough Items {jei@7.0.0.6 CREATE_REGISTRIES}
		metalbarrels-3.1a.jar Metal Barrels {metalbarrels@3.1a CREATE_REGISTRIES}
		tnt-yeeter-1.16.1-1.2.0.jar TNT Yeeter {yeeter@1.2.0 CREATE_REGISTRIES}
		FallingTree-1.16.1-2.1.5.jar Falling Tree {falling_tree@2.1.5 CREATE_REGISTRIES}
		Abnormals-Core-1.16.1-v2.0.0.jar Abnormals Core {abnormals_core@2.0.0 CREATE_REGISTRIES}
		no-nitwits-1.16.1-1.0.0.jar No Nitwits {no_nitwits@1.0.0 CREATE_REGISTRIES}
		Mekanism-1.16.1-10.0.0.423.jar Mekanism {mekanism@10.0.0 CREATE_REGISTRIES}
		caelus-FORGE-1.16.1-2.0-beta4.jar Caelus API {caelus@FORGE-1.16.1-2.0-beta4 CREATE_REGISTRIES}
		KleeSlabs_1.16.1-9.0.0.jar KleeSlabs {kleeslabs@9.0.0 CREATE_REGISTRIES}
		colytra-FORGE-1.16.1-4.0.jar Colytra {colytra@FORGE-1.16.1-4.0 CREATE_REGISTRIES}
		rsgauges-1.16.1-1.2.4-b1.jar Gauges and Switches {rsgauges@1.2.4-b1 CREATE_REGISTRIES}
		pitg-1.16.1-1.3.0.jar Pane In The Glass {pitg@1.16.1-1.3.0 CREATE_REGISTRIES}
		JarJarBinks-1.16.1-1.0.0.jar Jar Jar Binks {azurejarjar@1.0.0 CREATE_REGISTRIES}
		essentials-1.16.1-2.8.0.jar Essentials {essentials@1.16.1-2.8.0 CREATE_REGISTRIES}
		BetterCaves-1.16.1-1.0.jar YUNG's Better Caves {bettercaves@1.16.1-1.0 CREATE_REGISTRIES}
		Waystones_1.16.1-7.0.1.jar Waystones {waystones@7.0.1 CREATE_REGISTRIES}
		villagernames_1.16-2.4.jar Villager Names {villagernames@2.4 CREATE_REGISTRIES}
		comforts-FORGE-1.16.1-3.0.jar Comforts {comforts@FORGE-1.16.1-3.0 CREATE_REGISTRIES}
		citadel-1.2.0.jar Citadel {citadel@1.2.0 CREATE_REGISTRIES}
		[1.16.1]-additionalbars-1.4.1.jar Additional Bars {additionalbars@1.4.1 CREATE_REGISTRIES}
		beaconsforall-FORGE-1.16.1-4.0.jar Beacons For All {beaconsforall@FORGE-1.16.1-4.0 CREATE_REGISTRIES}
		potionofbees-1.16.1-1.0.1.0.jar Potion of Bees {potionofbees@1.16.1-1.0.1.0 CREATE_REGISTRIES}
		culinaryconstruct-FORGE-1.16.1-3.0.jar Culinary Construct {culinaryconstruct@FORGE-1.16.1-3.0 CREATE_REGISTRIES}
		FarmingForBlockheads_1.16.1-7.0.0.jar Farming for Blockheads {farmingforblockheads@7.0.0 CREATE_REGISTRIES}
		Bookshelf-1.16.1-6.0.2.jar Bookshelf {bookshelf@6.0.2 CREATE_REGISTRIES}
		BotanyPots-1.16.1-3.0.2.jar BotanyPots {botanypots@3.0.2 CREATE_REGISTRIES}
		snowundertrees-1.16.1-v1.1.1.jar Snow Under Trees {snowundertrees@v1.1.1 CREATE_REGISTRIES}
		guardvillagers-1.16.1-1.1.0.jar Guard Villagers {guardvillagers@1.0.7 CREATE_REGISTRIES}
		u_team_core-1.16.1-3.1.0.161-SNAPSHOT.jar U Team Core {uteamcore@3.1.0.161-SNAPSHOT CREATE_REGISTRIES}
		randompatches-1.16.1-1.21.2.1.jar RandomPatches {randompatches@1.16.1-1.21.2.1 CREATE_REGISTRIES}
		ForgivingVoid_1.16.1-5.0.0.jar Forgiving Void {forgivingvoid@5.0.0 CREATE_REGISTRIES}
		mcw-doors-1.0.0-mc1.16.1.jar Macaw's Doors {mcwdoors@1.0.0 CREATE_REGISTRIES}
		bedspreads-FORGE-1.16.1-4.0.jar Bedspreads {bedspreads@FORGE-1.16.1-4.0 CREATE_REGISTRIES}
		MekanismGenerators-1.16.1-10.0.0.423.jar Mekanism: Generators {mekanismgenerators@10.0.0 CREATE_REGISTRIES}
		forge-1.16.1-32.0.63-universal.jar Forge {forge@32.0.63 CREATE_REGISTRIES}
		Waddles-1.16.1-0.8.7.jar Waddles {waddles@1.16.1-0.8.7 CREATE_REGISTRIES}
		SimpleOres2-1.16.1-2.2.0.0.jar Simple Ores {simpleores@1.16.1-2.2.0.0 CREATE_REGISTRIES}
		structure-gel-api-1.16.1-1.1.1.jar Structure Gel API {structure_gel@1.1.1 CREATE_REGISTRIES}
		ironchest-1.16.1-11.0.1.jar Iron Chests {ironchest@1.16.1-11.0.1 CREATE_REGISTRIES}
		corpse-1.16.1-1.0.4.jar Corpse {corpse@1.16.1-1.0.4 CREATE_REGISTRIES}
		forge-1.16.1-32.0.63-client.jar Minecraft {minecraft@1.16.1 CREATE_REGISTRIES}
		mcw-bridges-1.0.4-mc1.16.1.jar Macaw's Bridges {mcwbridges@1.0.4 CREATE_REGISTRIES}
		lightestlamp-4.0.2.jar Lightest Lamps {lightestlamp@4.0.2 CREATE_REGISTRIES}
		useful_backpacks-1.16.1-1.11.0.68-SNAPSHOT.jar Useful Backpacks {usefulbackpacks@1.11.0.68-SNAPSHOT CREATE_REGISTRIES}
		improved-stations-2.0.jar Improved Stations {improved-stations@2.0 CREATE_REGISTRIES}
		morezombiev_1.16-1.1.jar More Zombie Villagers {morezombiev@1.1 CREATE_REGISTRIES}
		MouseTweaks-2.13-mc1.16.1.jar Mouse Tweaks {mousetweaks@2.13 CREATE_REGISTRIES}
		ToolBelt-1.16.1-1.14.1.jar Tool Belt {toolbelt@1.14.1 CREATE_REGISTRIES}
		netherportalspread_1.16-3.5.jar Nether Portal Spread {netherportalspread@3.5 CREATE_REGISTRIES}
		BiomesOPlenty-1.16.1-11.0.0.371-universal.jar Biomes O' Plenty {biomesoplenty@1.16.1-11.0.0.371 CREATE_REGISTRIES}
		MekanismAdditions-1.16.1-10.0.0.423.jar Mekanism: Additions {mekanismadditions@10.0.0 CREATE_REGISTRIES}
		valhelsia_structures-16.0.1.jar Valhelsia Structures {valhelsia_structures@16.0.1 CREATE_REGISTRIES}
		ironfurnaces-1.16.1-2.1.1.jar Iron Furnaces {ironfurnaces@2.1.1 CREATE_REGISTRIES}
		LetSleepingDogsLie-1.16.1-1.1.1.jar Let Sleeping Dogs Lie {dogslie@1.1.1 CREATE_REGISTRIES}
		forbidden_arcanus-1.16.1-1.0-beta-2.jar Forbidden & Arcanus {forbidden_arcanus@1.16.1-1.0-beta CREATE_REGISTRIES}
		masonry-1.16.1-0.3.5.jar Masonry {masonry@NONE CREATE_REGISTRIES}
		ceilingtorch-1.16.1-v1.5.jar Ceiling Torch {ceilingtorch@v1.5 CREATE_REGISTRIES}
		EyesInTheDarkness-1.16.1-0.4.0.jar Eyes in the Darkness {eyesinthedarkness@0.4.0 CREATE_REGISTRIES}
		corpsecomplex-FORGE-1.16.1-3.0.jar Corpse Complex {corpsecomplex@FORGE-FORGE-1.16.1-3.0 CREATE_REGISTRIES}
		car-1.16.1-1.0.3.jar Ultimate Car Mod {car@1.16.1-1.0.3 CREATE_REGISTRIES}
		AzureDooms-Doom-Mod-1.16.1-1.1.2.jar Azuredooms Doom Mod {doomweapon@1.1.2 CREATE_REGISTRIES}
		curios-FORGE-1.16.1-3.0-beta2.jar Curios API {curios@FORGE-1.16.1-3.0-beta2 CREATE_REGISTRIES}
		Savage-and-Ravage-1.16.1-2.0.0.jar Savage & Ravage {savageandravage@2.0.0 CREATE_REGISTRIES}
		Xaeros_Minimap_20.15.3_Forge_1.16.1.jar Xaero's Minimap {xaerominimap@20.15.3 CREATE_REGISTRIES}
		rats-6.0.3-1.16.1.jar Rats {rats@6.0.3 CREATE_REGISTRIES}
		pamhc2foodcore-1.16.1-1.0.1.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version CREATE_REGISTRIES}
		collective-1.16.1-1.35.jar Collective {collective@1.35 CREATE_REGISTRIES}
		lava-monster-1.16.1-1.0.7.jar Lava Monster {lava_monster@1.0.7 CREATE_REGISTRIES}
		StorageDrawers-1.16.1-8.0.0.jar Storage Drawers {storagedrawers@1.16.1-8.0.0 CREATE_REGISTRIES}
		combustivefishing-FORGE-1.16.1-3.0.jar Combustive Fishing {combustivefishing@FORGE-1.16.1-3.0 CREATE_REGISTRIES}
		MekanismTools-1.16.1-10.0.0.423.jar Mekanism: Tools {mekanismtools@10.0.0 CREATE_REGISTRIES}
		hunterillager-1.16.1-0.8.0.jar HunterIllager {hunterillager@0.8.0 CREATE_REGISTRIES}
		AppleSkin-mc1.16.1-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 CREATE_REGISTRIES}
		engineersdecor-1.16.1-1.1.1-a1.jar Engineer's Decor {engineersdecor@1.1.1-a1 CREATE_REGISTRIES}
		cherishedworlds-FORGE-1.16.1-4.0.jar Cherished Worlds {cherishedworlds@FORGE-1.16.1-4.0 CREATE_REGISTRIES}
		earthsanimals-1.16.1-0.0.6-beta.jar Earths Animals {earthsanimals@1.16.1-0.0.6-beta CREATE_REGISTRIES}
		moredragoneggs-1.1.jar More Dragon Eggs {moredragoneggs@1.1 CREATE_REGISTRIES}
		betterbedrockgenerator-1.16.1-0.0.7.jar Better Bedrock Generator {betterbedrockgenerator@0.0.7 ERROR}
		craftablehorsearmour-1.3.jar Craftable Horse Armour {craftablehorsearmour@1.3 CREATE_REGISTRIES}
		PrettyBeaches_1.16.1-5.0.0.jar Pretty Beaches {prettybeaches@5.0.0 CREATE_REGISTRIES}
		QuantumStorage-1.16.1-5.2.0.jar QuantumStorage {quantumstorage@NONE CREATE_REGISTRIES}
		rockcandy-1.16-1.0.1.jar Rock Candy {rockcandy@version CREATE_REGISTRIES}
		farlanders-1.16.1-1.3.2.jar The Farlanders {farlanders@1.3.2 CREATE_REGISTRIES}
		bigbuckets-1.1.1.jar BigBuckets {bigbuckets@1.1.1 CREATE_REGISTRIES}
	Launched Version: 1.16.1-forge-32.0.63
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce RTX 2080/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.75, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 16x AMD Ryzen 7 3800X 8-Core Processor

**Comment by pupnewfster** [comment]
First off `32.0.63` is not more unstable than `32.0.62`. In fact it fixes a pretty large bug in forge when it comes to custom registries. Secondly please use a site like pastebin or gist rather than just pasting all the raw text here. Thirdly I asked for your latest log not for your latest crash report, so try again as the crash report is still invalid due to the forge issue I linked above.

**Comment by PItlosTails** [comment]
firstly you told me to update to 32.0.63 which i did, secondly you linked a thing that tells me absolutely nothing so i could not know that ya suddenly wanted my other log 90 of people dont know anything about java but i digress ill use pastebin, https://pastebin.com/33D1kJha

**Comment by pupnewfster** [comment]
> if that still doesn't fix it please provide your latest log as the crash report does not contain any useful information due to

Regardless the crash seems to be caused by lycanites mobs:
```
[15feb2020 17:32:50.721] [modloading-worker-5/ERROR] [net.minecraftforge.fml.common.ObfuscationReflectionHelper/]: Unable to locate any field maximumValue on type net.minecraft.entity.ai.attributes.RangedAttribute
net.minecraftforge.fml.common.ObfuscationReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: maximumValue
    at net.minecraftforge.fml.common.ObfuscationReflectionHelper.findField(ObfuscationReflectionHelper.java:242) ~[?:?]
    at net.minecraftforge.fml.common.ObfuscationReflectionHelper.setPrivateValue(ObfuscationReflectionHelper.java:120) [?:?]
    at com.lycanitesmobs.core.helpers.LMReflectionHelper.setPrivateFinalValue(LMReflectionHelper.java:42) [?:1.0]
    at com.lycanitesmobs.LycanitesMobs.commonSetup(LycanitesMobs.java:177) [?:1.0]
    at com.lycanitesmobs.LycanitesMobs$$Lambda$2541/1192377796.accept(Unknown Source) [?:1.0]
```

**Comment by PItlosTails** [comment]
i dont have lycanite mobs, its not out for 1.16.2 and this is a clean install of minecraft.... what ???? it would seem i sent the wrong log somehow https://pastebin.com/ezN7RRHT here is the one for today, sorry

**Comment by pupnewfster** [comment]
```
[11jul2020 21:35:46.547] [Render thread/FATAL] [net.minecraftforge.fml.ModLoader/CORE]: Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod §efarlanders§r requires §6structure_gel§r §o1.1.0 or above§r
§7Currently, §6structure_gel§r§7 is §o§nnot installed
    at net.minecraftforge.fml.ModLoadingException.lambda$fromEarlyException$0(ModLoadingException.java:63) ~[?:?]
```
It seems the mod farlanders requires structure_gel which you do not have installed.

**Comment by yepidoodles** [comment]
Hello, so I had this crash and through process of elimiation figured out it was Dank Storage (posting in case anyone else has the same issue and comes looking)
