### ISSUE TITLE
Digital Miner crashes save when filter ore* starts

### ISSUE THREAD

**Issue by RodrigoZXMota** [mekanism/Mekanism#6588]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

Digital Miner crashes save after starting with filter for ore*

#### Steps to reproduce:
1. Place digital miner
2. Set filter to ore*
3. Crash game

#### Version (make sure you are on the latest version before reporting):
**Forge: forge-31.2.43
**Mekanism: Mekanism-1.15.2-9.10.3.416.jar
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 10/4/20 6:53 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.minecraftforge.fml.network.PacketDistributor.lambda$playerConsumer$1(PacketDistributor.java:216) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.PacketDistributor$$Lambda$11956/606375749.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.network.PacketDistributor$PacketTarget.send(PacketDistributor.java:178) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.simple.SimpleChannel.send(SimpleChannel.java:124) ~[?:?] {re:classloading}
	at nl.requios.effortlessbuilding.EventHandler.onBlockBroken(EventHandler.java:111) ~[?:1.15.2-2.21] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_116_EventHandler_onBlockBroken_BreakEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at mekanism.common.tile.TileEntityDigitalMiner.canMine(TileEntityDigitalMiner.java:449) ~[?:?] {re:classloading}
	at mekanism.common.tile.TileEntityDigitalMiner.onUpdateServer(TileEntityDigitalMiner.java:246) ~[?:?] {re:classloading}
	at mekanism.common.tile.base.TileEntityMekanism.func_73660_a(TileEntityMekanism.java:470) ~[?:?] {re:classloading}
	at net.minecraft.world.World.func_217391_K(World.java:1410) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.WorldMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:368) ~[?:?] {re:mixin,re:classloading,xf:fml:immersiveengineering:IE block update callback,pl:mixin:APP:assets/fruittrees/fruittrees.mixins.json:MixinServerWorld,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.fml.network.PacketDistributor.lambda$playerConsumer$1(PacketDistributor.java:216)
	at net.minecraftforge.fml.network.PacketDistributor$$Lambda$11956/606375749.accept(Unknown Source)
	at net.minecraftforge.fml.network.PacketDistributor$PacketTarget.send(PacketDistributor.java:178)
	at net.minecraftforge.fml.network.simple.SimpleChannel.send(SimpleChannel.java:124)
	at nl.requios.effortlessbuilding.EventHandler.onBlockBroken(EventHandler.java:111)
	at net.minecraftforge.eventbus.ASMEventHandler_116_EventHandler_onBlockBroken_BreakEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at mekanism.common.tile.TileEntityDigitalMiner.canMine(TileEntityDigitalMiner.java:449)
	at mekanism.common.tile.TileEntityDigitalMiner.onUpdateServer(TileEntityDigitalMiner.java:246)
	at mekanism.common.tile.base.TileEntityMekanism.func_73660_a(TileEntityMekanism.java:470)

-- Block entity being ticked --
Details:
	Name: mekanism:digital_miner // mekanism.common.tile.TileEntityDigitalMiner
	Block: Block{mekanism:digital_miner}[active=true,facing=west,waterlogged=false]
	Block location: World: (-135,72,-2131), Chunk: (at 9,4,13 in -9,-134; contains blocks -144,0,-2144 to -129,255,-2129), Region: (-1,-5; contains chunks -32,-160 to -1,-129, blocks -512,0,-2560 to -1,255,-2049)
	Block: Block{mekanism:digital_miner}[active=true,facing=west,waterlogged=false]
	Block location: World: (-135,72,-2131), Chunk: (at 9,4,13 in -9,-134; contains blocks -144,0,-2144 to -129,255,-2129), Region: (-1,-5; contains chunks -32,-160 to -1,-129, blocks -512,0,-2560 to -1,255,-2049)
Stacktrace:
	at net.minecraft.world.World.func_217391_K(World.java:1410)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:368)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['MotaZX'/141, l='Manga, The final countdown', x=-137.48, y=72.00, z=-2130.29]]
	Chunk stats: ServerChunkCache: 3874
	Level dimension: DimensionType{minecraft:overworld}
	Level name: Manga, The final countdown
	Level seed: 1499036368
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (-48,63,96), Chunk: (at 0,3,0 in -3,6; contains blocks -48,0,96 to -33,255,111), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 602724 game time, 731773 day time
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 91129 (now: false), thunder time: 109578 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 689228408 bytes (657 MB) / 2737307648 bytes (2610 MB) up to 5249695744 bytes (5006 MB)
	CPUs: 8
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5632m -Xms256m -XX:PermSize=256m
	ModLauncher: 5.1.2+70+master.2845bb9
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.43.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.43.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.43.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.43.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.2.43.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.4.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.4.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.4.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.43
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		jei-1.15.2-6.0.3.15.jar Just Enough Items {jei@6.0.3.15 DONE}
		Druidcraft-1.15-0.4.31.jar Druidcraft {druidcraft@0.4.31 DONE}
		Mekanism-1.15.2-9.10.3.416.jar Mekanism {mekanism@9.10.3 DONE}
		create-mc1.15.2_v0.2.4e.jar Create {create@mc1.15.2_v0.2.4e+custom DONE}
		Clumps-5.0.2.6.jar Clumps {clumps@5.0.2.6 DONE}
		journeymap-1.15.2-5.7.0b3.jar Journeymap {journeymap@5.7.0b3 DONE}
		CookingForBlockheads_1.15.2-8.0.3.jar Cooking for Blockheads {cookingforblockheads@8.0.3 DONE}
		Placebo-1.15.2-3.1.0.jar Placebo {placebo@3.1.0 DONE}
		FruitTrees-1.15.2-1.6.0.jar Fruit Trees {fruittrees@1.6.0 DONE}
		Kiwi-1.15.2-2.8.2.jar Kiwi {kiwi@2.8.2 DONE}
		Bookshelf-1.15.2-5.6.40.jar Bookshelf {bookshelf@5.6.40 DONE}
		pneumaticcraft-repressurized-1.15.2-1.5.0-73.jar PneumaticCraft: Repressurized {pneumaticcraft@1.15.2-1.5.0-73 DONE}
		mcjtylib-1.15-4.1.10.jar McJtyLib {mcjtylib@1.15-4.1.10 DONE}
		rftoolsbase-1.15-1.1.7.jar RFToolsBase {rftoolsbase@1.15-1.1.7 DONE}
		xnet-1.15-2.1.11.jar XNet {xnet@1.15-2.1.11 DONE}
		DarkUtilities-1.15.2-3.1.8.jar Dark Utilities {darkutils@3.1.8 DONE}
		Apotheosis-1.15.2-3.3.7.jar Apotheosis {apotheosis@3.3.7 DONE}
		MekanismGenerators-1.15.2-9.10.3.416.jar Mekanism: Generators {mekanismgenerators@9.10.3 DONE}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		JustEnoughResources-1.15.2-0.10.1.77.jar Just Enough Resources {jeresources@0.10.1.77 DONE}
		XNetGases-1.15.2-1.0.0.jar XNet Gases {xnetgases@1.0.0 DONE}
		forge-1.15.2-31.2.43-universal.jar Forge {forge@31.2.43 DONE}
		refinedstorage-1.8.8.jar Refined Storage {refinedstorage@1.8.8 DONE}
		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 DONE}
		forge-1.15.2-31.2.43-client.jar Minecraft {minecraft@1.15.2 DONE}
		industrial-foregoing-1.15.2-2.3.3-e356e61.jar Industrial Foregoing {industrialforegoing@2.3.3 DONE}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		titanium-1.15.2-2.4.2.jar Titanium {titanium@2.4.2 DONE}
		Psi r1.2-84.jar Psi {psi@r1.2-83 DONE}
		ImmersiveEngineering-1.15.2-4.0.1-119.jar Immersive Engineering {immersiveengineering@1.15.2-4.0.1-119 DONE}
		SilentLib-1.15.2-4.6.6+59.jar Silent Lib {silentlib@4.6.6+59 DONE}
		phosphor-forge-mc1.15.2-0.5.2+build.4.jar Phosphor {phosphor@0.5.2+build.4 DONE}
		valhelsia_structures-15.0.3a.jar Valhelsia Structures {valhelsia_structures@15.0.3a DONE}
		CreativeCore_v2.0.5_mc1.15.2.jar CreativeCore {creativecore@2.0.0 DONE}
		SilentGear-1.15.2-1.11.3+160.jar Silent Gear {silentgear@1.11.3+160 DONE}
		ChickenChunks-1.15.2-2.5.0.77-universal.jar ChickenChunks {chickenchunks@1.15.2-2.5.0.77 DONE}
		curios-FORGE-1.15.2-2.0.2.6.jar Curios API {curios@FORGE-1.15.2-2.0.2.6 DONE}
		Botania-r1.15-388.jar Botania {botania@r1.15-388 DONE}
		Patchouli-1.15.2-1.2-35.jar Patchouli {patchouli@1.15.2-1.2-35 DONE}
		gravestone-1.17.5.jar Gravestone Mod {gravestone@1.17.5 DONE}
		FluxNetworks-1.15.2-5.0.3-4.jar Flux Networks {fluxnetworks@1.15.2-5.0.3-4 DONE}
		performant-1.15-3.11m.jar Performant {performant@3.11m DONE}
		elevatorid-1.15.2-1.7.1.jar Elevator Mod {elevatorid@1.15.2-1.7.1 DONE}
		cobbler-1.5.1.jar Cobbler {cobbler@1.5.1 DONE}
		AppleSkin-mc1.15.2-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 DONE}
		refinedstorageaddons-0.6.3.jar Refined Storage Addons {refinedstorageaddons@0.6.3 DONE}
		CodeChickenLib-1.15.2-3.3.1.379-universal.jar CodeChicken Lib {codechickenlib@3.3.1.379 DONE}
		EnderStorage-1.15.2-2.5.0.151-universal.jar EnderStorage {enderstorage@1.15.2-2.5.0.151 DONE}
		BetterMineshaftsForge-1.15.2-1.3.1.jar YUNG's Better Mineshafts {bettermineshafts@1.15.2-1.3.1 DONE}
		effortlessbuilding-1.15.2-2.21.jar Effortless Building {effortlessbuilding@1.15.2-2.21 DONE}
		WailaHarvestability-mc1.15.2-1.1.12.jar Waila Harvestability {wailaharvestability@1.1.12 DONE}
	Kiwi Modules: 
		fruittrees:cherry
		fruittrees:fruittrees
		fruittrees:hybridization
		kiwi:contributors
		kiwi:data
	[Psi] Active spell: None
	Patchouli open book context: n/a
	Player Count: 1 / 8; [ServerPlayerEntity['MotaZX'/141, l='Manga, The final countdown', x=-137.48, y=72.00, z=-2130.29]]
	Data Packs: mod:cobbler, vanilla, mod:jei (incompatible), mod:druidcraft, mod:mekanism, mod:create, mod:clumps (incompatible), mod:journeymap (incompatible), mod:cookingforblockheads (incompatible), mod:placebo (incompatible), mod:fruittrees, mod:kiwi, mod:bookshelf (incompatible), mod:pneumaticcraft, mod:mcjtylib (incompatible), mod:rftoolsbase (incompatible), mod:xnet (incompatible), mod:darkutils (incompatible), mod:apotheosis (incompatible), mod:mekanismgenerators, mod:waila (incompatible), mod:jeresources (incompatible), mod:xnetgases, mod:forge (incompatible), mod:refinedstorage (incompatible), mod:ironchest, mod:industrialforegoing (incompatible), mod:mousetweaks (incompatible), mod:titanium (incompatible), mod:psi (incompatible), mod:immersiveengineering (incompatible), mod:silentlib (incompatible), mod:phosphor, mod:valhelsia_structures (incompatible), mod:creativecore (incompatible), mod:silentgear (incompatible), mod:chickenchunks (incompatible), mod:curios (incompatible), mod:botania (incompatible), mod:patchouli (incompatible), mod:gravestone, mod:fluxnetworks, mod:performant (incompatible), mod:elevatorid, mod:appleskin (incompatible), mod:refinedstorageaddons (incompatible), mod:codechickenlib (incompatible), mod:enderstorage (incompatible), mod:bettermineshafts (incompatible), mod:effortlessbuilding, mod:wailaharvestability (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by pupnewfster** [comment]
We are no longer actively developing 1.15, but even then you are not on the latest version of Mekanism for 1.15 (9.10.9, you are on 9.10.3) so there is a chance it was fixed since then. I also am not quite sure from the crash report but it may have something to do with the effortlessbuilding mod failing to send a packet to something.
