### ISSUE TITLE
1.16.3 Crash on launch

### ISSUE THREAD

**Issue by applemes** [mekanism/Mekanism#6602]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Game crashes on launch with mekanism installed.

#### Steps to reproduce:
1. Launch the Game
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 34.1.12
**Mekanism:** 1.16.3-10.0.10.434
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 10/8/20 1:06 PM
Description: Rendering overlay

java.lang.IllegalStateException: Failed to load description for particle mekanism:laser
	at net.minecraft.client.particle.ParticleManager.func_215236_a(ParticleManager.java:226) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.particle.ParticleManager.lambda$null$0(ParticleManager.java:169) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.particle.ParticleManager$$Lambda$10582/1056409787.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}
Caused by: java.io.FileNotFoundException: mekanism:particles/laser.json
	at net.minecraft.resources.SimpleReloadableResourceManager.func_199002_a(SimpleReloadableResourceManager.java:63) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:solarflux:coremodone}
	at net.minecraft.client.particle.ParticleManager.func_215236_a(ParticleManager.java:205) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	... 8 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:483) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.ResourceLoadProgressGui
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:483) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:584) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.12.jar:34.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$483/460534439.call(Unknown Source) [forge-1.16.3-34.1.12.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4752726432 bytes (4532 MB) / 6543114240 bytes (6240 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 7.0.1+78+master.e9771d8
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.3-34.1.12.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.12.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.3-34.1.12.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.12.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.3-34.1.12.jar fml TRANSFORMATIONSERVICE 
	FML: 34.1
	Forge: net.minecraftforge:34.1.12
	FML Language Providers: 
		javafml@34.1
		minecraft@1
		kotori_scala@2.13.3-build-3
	Mod List: 
		glasscutter-1.16.3-2.0.0.jar Glass Harvesters {glasscutter@1.16.3-2.0.0 COMMON_SETUP}
		AdditionalEnchantedMiner-1.16.2-16.1.0.jar QuarryPlus {quarryplus@16.1.0 COMMON_SETUP}
		Variant16x-1.16.3-v0.15.4.2_beta.jar Variant16x {variant16x@0.15.4.2_beta COMMON_SETUP}
		curiousshulkerboxes-forge-1.16.3-4.0.0.1.jar Curious Shulker Boxes {curiousshulkerboxes@1.16.3-4.0.0.1 COMMON_SETUP}
		ceiling_carpets-mc1.16.1_v0.0.1.jar Ceiling Carpets {ceiling_carpets@0.0.1 COMMON_SETUP}
		Uppers-0.3.1.jar Uppers {uppers@0.3.1 COMMON_SETUP}
		paperbooks_1.16.3_1.1.jar Paper Books {paperbooks@1.1 COMMON_SETUP}
		essentials-1.16.2-2.9.1.jar Essentials {essentials@1.16.2-2.9.1 COMMON_SETUP}
		BetterCaves-1.16.2-1.0.2.jar YUNG's Better Caves {bettercaves@1.16.2-1.0.2 COMMON_SETUP}
		glassential-forge-1.16.3-1.1.5.jar Glassential {glassential@1.1.5 COMMON_SETUP}
		ForgeEndertech-1.16.3-7.0.4.0-build.0017.jar Forge Endertech {forgeendertech@7.0.4.0 COMMON_SETUP}
		Controlling-7.0.0.7.jar Controlling {controlling@7.0.0.7 COMMON_SETUP}
		Placebo-1.16.3-4.3.0.jar Placebo {placebo@4.3.0 COMMON_SETUP}
		citadel-1.4.0.jar Citadel {citadel@1.4.0 COMMON_SETUP}
		darkerloadingscreen-2.2.jar Darker Loading Screen {darkerloadingscreen@2.2 COMMON_SETUP}
		premium-wood-1.16.3-1.3.2.jar Premium Wood {premium_wood@1.3.2 COMMON_SETUP}
		jumbofurnace-1.16.3-2.0.0.0.jar Jumbo Furnace {jumbofurnace@1.16.3-2.0.0.0 COMMON_SETUP}
		Wither-Skeleton-Tweaks-1.16.3-5.2.0.jar Wither Skeleton Tweaks {wstweaks@5.2.0 COMMON_SETUP}
		branders-spawnermod-1.16.3-1.6.7.jar Enhanced Mob Spawners {spawnermod@1.6.7 COMMON_SETUP}
		Bookshelf-1.16.3-8.4.13.jar Bookshelf {bookshelf@8.4.13 COMMON_SETUP}
		toolleveling-1.16.2-1.0.1.jar Tool Leveling {toolleveling@1.16.2 - 1.0.1 COMMON_SETUP}
		Actually.Useful.Smithing.Table-1.0.2.mc.1.16.3.jar Actually Useful Smithing Table {actuallyusefulsmithingtable@1.0.2 mc 1.16.3 COMMON_SETUP}
		DarkUtilities-1.16.3-6.0.1.jar Dark Utilities {darkutils@6.0.1 COMMON_SETUP}
		MekanismGenerators-1.16.3-10.0.10.434.jar Mekanism: Generators {mekanismgenerators@10.0.10 COMMON_SETUP}
		Hwyla-forge-1.10.11-B78_1.16.2.jar Waila {waila@1.10.11-B78_1.16.2 COMMON_SETUP}
		shulkerbox-1.16.3-1.0.0.jar Advanced Shulkerboxes {shulkerbox@1.16.3-1.0.0 COMMON_SETUP}
		pathundergates-1.16.3-1.0.0-release.jar Path Under Gates {pathundergates@1.16.3-1.0.0-release COMMON_SETUP}
		Ma-Essentials-1.16.3-3.4.0.jar Ma Essentials {maessentials@1.16.3-3.4.0 COMMON_SETUP}
		JustEnoughResources-1.16.3-0.12.0.100.jar Just Enough Resources {jeresources@0.12.0.100 COMMON_SETUP}
		shetiphiancore-1.16-3.8.2.jar ShetiPhian-Core {shetiphiancore@3.8.2 COMMON_SETUP}
		MysticalAgradditions-1.16.3-4.1.0.jar Mystical Agradditions {mysticalagradditions@4.1.0 COMMON_SETUP}
		absentbydesign-1.16.2-1.1.0.jar Absent By Design Mod {absentbydesign@1.16.2-1.1.0 COMMON_SETUP}
		refinedstorage-1.9.6.jar Refined Storage {refinedstorage@1.9.6 COMMON_SETUP}
		LootingBowEnchantment-1.16.3-2.0.0.jar LootingBowEnchantment {lootingbowenchantment@2.0.0 COMMON_SETUP}
		replantingcrops_1.16.3_1.5.jar Replanting Crops {replantingcrops@1.5 COMMON_SETUP}
		anviltweaks-3.1.jar Anvil Tweaks {anviltweaks@3.1 COMMON_SETUP}
		industrial-foregoing-1.16.3-3.1.0-7b7cd48.jar Industrial Foregoing {industrialforegoing@3.1.0 COMMON_SETUP}
		TipTheScales-1.16.3-3.0.0.6.jar TipTheScales {tipthescales@3.0.0.6 COMMON_SETUP}
		GreaterEye-1.16.3-1.1.2.jar GreaterEye {greater_eye@1.1.1 COMMON_SETUP}
		BiomesOPlenty-1.16.3-12.0.0.401-universal.jar Biomes O' Plenty {biomesoplenty@1.16.3-12.0.0.401 COMMON_SETUP}
		MekanismAdditions-1.16.3-10.0.10.434.jar Mekanism: Additions {mekanismadditions@10.0.10 COMMON_SETUP}
		valhelsia_structures-16.0.3.jar Valhelsia Structures {valhelsia_structures@16.0.3 COMMON_SETUP}
		ironfurnaces-1.16.3-2.4.0.jar Iron Furnaces {ironfurnaces@2.4.0 COMMON_SETUP}
		masonry-1.16.3-0.3.6.jar Masonry {masonry@NONE COMMON_SETUP}
		BetterDefaultBiomes-1.16.3-Alpha+2.1.0.jar Better Default Biomes {betterdefaultbiomes@Alpha 2.1.0 COMMON_SETUP}
		simplylight-1.16.3-1.0.2.jar Simply Light {simplylight@1.16.3-1.0.2 COMMON_SETUP}
		NetherEnhanced-1.16.3-0.1.jar Nether Enhanced {netherenhanced@0.1 COMMON_SETUP}
		xercamod-1.16.3-1.0.jar Xerca Mod {xercamod@1.16.3-1.0 COMMON_SETUP}
		SolarFluxReborn-1.16.3-16.1.1.jar Solar Flux Reborn {solarflux@16.1.1 COMMON_SETUP}
		randomenchants-4.0.3.jar Random Enchants {randomenchants@4.0.3 COMMON_SETUP}
		curios-forge-1.16.3-4.0.2.0.jar Curios API {curios@1.16.3-4.0.2.0 COMMON_SETUP}
		Patchouli-1.16.2-44.jar Patchouli {patchouli@1.16.2-44 COMMON_SETUP}
		collective-1.16.3-1.45.jar Collective {collective@1.45 COMMON_SETUP}
		extlights-3.1.jar Extended Lights {extlights@3.1 COMMON_SETUP}
		betbeacpl_1.16.3_1.1.jar Better Beacon Placement {betbeacpl@1.1 COMMON_SETUP}
		ObsidianOres-1.16.3-1.1.0.jar Obsidian Ores {obsidianores@1.1.0 COMMON_SETUP}
		lottaterracotta-1.16.3-1.3.1.jar Lotta Terracotta {lottaterracotta@1.16.3-1.3.1 COMMON_SETUP}
		elevatorid-1.16.3-1.7.6.jar Elevator Mod {elevatorid@1.16.3-1.7.6 COMMON_SETUP}
		Gobber2-1.16.3-2.3.11.jar Gobber 2 {gobber2@2.3.8 COMMON_SETUP}
		ftb-ultimine-1.1.0.10.jar FTB Ultimine {ftbultimine@1.1.0.10 COMMON_SETUP}
		EnigmaticLegacy-2.5.2.jar Enigmatic Legacy {enigmaticlegacy@2.5.2 COMMON_SETUP}
		buildersaddition-1.16.3-20200930a.jar Builders Crafts & Addition {buildersaddition@1.16.3-20200930a COMMON_SETUP}
		invcrafting-1.16.2-1.1.2.jar invcrafting {invcrafting@1.16.2-1.1.2 COMMON_SETUP}
		MekanismTools-1.16.3-10.0.10.434.jar Mekanism: Tools {mekanismtools@10.0.10 COMMON_SETUP}
		constructionwand-1.16.2-1.5.jar Construction Wand {constructionwand@1.16.2-1.5 COMMON_SETUP}
		shulkerdt_1.16.3_1.2.jar Shulker Drops Two {shulkerdt@1.2 COMMON_SETUP}
		curiouselytra-forge-1.16.3-4.0.0.1.jar Curious Elytra {curiouselytra@1.16.3-4.0.0.1 COMMON_SETUP}
		fortunate-2.9-MC-1.16.2.jar How Fortunate! {fortunate@2.9-MC-1.16.2 COMMON_SETUP}
		cloth-config-forge-4.1.0.jar Cloth Config v4 API {cloth-config@4.0 COMMON_SETUP}
		clearwater-1.16.3-1.5.jar Clear Water {clearwater@1.16.3-1.5 COMMON_SETUP}
		woodcutter-1.3-1.16.3.jar Wood Cutter {woodcutter@1.3-1.16.3 COMMON_SETUP}
		EnchantmentsReloaded-4.0.jar Enchantments Reloaded {enchantmentsreloaded@2.1 COMMON_SETUP}
		PrettyBeaches_1.16.2-5.1.0.jar Pretty Beaches {prettybeaches@5.1.0 COMMON_SETUP}
		BetterMineshaftsForge-1.16.2-1.0.jar YUNG's Better Mineshafts {bettermineshafts@1.16.2-1.0 COMMON_SETUP}
		Cyclic-1.16.3-0.8.0.jar Cyclic {cyclic@1.16.3-0.8.0 COMMON_SETUP}
		ClientTweaks_1.16.3-5.2.0.jar Client Tweaks {clienttweaks@5.2.0 COMMON_SETUP}
		AdFinders-1.16.3-5.0.3.0-build.0017.jar Advanced Finders {adfinders@5.0.3.0 COMMON_SETUP}
		Ma-Enchants-1.16.3-3.4.0.jar Ma Enchants {ma-enchants@1.16.3-3.4.0 COMMON_SETUP}
		Cucumber-1.16.3-4.1.2.jar Cucumber Library {cucumber@4.1.2 COMMON_SETUP}
		torchslabmod-1.16.3_v1.6.17.jar Torch Slab Mod {torchslabmod@1.6.17 VALIDATE}
		XPFromHarvest-1.16.3-1.2.1.jar XP From Harvest {xpfromharvest@1.2.1 COMMON_SETUP}
		vanillaexcavators-1.16.2-2.1.3.jar Vanilla Excavators {vanillaexcavators@2.1.3 COMMON_SETUP}
		treeharvester_1.16.3-1.5.jar Tree Harvester {treeharvester@1.5 COMMON_SETUP}
		jei-1.16.3-7.3.2.36.jar Just Enough Items {jei@7.3.2.29 COMMON_SETUP}
		justmobheads_1.16.3_3.6.jar Just Mob Heads {justmobheads@3.6 COMMON_SETUP}
		Mekanism-1.16.3-10.0.10.434.jar Mekanism {mekanism@10.0.10 COMMON_SETUP}
		caelus-forge-1.16.3-2.0.0.3.jar Caelus API {caelus@1.16.3-2.0.0.3 COMMON_SETUP}
		reap-1.16.3-1.0.1.jar Reap Mod {reap@1.16.3-1.0.1 COMMON_SETUP}
		colytra-forge-1.16.3-5.0.0.1.jar Colytra {colytra@1.16.3-5.0.0.1 COMMON_SETUP}
		woodutilities-1.0-1.16.3.jar Wooden Utilities {woodenutilities@1.0 COMMON_SETUP}
		Portable+Nether-1.1.jar Portable Nether {portablenether@1.1 COMMON_SETUP}
		Clumps-6.0.0.10.jar Clumps {clumps@6.0.0.10 COMMON_SETUP}
		light-overlay-5.5.3.jar Light Overlay Forge {lightoverlay-forge@NONE COMMON_SETUP}
		sweetconcrete-1.16.3-1.7.1.jar Sweet Concrete {sweetconcrete@1.16.3-1.7.1 COMMON_SETUP}
		comforts-forge-1.16.2-4.0.0.0.jar Comforts {comforts@1.16.2-4.0.0.0 COMMON_SETUP}
		BotanyPots-1.16.3-5.0.1.jar BotanyPots {botanypots@5.0.1 COMMON_SETUP}
		BotanyTrees-1.16.3-1.0.4.jar BotanyTrees {botanytrees@1.0.4 COMMON_SETUP}
		VanillaTweaks-1.16.3-1.5.33.jar VanillaTweaks {vanillatweaks@1.16.3-1.5.33 COMMON_SETUP}
		curioofundying-forge-1.16.3-5.0.0.1.jar Curio of Undying {curioofundying@1.16.3-5.0.0.1 COMMON_SETUP}
		BadMobs-1.16.3-7.0.1.jar BadMobs {badmobs@7.0.1 COMMON_SETUP}
		repurpose-1.3.0.1.jar Repurpose {repurpose@1.3.0.1 COMMON_SETUP}
		TinyMobFarm-1.16.2-1.1.1.jar Tiny Mob Farm {tinymobfarm@1.1.1 COMMON_SETUP}
		mapperbase-1.16.3-2.1.0.0.jar Mapper Base {mapperbase@1.16.3-2.1.0.0 COMMON_SETUP}
		embellishcraft-1.16.3-3.1.0.0.jar EmbellishCraft {embellishcraft@1.16.3-3.1.0.0 COMMON_SETUP}
		embellishcraft-bop-1.16.3-3.1.0.jar EmbellishCraft BoP Addon {embellishcraft-bop@1.16.3-3.1.0 COMMON_SETUP}
		iceandfire-2.0.3-1.16.3.jar Ice and Fire {iceandfire@2.0.3-1.16.3 COMMON_SETUP}
		walljump-forge-1.16.3-1.3.6.jar Wall-Jump! {walljump@1.16.3-1.3.6 COMMON_SETUP}
		PackingTape-1.16.2-0.9.7.jar Packing Tape {packingtape@0.9.7 COMMON_SETUP}
		extradisks-1.16.2-1.3.1.jar Extra Disks {extradisks@1.3.1 COMMON_SETUP}
		strongfarmland-1.16.2-1.1.0.jar Stronger Farmland Mod {strongfarmland@1.16.2-1.1.0 COMMON_SETUP}
		forge-1.16.3-34.1.12-universal.jar Forge {forge@34.1.12 COMMON_SETUP}
		improvedvanilla-1.16.3-1.4.0.jar Improved Vanilla {improvedvanilla@1.16.3 - 1.4.0 COMMON_SETUP}
		amb-1.16.3-0.1.0.jar Aurum's More Blocks {amb@1.16.3-0.1.0 COMMON_SETUP}
		MysticalAgriculture-1.16.3-4.1.0.jar Mystical Agriculture {mysticalagriculture@4.1.0 COMMON_SETUP}
		CraftingTweaks_1.16.3-12.2.0.jar Crafting Tweaks {craftingtweaks@12.2.0 COMMON_SETUP}
		forge-1.16.3-34.1.12-client.jar Minecraft {minecraft@1.16.3 COMMON_SETUP}
		morezombiev_1.16.3_1.1.jar More Zombie Villagers {morezombiev@1.1 COMMON_SETUP}
		EnchantmentDescriptions-1.16.3-5.0.1.jar EnchantmentDescriptions {enchdesc@5.0.1 COMMON_SETUP}
		MouseTweaks-2.13-mc1.16.2.jar Mouse Tweaks {mousetweaks@2.13 COMMON_SETUP}
		titanium-1.16.3-3.1.0.jar Titanium {titanium@3.1.0 COMMON_SETUP}
		compactores-1.16.3-3.0.1.jar Compact Ores {compactores@3.0.1 COMMON_SETUP}
		morevanillalib-1.16.2-1.2.13.jar MoreVanillaLib {morevanillalib@1.2.13 COMMON_SETUP}
		AdLods-1.16.3-4.0.2.0-build.0017.jar Large Ore Deposits {adlods@4.0.2.0 COMMON_SETUP}
		ceilingtorch-1.16.2-v1.8.jar Ceiling Torch {ceilingtorch@v1.8 COMMON_SETUP}
		jeiintegration_1.16.3-6.0.0.8.jar JEI Integration {jeiintegration@6.0.0.8 COMMON_SETUP}
		easy_villagers-1.16.3-1.0.1.jar Easy Villagers {easy_villagers@1.16.3-1.0.1 COMMON_SETUP}
		Mantle-1.16.3-1.6.40.jar Mantle {mantle@1.6.40 COMMON_SETUP}
		Inspirations-1.16.3-1.2.1.19.jar Inspirations {inspirations@1.2.1 COMMON_SETUP}
		betconduitpl_1.16.3_1.1.jar Better Conduit Placement {betconduitpl@1.1 COMMON_SETUP}
		ShulkerTooltip-1.9.3.jar Shulker Tooltip {shulkertooltip@1.9.3 COMMON_SETUP}
		itemcollectors-1.0.6-mc1.16.3.jar Item Collectors {itemcollectors@1.0.6 COMMON_SETUP}
		polymorph-forge-1.16.2-0.14.jar Polymorph {polymorph@1.16.2-0.14 COMMON_SETUP}
		multibeds-1.16-1.7.4.jar Multi-Beds {multibeds@1.7.4 COMMON_SETUP}
		StorageDrawers-1.16.2-8.1.0.jar Storage Drawers {storagedrawers@1.16.2-8.1.0 COMMON_SETUP}
		vanillahammers-1.16.2-2.1.3.jar Vanilla Hammers {vanillahammers@2.1.3 COMMON_SETUP}
		structurize-0.13.90-ALPHA-universal.jar Structurize {structurize@0.13.90-ALPHA COMMON_SETUP}
		minecolonies-0.13.312-BETA-universal.jar Minecolonies {minecolonies@0.13.312-BETA COMMON_SETUP}
		AppleSkin-mc1.16.2-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 COMMON_SETUP}
		smallernp_1.16.3_1.4.jar Smaller Nether Portals {smallernp@1.4 COMMON_SETUP}
		byg-1.0.7.jar Oh The Biomes You'll Go {byg@1.0.7 COMMON_SETUP}
		refinedstorageaddons-0.7.2.jar Refined Storage Addons {refinedstorageaddons@0.7.2 COMMON_SETUP}
		exnihilosequentia-1.16-1.2.1.2.jar Ex Nihilo: Sequentia {exnihilosequentia@1.16-1.2.1.2 COMMON_SETUP}
		AutoLootBowEnchantment-1.16.3-2.0.0.jar AutoLootBowEnchantment {autolootbowenchantment@2.0.0 COMMON_SETUP}
		supertools-1.16.3-3.jar Vanilla+ Tools {supertools@version COMMON_SETUP}
		balancedenchanting-1.0.jar Balanced Enchanting {balancedenchanting@1.0 COMMON_SETUP}
	Crash Report UUID: c119bba3-9a72-4094-8d14-dc81bd2bd43a
	Launched Version: 1.16.3-forge-34.1.12
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.38, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
```

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Can you please provide your latest.log I don't think this has anything to do with Mekanism as if you look inside the jar that file exists but maybe the latest log has a more helpful crash.

**Comment by Harkon1** [comment]
Hi 
I have the same problem!
I press play in the launcher, then I load it and then it breaks shortly before it has finished loading and I am back in the launcher!  Forge version: 1.16.3 34.1.0
Mekanism:1.16.3-10.0.10.434.jar

**Comment by MeinKraft** [comment]
I had the same error. After checking the latest.log it seems TorchSlabMod caused the issue.  I removed the mod and my modpack worked

hope this is of help

**Comment by applemes** [comment]
Meinkraft's comment = solution

**Comment by Harkon1** [comment]
Hello again!
With me it runs now also however the error was another one!

Attention (Facepalm to me ) i had a texture pack from 2013 in my reourcepacks folder!  LOL

Thx for such a great mod like Mekanism and for your hard work on it!
