### ISSUE TITLE
Registry Object not present: mekanism:basic_fluid_tank

### ISSUE THREAD

**Issue by smitheri6** [mekanism/Mekanism#6613]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description: game crashes while I am trying to start up minecraft. From previous issues it looks like it is a problem with forge, Dank Storage, or minecolonies. I have deleted those and their config files, but nothing works. 

Here is my crash log

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 10/10/20 5:09 PM
Description: Initializing game

java.lang.NullPointerException: Registry Object not present: mekanism:basic_fluid_tank
	at java.util.Objects.requireNonNull(Objects.java:290) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:120) ~[?:?] {re:classloading}
	at mekanism.common.registration.DoubleWrappedRegistryObject.getPrimary(DoubleWrappedRegistryObject.java:23) ~[?:?] {re:classloading}
	at mekanism.common.registration.impl.BlockRegistryObject.getBlock(BlockRegistryObject.java:19) ~[?:?] {re:classloading}
	at mekanism.client.ClientRegistrationUtil.registerBlockColorHandler(ClientRegistrationUtil.java:112) ~[?:?] {re:classloading}
	at mekanism.client.ClientRegistration.registerItemColorHandlers(ClientRegistration.java:352) ~[?:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_212_ClientRegistration_registerItemColorHandlers_Item.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168) ~[?:31.2] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:260) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader$$Lambda$4553/1109979753.accept(Unknown Source) ~[?:?] {}
	at java.util.HashMap.forEach(HashMap.java:1280) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:218) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:260) ~[?:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.onItemColorsInit(ForgeHooksClient.java:212) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.color.ItemColors.func_186729_a(ItemColors.java:84) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:420) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:166) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.15.2-31.2.45.jar:31.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$433/235154585.call(Unknown Source) [forge-1.15.2-31.2.45.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:290)
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:120)
	at mekanism.common.registration.DoubleWrappedRegistryObject.getPrimary(DoubleWrappedRegistryObject.java:23)
	at mekanism.common.registration.impl.BlockRegistryObject.getBlock(BlockRegistryObject.java:19)
	at mekanism.client.ClientRegistrationUtil.registerBlockColorHandler(ClientRegistrationUtil.java:112)
	at mekanism.client.ClientRegistration.registerItemColorHandlers(ClientRegistration.java:352)
	at net.minecraftforge.eventbus.ASMEventHandler_212_ClientRegistration_registerItemColorHandlers_Item.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168)
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:260)
	at net.minecraftforge.fml.ModLoader$$Lambda$4553/1109979753.accept(Unknown Source)
	at java.util.HashMap.forEach(HashMap.java:1280)
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:218)
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:260)
	at net.minecraftforge.client.ForgeHooksClient.onItemColorsInit(ForgeHooksClient.java:212)
	at net.minecraft.client.renderer.color.ItemColors.func_186729_a(ItemColors.java:84)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:420)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$433/235154585.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5055735304 bytes (4821 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.2+70+master.2845bb9
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.45.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.45.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.45.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.45.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.45.jar fml TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.45
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		forge-1.15.2-31.2.45-client.jar Minecraft {minecraft@1.15.2 CREATE_REGISTRIES}
		wetstone-1.2.0.jar Wetstone {wetstone@1.2.0 CREATE_REGISTRIES}
		dwmh-1.15.2-4.0.0.jar Dude! Where's my Horse? {dwmh@NONE CREATE_REGISTRIES}
		useful_backpacks-1.15.2-1.10.3.77.jar Useful Backpacks {usefulbackpacks@1.10.3.77 CREATE_REGISTRIES}
		theoneprobe-1.15-2.0.7.jar The One Probe {theoneprobe@1.15-2.0.7 CREATE_REGISTRIES}
		swingthroughgrass-1.15.2-1.4.0.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.0 CREATE_REGISTRIES}
		astralsorcery-1.15.2-1.12.9.jar Astral Sorcery {astralsorcery@1.15.2-1.12.9 CREATE_REGISTRIES}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 CREATE_REGISTRIES}
		ToolBelt-1.15.2-1.14.1.jar Tool Belt {toolbelt@1.14.1 CREATE_REGISTRIES}
		Cucumber-1.15.2-3.0.9.jar Cucumber Library {cucumber@3.0.9 CREATE_REGISTRIES}
		animalnet-v1.15.2+Forge+b1.jar AnimalNet {animalnet@v1.15.2 Forge b1 CREATE_REGISTRIES}
		TrashSlot_1.15.2-11.0.0.jar TrashSlot {trashslot@11.0.0 CREATE_REGISTRIES}
		aiotbotania-1.15.2-1.2.3.jar AIOT Botania {aiotbotania@1.2.3 CREATE_REGISTRIES}
		valhelsia_structures-15.0.3a.jar Valhelsia Structures {valhelsia_structures@15.0.3a CREATE_REGISTRIES}
		Mine+and+Slash-1.15.2-3.7.4.jar Mine and Slash {mmorpg@3.7.4 CREATE_REGISTRIES}
		jei-1.15.2-6.0.3.15.jar Just Enough Items {jei@6.0.3.15 CREATE_REGISTRIES}
		jei-professions-1.0.0-1.15.2.jar JEI Professions {jeiprofessions@1.0.0 CREATE_REGISTRIES}
		AzureRPGItems+1.15.2-1.3.3.jar Azure RPG Items {azurerpgitems@1.1.0 CREATE_REGISTRIES}
		prefab-1.5.0.9.jar Prefab {prefab@1.5.0.9 CREATE_REGISTRIES}
		Mekanism-1.15.2-9.10.9.422.jar Mekanism {mekanism@9.10.9 CREATE_REGISTRIES}
		invtweaks-1.15.2-2.0.9.jar Inventory Tweaks Renewed {invtweaks@1.15.2-2.0.9 CREATE_REGISTRIES}
		curios-FORGE-1.15.2-2.0.2.6.jar Curios API {curios@FORGE-1.15.2-2.0.2.6 CREATE_REGISTRIES}
		Botania-r1.15-388.jar Botania {botania@r1.15-388 CREATE_REGISTRIES}
		Patchouli-1.15.2-1.2-35.jar Patchouli {patchouli@1.15.2-1.2-35 CREATE_REGISTRIES}
		Neat+1.6-22.jar Neat {neat@1.6-22 CREATE_REGISTRIES}
		MS+Auto-Compat-1.15.2-1.2.0.jar M&S Auto-Compat 1.15.1 {azurecompat@1.2.0 CREATE_REGISTRIES}
		BetterCaves-1.15.2-1.0.jar YUNG's Better Caves {bettercaves@1.15.2-1.0 CREATE_REGISTRIES}
		Xaeros_Minimap_20.24.0_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.24.0 CREATE_REGISTRIES}
		Waystones_1.15.2-6.0.2.jar Waystones {waystones@6.0.2 CREATE_REGISTRIES}
		gravestone-1.17.5.jar Gravestone Mod {gravestone@1.17.5 CREATE_REGISTRIES}
		CTM-MC1.15.2-1.1.1.13 (1).jar ConnectedTexturesMod {ctm@MC1.15.2-1.1.1.13 CREATE_REGISTRIES}
		OreExcavation-1.7.151.jar Ore Excavation {oreexcavation@NONE CREATE_REGISTRIES}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 CREATE_REGISTRIES}
		zDungeonCrawl-1.15.2-2.1.0.jar Dungeon Crawl {dungeoncrawl@2.1.0 CREATE_REGISTRIES}
		betteranimalsplus-1.15.2-10.0.0.jar Better Animals Plus {betteranimalsplus@10.0.0 CREATE_REGISTRIES}
		guardvillagers-1.15.2-1.0.8.jar Guard Villagers {guardvillagers@1.0.7 CREATE_REGISTRIES}
		u_team_core-1.15.2-3.0.2.169.jar U Team Core {uteamcore@3.0.2.169 CREATE_REGISTRIES}
		PickleTweaks-1.15.2-4.0.4.jar Pickle Tweaks {pickletweaks@4.0.4 CREATE_REGISTRIES}
		AppleSkin-mc1.15.2-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 CREATE_REGISTRIES}
		observerlib-1.15.2-1.2.0.v60.jar ObserverLib {observerlib@1.15.2-1.2.0 CREATE_REGISTRIES}
		traverse-1.15.2-3.2.0.jar Traverse {traverse@1.15.2-3.2.0 ERROR}
		forge-1.15.2-31.2.45-universal.jar Forge {forge@31.2.45 CREATE_REGISTRIES}
		FastLeafDecay-v22.1.jar FastLeafDecay {fastleafdecay@v22.1 CREATE_REGISTRIES}
		BetterMineshaftsForge-1.15.2-1.3.1.jar YUNG's Better Mineshafts {bettermineshafts@1.15.2-1.3.1 CREATE_REGISTRIES}
		exp_bottling-1.15.2-1.jar EXP Bottling {exp_bottling@1.15.2-1 CREATE_REGISTRIES}
		MysticalAgriculture-1.15.2-3.0.10.jar Mystical Agriculture {mysticalagriculture@3.0.10 CREATE_REGISTRIES}
		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 CREATE_REGISTRIES}
		CraftingTweaks_1.15.2-11.0.1.jar Crafting Tweaks {craftingtweaks@11.0.1 CREATE_REGISTRIES}
	Launched Version: 1.15.2-forge-31.2.45
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics 5500 GL version 4.4.0 - Build 20.19.15.5070, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 4x Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz

#### Steps to reproduce:
1. download mekanism 1.15.2-9.10.9.422.jar
2. Try to start minecraft
3. crash

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
This has nothing to do with mekanism and is another mod crashing you and it is being hidden due to https://github.com/MinecraftForge/MinecraftForge/issues/6374 if you provide your latest log we can potentially tell you the actual crash.
