### ISSUE TITLE
1.16.3 added new mod to a previous created world and biomes mod crashes the save as far as i can tell

### ISSUE THREAD

**Issue by SDUBZ** [mekanism/Mekanism#6624]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
after adding mekanism it was crashing the world save without the mod in previous state

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.16.3- 34.1.19
**Mekanism:** Mekanism-1.16.3-10.0.11.436 plus addons of same versions
**Other relevant version:** 
i reported on bops gh before and they lead me to coming here 
https://github.com/Glitchfiend/BiomesOPlenty/issues/1704

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://github.com/Glitchfiend/BiomesOPlenty/files/5382802/latest.log
other mods used
https://github.com/Glitchfiend/BiomesOPlenty/files/5382801/mods.txt

**Comment by thiakil** [comment]
The error is in their code. From the quick look I had at their github, its trying to read something from their config.

```
[17:12:38] [Render thread/WARN]: Failed to load save.
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_51]
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_51]
	at biomesoplenty.common.world.BOPWorldTypeUtil.isUsingBopWorldType(BOPWorldTypeUtil.java:46) ~[?:?]
	at biomesoplenty.client.handler.GuiEventHandler.isBopWorldType(GuiEventHandler.java:142) [?:?]
	at biomesoplenty.client.handler.GuiEventHandler.onGuiDraw(GuiEventHandler.java:95) [?:?]
	at net.minecraftforge.eventbus.ASMEventHandler_208_GuiEventHandler_onGuiDraw_DrawScreenEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) [eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) [eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:278) [?:?]
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:491) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:584) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.19.jar:34.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$478/1013364696.call(Unknown Source) [forge-1.16.3-34.1.19.jar:34.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?]
```
