### ISSUE TITLE
Loading crash, laser.json is not found

### ISSUE THREAD

**Issue by Igor006** [mekanism/Mekanism#6664]
#### Issue description:
I found something intresting in crash log and I can't open the game and I believe its because of mekanism
Caused by: java.io.FileNotFoundException: mekanism:particles/laser.json
That text above is what I found in crash log.
#### Steps to reproduce:
I don't know how to reproduce it really.
#### Version:
**Forge:** 34.1.32
**Mekanism:**  1.16.3-10.0.15.441
And here is crash log 
[crash-2020-10-27_18.02.18-client.txt](https://github.com/mekanism/Mekanism/files/5446902/crash-2020-10-27_18.02.18-client.txt)

**Comment by pupnewfster** [comment]
Please provide the latest log as that crash report is incorrect.

**Comment by Igor006** [comment]
[crash-2020-10-27_18.02.18-client.txt](https://github.com/mekanism/Mekanism/files/5446969/crash-2020-10-27_18.02.18-client.txt)
I hope now its ok

**Comment by pupnewfster** [comment]
Ya that contains useful information, for some reason forge sometimes still blames the wrong mods for crashes when it crashes at specific times; seems the actual crash is being caused by BiomesOPlenty
```
[27/10/2020 18:25:59 PM] [18:25:59] [Render thread/ERROR]: Exception caught during firing event: null
[27/10/2020 18:25:59 PM] 	Index: 2
[27/10/2020 18:25:59 PM] 	Listeners:
[27/10/2020 18:25:59 PM] 		0: NORMAL
[27/10/2020 18:25:59 PM] 		1: ASM: class biomesoplenty.init.ModPaintings registerPaintingTypes(Lnet/minecraftforge/event/RegistryEvent$Register;)V
[27/10/2020 18:25:59 PM] 		2: ASM: class biomesoplenty.init.ModBiomes registerBiomes(Lnet/minecraftforge/event/RegistryEvent$Register;)V
[27/10/2020 18:25:59 PM] 		3: ASM: class biomesoplenty.init.ModItems registerItems(Lnet/minecraftforge/event/RegistryEvent$Register;)V
[27/10/2020 18:25:59 PM] 		4: ASM: class biomesoplenty.init.ModSounds registerSounds(Lnet/minecraftforge/event/RegistryEvent$Register;)V
[27/10/2020 18:25:59 PM] 		5: ASM: class biomesoplenty.init.ModBlocks registerBlocks(Lnet/minecraftforge/event/RegistryEvent$Register;)V
[27/10/2020 18:25:59 PM] 		6: ASM: class biomesoplenty.init.ModEntities registerEntities(Lnet/minecraftforge/event/RegistryEvent$Register;)V
[27/10/2020 18:25:59 PM] java.lang.ExceptionInInitializerError
[27/10/2020 18:25:59 PM] 	at biomesoplenty.common.biome.overworld.TropicBeachBiome.configureGeneration(TropicBeachBiome.java:40)
[27/10/2020 18:25:59 PM] 	at biomesoplenty.common.biome.BiomeTemplate.build(BiomeTemplate.java:46)
[27/10/2020 18:25:59 PM] 	at biomesoplenty.common.biome.BiomeRegistry$TemplateRegistrationData.<init>(BiomeRegistry.java:477)
[27/10/2020 18:25:59 PM] 	at biomesoplenty.common.biome.BiomeRegistry$ToggleableStandardBiomeRegistrationData.<init>(BiomeRegistry.java:643)
[27/10/2020 18:25:59 PM] 	at biomesoplenty.common.biome.BiomeRegistry.deferTechnicalBiomeRegistration(BiomeRegistry.java:48)
[27/10/2020 18:25:59 PM] 	at biomesoplenty.init.ModBiomes.registerTechnicalBiome(ModBiomes.java:345)
[27/10/2020 18:25:59 PM] 	at biomesoplenty.init.ModBiomes.registerBiomes(ModBiomes.java:116)
[27/10/2020 18:25:59 PM] 	at net.minecraftforge.eventbus.ASMEventHandler_27_ModBiomes_registerBiomes_Register.invoke(.dynamic)
[27/10/2020 18:25:59 PM] 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
[27/10/2020 18:25:59 PM] 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
[27/10/2020 18:25:59 PM] 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120)
[27/10/2020 18:25:59 PM] 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:111)
[27/10/2020 18:25:59 PM] 	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
[27/10/2020 18:25:59 PM] 	at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56)
[27/10/2020 18:25:59 PM] 	at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40)
[27/10/2020 18:25:59 PM] 	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:242)
[27/10/2020 18:25:59 PM] 	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:229)
[27/10/2020 18:25:59 PM] 	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:195)
[27/10/2020 18:25:59 PM] 	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$1(ClientModLoader.java:103)
[27/10/2020 18:25:59 PM] 	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:123)
[27/10/2020 18:25:59 PM] 	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:103)
[27/10/2020 18:25:59 PM] 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:424)
[27/10/2020 18:25:59 PM] 	at net.minecraft.client.main.Main.main(Main.java:149)
[27/10/2020 18:25:59 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[27/10/2020 18:25:59 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[27/10/2020 18:25:59 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[27/10/2020 18:25:59 PM] 	at java.lang.reflect.Method.invoke(Unknown Source)
[27/10/2020 18:25:59 PM] 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[27/10/2020 18:25:59 PM] 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[27/10/2020 18:25:59 PM] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[27/10/2020 18:25:59 PM] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[27/10/2020 18:25:59 PM] 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
[27/10/2020 18:25:59 PM] 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
[27/10/2020 18:25:59 PM] Caused by: java.lang.IllegalStateException: Can not register to a locked registry. Modder should use Forge Register methods.
[27/10/2020 18:25:59 PM] 	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:56)
[27/10/2020 18:25:59 PM] 	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:72)
[27/10/2020 18:25:59 PM] 	at net.minecraftforge.registries.NamespacedWrapper.func_218381_a(NamespacedWrapper.java:40)
[27/10/2020 18:25:59 PM] 	at net.minecraft.util.registry.Registry.func_218322_a(Registry.java:456)
[27/10/2020 18:25:59 PM] 	at biomesoplenty.common.world.gen.surfacebuilders.BOPSurfaceBuilders.register(BOPSurfaceBuilders.java:55)
[27/10/2020 18:25:59 PM] 	at biomesoplenty.common.world.gen.surfacebuilders.BOPSurfaceBuilders.<clinit>(BOPSurfaceBuilders.java:35)
[27/10/2020 18:25:59 PM] 	... 33 more
[27/10/2020 18:25:59 PM] 
[27/10/2020 18:25:59 PM] [18:25:59] [Render thread/ERROR]: Caught exception during event RegistryEvent.Register<minecraft:worldgen/biome> dispatch for modid biomesoplenty
[27/10/2020 18:25:59 PM] java.lang.ExceptionInInitializerError: null
[27/10/2020 18:25:59 PM] 	at biomesoplenty.common.biome.overworld.TropicBeachBiome.configureGeneration(TropicBeachBiome.java:40) ~[biomesoplenty:?]
[27/10/2020 18:25:59 PM] 	at biomesoplenty.common.biome.BiomeTemplate.build(BiomeTemplate.java:46) ~[biomesoplenty:?]
[27/10/2020 18:25:59 PM] 	at biomesoplenty.common.biome.BiomeRegistry$TemplateRegistrationData.<init>(BiomeRegistry.java:477) ~[biomesoplenty:?]
[27/10/2020 18:25:59 PM] 	at biomesoplenty.common.biome.BiomeRegistry$ToggleableStandardBiomeRegistrationData.<init>(BiomeRegistry.java:643) ~[biomesoplenty:?]
[27/10/2020 18:25:59 PM] 	at biomesoplenty.common.biome.BiomeRegistry.deferTechnicalBiomeRegistration(BiomeRegistry.java:48) ~[biomesoplenty:?]
[27/10/2020 18:25:59 PM] 	at biomesoplenty.init.ModBiomes.registerTechnicalBiome(ModBiomes.java:345) ~[biomesoplenty:?]
[27/10/2020 18:25:59 PM] 	at biomesoplenty.init.ModBiomes.registerBiomes(ModBiomes.java:116) ~[biomesoplenty:?]
[27/10/2020 18:25:59 PM] 	at net.minecraftforge.eventbus.ASMEventHandler_27_ModBiomes_registerBiomes_Register.invoke(.dynamic) ~[?:?]
[27/10/2020 18:25:59 PM] 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?]
[27/10/2020 18:25:59 PM] 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?]
[27/10/2020 18:25:59 PM] 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge:34.1]
[27/10/2020 18:25:59 PM] 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:111) ~[forge:?]
[27/10/2020 18:25:59 PM] 	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_251]
[27/10/2020 18:25:59 PM] 	at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56) ~[forge:?]
[27/10/2020 18:25:59 PM] 	at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40) ~[forge:?]
[27/10/2020 18:25:59 PM] 	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:242) ~[forge:?]
[27/10/2020 18:25:59 PM] 	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:229) ~[forge:?]
[27/10/2020 18:25:59 PM] 	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:195) ~[forge:?]
[27/10/2020 18:25:59 PM] 	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$1(ClientModLoader.java:103) ~[forge:?]
[27/10/2020 18:25:59 PM] 	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:123) ~[forge:?]
[27/10/2020 18:25:59 PM] 	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:103) ~[forge:?]
[27/10/2020 18:25:59 PM] 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:424) ~[?:?]
[27/10/2020 18:25:59 PM] 	at net.minecraft.client.main.Main.main(Main.java:149) ~[client-1.16.3.jar:?]
[27/10/2020 18:25:59 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
[27/10/2020 18:25:59 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
[27/10/2020 18:25:59 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
[27/10/2020 18:25:59 PM] 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
[27/10/2020 18:25:59 PM] 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.3-34.1.32.jar:34.1]
[27/10/2020 18:25:59 PM] 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.5.jar:?]
[27/10/2020 18:25:59 PM] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.5.jar:?]
[27/10/2020 18:25:59 PM] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.5.jar:?]
[27/10/2020 18:25:59 PM] 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-8.0.5.jar:?]
[27/10/2020 18:25:59 PM] 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-8.0.5.jar:?]
[27/10/2020 18:25:59 PM] Caused by: java.lang.IllegalStateException: Can not register to a locked registry. Modder should use Forge Register methods.
[27/10/2020 18:25:59 PM] 	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:56) ~[forge:?]
[27/10/2020 18:25:59 PM] 	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:72) ~[forge:?]
[27/10/2020 18:25:59 PM] 	at net.minecraftforge.registries.NamespacedWrapper.func_218381_a(NamespacedWrapper.java:40) ~[forge:?]
[27/10/2020 18:25:59 PM] 	at net.minecraft.util.registry.Registry.func_218322_a(Registry.java:456) ~[?:?]
[27/10/2020 18:25:59 PM] 	at biomesoplenty.common.world.gen.surfacebuilders.BOPSurfaceBuilders.register(BOPSurfaceBuilders.java:55) ~[biomesoplenty:?]
[27/10/2020 18:25:59 PM] 	at biomesoplenty.common.world.gen.surfacebuilders.BOPSurfaceBuilders.<clinit>(BOPSurfaceBuilders.java:35) ~[biomesoplenty:?]
[27/10/2020 18:25:59 PM] 	... 33 more
```

**Comment by Igor006** [comment]
ok thanks
