### ISSUE TITLE
Crash after updating Forge Mod Loader - Failed to load description for particle mekanism:laser

### ISSUE THREAD

**Issue by Velken** [mekanism/Mekanism#6668]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Updating Forge above 34.1.25 causes crash "Failed to load description for particle mekanism:laser"

#### Steps to reproduce:
1.Update forge to above 34.1.25
2.Launch game
3.Crash on startup

#### Version (make sure you are on the latest version before reporting):
**Forge:**  34.1.34
**Mekanism:** Mekanism-1.16.3-10.0.15.441
**Other relevant version:** Forge 34.1.25

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
Working:
[Forge 25 Latest.log](https://pastebin.com/LjVhwdvA)
Crash:
[Forge 34 Crash](https://pastebin.com/qiUn1kmM)
[Forge 34 Latest.log](https://pastebin.com/bx36mih8)

**Comment by thiakil** [comment]
https://github.com/mekanism/Mekanism/issues?q=is%3Aissue+Failed+to+load+description+for+particle+mekanism%3Alaser

**Comment by thiakil** [comment]
```
[07:37:57] [Render thread/ERROR]: Exception caught during firing event: Can not register to a locked registry. Modder should use Forge Register methods.
	Index: 5
	Listeners:
		0: NORMAL
		1: ASM: class com.qouteall.hiding_in_the_bushes.ModMainForge$RegistryEvents onBlocksRegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		2: ASM: class com.qouteall.hiding_in_the_bushes.ModMainForge$RegistryEvents onItemRegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		3: ASM: class com.qouteall.hiding_in_the_bushes.ModMainForge$RegistryEvents onEntityRegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		4: ASM: class com.qouteall.hiding_in_the_bushes.ModMainForge$RegistryEvents onPotionRegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		5: ASM: class com.qouteall.hiding_in_the_bushes.ModMainForge$RegistryEvents onEffectRegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
java.lang.IllegalStateException: Can not register to a locked registry. Modder should use Forge Register methods.
	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:56)
	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:72)
	at net.minecraftforge.registries.NamespacedWrapper.func_218381_a(NamespacedWrapper.java:40)
	at net.minecraft.util.registry.Registry.func_218322_a(Registry.java:456)
	at com.qouteall.hiding_in_the_bushes.ModMainForge$RegistryEvents.onEffectRegistry(ModMainForge.java:406)
	at net.minecraftforge.eventbus.ASMEventHandler_132_RegistryEvents_onEffectRegistry_Register.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120)
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:111)
	at net.minecraftforge.fml.ModContainer$$Lambda$3213/333022446.run(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618)
	at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56)
	at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40)
	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:242)
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:229)
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:195)
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$1(ClientModLoader.java:103)
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2904/1409864883.run(Unknown Source)
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:123)
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2905/249483336.run(Unknown Source)
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:103)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:424)
	at net.minecraft.client.main.Main.main(Main.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$472/1703358554.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
```
