### ISSUE TITLE
My game crashes unexpectedly and it looks like a Entangoloporter issue

### ISSUE THREAD

**Issue by ZodiacTG** [mekanism/Mekanism#6933]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
My game crashes after a while on my server and looking at the crash report it looks like it might have something to do with the Quantum Entangoloporter

#### Steps to reproduce:
unsure

#### Version (make sure you are on the latest version before reporting):
**Forge: 36.0.1
**Mekanism: v10
**Other relevant version: Valhelsia 3 modpack, version 3.1.6

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

java.lang.NullPointerException: Unexpected error
	at mekanism.common.lib.frequency.FrequencyManager.createOrLoad(FrequencyManager.java:140) ~[?:10.0.18] {re:classloading}
	at mekanism.common.lib.frequency.FrequencyManagerWrapper.getPrivateManager(FrequencyManagerWrapper.java:54) ~[?:10.0.18] {re:classloading}
	at mekanism.common.lib.frequency.TileComponentFrequency.getManager(TileComponentFrequency.java:146) ~[?:10.0.18] {re:classloading}
	at mekanism.common.lib.frequency.TileComponentFrequency.setFrequencyFromData(TileComponentFrequency.java:71) ~[?:10.0.18] {re:classloading}
	at mekanism.common.lib.frequency.IFrequencyHandler.setFrequency(IFrequencyHandler.java:16) ~[?:10.0.18] {re:classloading}
	at mekanism.common.tile.TileEntityQuantumEntangloporter.readSustainedData(TileEntityQuantumEntangloporter.java:257) ~[?:10.0.18] {re:classloading}
	at mekanism.common.block.BlockMekanism.func_180633_a(BlockMekanism.java:278) ~[?:10.0.18] {re:classloading}
	at net.minecraft.item.BlockItem.func_195942_a(BlockItem.java:66) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:BlockItemMixin,pl:mixin:A}
	at net.minecraft.item.BlockItem.func_195939_a(BlockItem.java:39) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:BlockItemMixin,pl:mixin:A}
	at shadows.apotheosis.deadly.asm.DeadlyHooks.lambda$onItemUse$0(DeadlyHooks.java:122) ~[?:4.4.1] {re:classloading}
	at shadows.apotheosis.deadly.asm.DeadlyHooks$$Lambda$25300/1083307414.apply(Unknown Source) ~[?:?] {}
	at shadows.apotheosis.deadly.asm.DeadlyHooks.onItemUse(DeadlyHooks.java:136) ~[?:4.4.1] {re:classloading}
	at shadows.apotheosis.deadly.asm.DeadlyHooks.onItemUse(DeadlyHooks.java:122) ~[?:4.4.1] {re:classloading}

[crash-2021-02-07_22.17.53-client.txt](https://github.com/mekanism/Mekanism/files/5941268/crash-2021-02-07_22.17.53-client.txt)

**Comment by pupnewfster** [comment]
Does it happen without apotheosis?

**Comment by ZodiacTG** [comment]
Idk, I haven't really taken out any mods to test because I'm playing a modpack and I don't really want to fuck anything up. I could try to reproduce the error and see if the crash report is any different a second time. This crash has happened more than once but this is the only report I read.

**Comment by pupnewfster** [comment]
Ya, my best guess given nothing on that line should be null when it is being called is that it is either apotheosis (given that stack trace doesn't look too friendly name wise in terms of the ASM they are doing), or if you aren't using forge on the server but using one of the forge/bukkit(or other plugin software) hybrids the hybrid probably is broken.

**Comment by pupnewfster** [comment]
Managed to figure out and reproduce this (without apotheosis). It seems there was one code path that was calling something that only expects to exist on the server client side by accident.

**Comment by pupnewfster** [comment]
We leave issues open until the version they are fixed in is released.

**Comment by XCOYoshi** [comment]
[crash-2021-02-05_22.19.35-client.txt](https://github.com/mekanism/Mekanism/files/5935388/crash-2021-02-05_22.19.35-client.txt)
Similär Problem
