### ISSUE TITLE
Upon entering a LAN game the client side crashes, seems like flamethrower is causing this

### ISSUE THREAD

**Issue by Thecnogamer** [mekanism/Mekanism#6951]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Using a small modpack, 46 mods, the game crashes when entering a LAN game. the host keeps ok but the "guest" crashes as soon as the world loads.
looking at the crash report, seems like flamethrower is being checked and so is player state related to it

#### Steps to reproduce:
*it may be mod conflict*
1.Create a world
2.Host to LAN
3.Ask for someone to enter it

#### Version (make sure you are on the latest version before reporting):
**M 1.16.4 F 35.1.37** .
**Mekanism: 10.0.18.445** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
Preview:Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at mekanism.common.base.PlayerState.setFlamethrowerState(PlayerState.java:319) ~[mekanism:10.0.18] {re:classloading}
	at mekanism.client.ClientTickHandler.tickStart(ClientTickHandler.java:183) ~[mekanism:10.0.18] {re:classloading}
	at mekanism.client.ClientTickHandler.onTick(ClientTickHandler.java:146) ~[mekanism:10.0.18] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_576_ClientTickHandler_onTick_ClientTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPreClientTick(BasicEventHooks.java:105) ~[forge:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1414) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[Modpack%201.16.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.37.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

 I'm Thecnogamer and the host is Blaze_of_winner
 [Full crash report](https://gist.github.com/Thecnogamer/1cce7ea63cb3de2c0ca8de13c2763217)

Edit: It happens in vice-versa too

**Comment by Robball14** [comment]
> Please use search functionality before posting issues. 
If you search there are like 8 issues that reports the same problem, please use, as said, the research functionality first. 
Anyway it should be programmed to be fixed in the next Mekanism update iirc

**Comment by Thecnogamer** [comment]
Thank you and sorry for the inconvenience
