### ISSUE TITLE
"'TransitRequest' was wrapped around a non-IItemHandler inventory. This should not happen!"

### ISSUE THREAD

**Issue by Peekofwar** [mekanism/Mekanism#7327]
### Issue description

A player on my server placed down a digital miner, a logistical transport pipe, and a personal chest, and once the machine is activated, it starts spamming the console with errors. Not entirely sure if it also caused the crash, but I'd assume it was.

![mekanism_machine_ran_out_of_cobblestone_1](https://user-images.githubusercontent.com/10189526/137569545-e6cd841e-39dc-4c63-adde-2c167117a5e6.JPG)

![mekanism_machine_ran_out_of_cobblestone_2](https://user-images.githubusercontent.com/10189526/137569547-162d38de-c56d-42c9-9b25-0913353b0f49.JPG)

```
[15Oct2021 21:58:13.045] [Server thread/WARN] [Mekanism/]: 'TransitRequest' was wrapped around a non-IItemHandler inventory. This should not happen!
java.lang.Exception: null
	at mekanism.common.util.InventoryUtils.assertItemHandler(InventoryUtils.java:39) ~[mekanism:10.0.21]
	at mekanism.common.lib.inventory.TransitRequest.definedItem(TransitRequest.java:38) ~[mekanism:10.0.21]
	at mekanism.common.lib.inventory.TransitRequest.definedItem(TransitRequest.java:33) ~[mekanism:10.0.21]
	at mekanism.common.tile.machine.TileEntityDigitalMiner.getReplace(TileEntityDigitalMiner.java:472) ~[mekanism:10.0.21]
	at mekanism.common.tile.machine.TileEntityDigitalMiner.setReplace(TileEntityDigitalMiner.java:429) ~[mekanism:10.0.21]
	at mekanism.common.tile.machine.TileEntityDigitalMiner.onUpdateServer(TileEntityDigitalMiner.java:262) ~[mekanism:10.0.21]
	at mekanism.common.tile.base.TileEntityMekanism.func_73660_a(TileEntityMekanism.java:498) ~[mekanism:10.0.21]
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
[15Oct2021 21:58:13.046] [Server thread/WARN] [Mekanism/]:  - details: mekanism.common.tile.transmitter.TileEntityLogisticalTransporter@22cbf706 BlockPos{x=-2100, y=81, z=-1877}
```

[crash-2021-10-15_21.51.53-server.txt](https://github.com/mekanism/Mekanism/files/7356576/crash-2021-10-15_21.51.53-server.txt)

### Steps to reproduce

1: Place down a digital miner
2: Place down a logistic pipe on the top of the digital miner
3: Place a chest on the pipe
4: Activate the digital miner (This particular one is configured to require cobblestone to replace blovcks)

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.2

### Mekanism version

10.0.21 (Latest)

**Comment by Seniorendi** [comment]
👍🏻
