### ISSUE TITLE
1.18 build incompatible with BiggerReactors & RSGauges

### ISSUE THREAD

**Issue by SkyTheCodeMaster** [mekanism/Mekanism#7400]
### Issue description

When building the 1.18.x branch of the repo, and loading the mods (mekanism, generators, tools, additions, defense) in a modpack with BiggerReactors and RS Gauges, loading a world gives the following error:
> Errors in currently selected datapacks prevented the world from loading.
> You can either try to load it with only the vanilla data pack ("safe mode"), or go back to the title screen and fix it manually.
The error in console is:
<details>
  <summary>Error Log</summary>

  ```
[11:03:13] [Worker-Main-28/ERROR]: Couldn't load tag forge:superheated_sodium as it is missing following references: biggerreactors:superheated_sodium (from biggerreactors-1.18.1-0.6.0-beta.jar)
[11:03:13] [Worker-Main-24/ERROR]: Couldn't load tag rsgauges:soils as it is missing following references: minecraft:grass_path (from rsgauges-1.18.1-1.2.13-b2.jar)
[11:03:15] [Render thread/WARN]: Failed to load datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Missing required tags: ResourceKey[minecraft:root / minecraft:fluid]:forge:superheated_sodium
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.client.Minecraft.m_91190_(Minecraft.java:2071) ~[client-1.18.1-20211210.034407-srg.jar%23149!:?]
	at net.minecraft.client.Minecraft.doLoadLevel(Minecraft.java:1906) ~[client-1.18.1-20211210.034407-srg.jar%23149!:?]
	at net.minecraft.client.Minecraft.m_91200_(Minecraft.java:1873) ~[client-1.18.1-20211210.034407-srg.jar%23149!:?]
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_101744_(WorldSelectionList.java:436) ~[client-1.18.1-20211210.034407-srg.jar%23149!:?]
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_101704_(WorldSelectionList.java:342) ~[client-1.18.1-20211210.034407-srg.jar%23149!:?]
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_6375_(WorldSelectionList.java:278) ~[client-1.18.1-20211210.034407-srg.jar%23149!:?]
	at net.minecraft.client.gui.components.AbstractSelectionList.m_6375_(AbstractSelectionList.java:323) ~[client-1.18.1-20211210.034407-srg.jar%23149!:?]
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:27) ~[client-1.18.1-20211210.034407-srg.jar%23149!:?]
	at net.minecraft.client.MouseHandler.lambda$onPress$0(MouseHandler.java:88) ~[client-1.18.1-20211210.034407-srg.jar%23149!:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:527) ~[client-1.18.1-20211210.034407-srg.jar%23149!:?]
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.18.1-20211210.034407-srg.jar%23149!:?]
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.18.1-20211210.034407-srg.jar%23149!:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:101) ~[client-1.18.1-20211210.034407-srg.jar%23149!:?]
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.18.1-20211210.034407-srg.jar%23149!:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar%230!:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar%236!:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar%230!:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.m_69830_(RenderSystem.java:220) ~[client-1.18.1-20211210.034407-srg.jar%23149!:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1065) ~[client-1.18.1-20211210.034407-srg.jar%23149!:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.18.1-20211210.034407-srg.jar%23149!:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%23149!:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.36.jar%2351!:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%2340!:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%2340!:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%2340!:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%2340!:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%2340!:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%2340!:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%2340!:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc3.jar:mmc3]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.IllegalStateException: Missing required tags: ResourceKey[minecraft:root / minecraft:fluid]:forge:superheated_sodium
	at net.minecraft.tags.TagManager.m_144592_(TagManager.java:58) ~[client-1.18.1-20211210.034407-srg.jar%23149!:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:71) ~[client-1.18.1-20211210.034407-srg.jar%23149!:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[client-1.18.1-20211210.034407-srg.jar%23149!:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.1-20211210.034407-srg.jar%23149!:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[client-1.18.1-20211210.034407-srg.jar%23149!:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[client-1.18.1-20211210.034407-srg.jar%23149!:?]
	at net.minecraft.client.Minecraft.m_91190_(Minecraft.java:2070) ~[client-1.18.1-20211210.034407-srg.jar%23149!:?]
	... 46 more
```
</details>

### Steps to reproduce

1. Git clone, and build the latest version of Mekanism for 1.18.x
2. Place the built files into a modpack with BiggerReactors, and RSGauges.
3. Create or load a world, error here.

### Minecraft version

1.18.1 (Manually Compiled)

### Forge version

39.0.36

### Mekanism version

Current Dev Branch (Manually Compiled)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://i.skystuff.games/paste/6T3uyL0lDSZ8.txt

**Comment by Seniorendi** [comment]
had the same issue at the time I tested it
But I just ignored it

**Comment by pupnewfster** [comment]
Support is not really being given yet for 1.18, plus the tag is most definitely there: https://github.com/mekanism/Mekanism/blob/1.18.x/src/datagen/generated/mekanism/data/forge/tags/fluids/superheated_sodium.json But either way looks like biggerreactors is adding elements to the given tag that it doesn't actually add to the game?
