### ISSUE TITLE
java.lang.IllegalStateException: Failed to load description for particle mekanism:laser

### ISSUE THREAD

**Issue by voidwyrm-2** [mekanism/Mekanism#7534]
### Issue description

it is telling me it can't find the discription of the mekanism laser particle(java.io.FileNotFoundException: mekanism:particles/laser.json + java.lang.IllegalStateException: Failed to load description for particle mekanism:laser);  I don't know why this is happening, I assume it's a either a missing file or minecraft/forge misreading a file. Sorry for the lack of information.

### Minecraft version

1.18.2 (Latest)

### Forge version

40.1.27

### Mekanism version

10.2.4 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/voidwyrm-2/00bb59b0ec61e86344b2efe54b877af5#file-mekanismcrashreport-txt

**Comment by pupnewfster** [comment]
Could you please provide your latest log? I have a suspicion there might be an exception earlier in it that caused an invalid state or something

**Comment by voidwyrm-2** [comment]
I gave a link to a Gitgist

**Comment by voidwyrm-2** [comment]
Which has my latest log

**Comment by pupnewfster** [comment]
No, that has your (I presume latest) crash report not your latest log

**Comment by voidwyrm-2** [comment]
```
[30Jun2022 20:43:22.318] [Worker-Main-4/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[30Jun2022 20:43:22.322] [Worker-Main-9/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[30Jun2022 20:43:23.918] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Reported exception thrown!
net.minecraft.ReportedException: Rendering overlay
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:886) ~[client-1.18.2-20220404.173914-srg.jar%2395!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1044) ~[client-1.18.2-20220404.173914-srg.jar%2395!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%2395!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2395!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.27.jar%2316!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
Caused by: java.lang.IllegalStateException: Failed to load description for particle mekanism:laser
	at net.minecraft.client.particle.ParticleEngine.m_107316_(ParticleEngine.java:278) ~[client-1.18.2-20220404.173914-srg.jar%2395!/:?]
	at net.minecraft.client.particle.ParticleEngine.m_172284_(ParticleEngine.java:192) ~[client-1.18.2-20220404.173914-srg.jar%2395!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.io.FileNotFoundException: mekanism:particles/laser.json
	at net.minecraft.server.packs.resources.MultiPackResourceManager.m_142591_(MultiPackResourceManager.java:50) ~[client-1.18.2-20220404.173914-srg.jar%2395!/:?]
	at net.minecraft.client.particle.ParticleEngine.m_107316_(ParticleEngine.java:228) ~[client-1.18.2-20220404.173914-srg.jar%2395!/:?]
	at net.minecraft.client.particle.ParticleEngine.m_172284_(ParticleEngine.java:192) ~[client-1.18.2-20220404.173914-srg.jar%2395!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
[30Jun2022 20:43:23.961] [Render thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 36c37fb6-3adf-41ef-86fb-cb5162dc22fc
[30Jun2022 20:43:23.969] [Render thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 4cb42954-9cbe-464c-9399-a078221532c7
```

**Comment by voidwyrm-2** [comment]
is this it?

**Comment by voidwyrm-2** [comment]
do you want the full log?

**Comment by pupnewfster** [comment]
Yes I want the full log hence why I asked for the latest log... it is a file called `latest` with extension `log` in your logs folder

**Comment by voidwyrm-2** [comment]
I tried to attach the log to this comment but it says the file size is to big

**Comment by pupnewfster** [comment]
Then copy paste it into a gist?

**Comment by voidwyrm-2** [comment]
I got a unicorn(This page is taking too long to load. Sorry about that. Please try refreshing and contact us if the problem persists.) when I try to save the gist.

**Comment by voidwyrm-2** [comment]
ah, yes thermal series has been giving me trouble before, thank you
