### ISSUE TITLE
Crash when loading

### ISSUE THREAD

**Issue by pepdron** [mekanism/Mekanism#7711]
### Issue description

so basiccly want to play minecraft mekansim in my folder for mods is only mekanism and when i try to load in it crash while im loading 

versions:  Mekanism-1.7.10-9.1.1.1031.jar
                1.7.10-Forge10.13.4.1614-1.7.10

error code: -1

---- Minecraft Crash Report ----
// My bad.

Time: 21.1.23 19:18
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: codechicken/multipart/BlockMultipart
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: codechicken/multipart/BlockMultipart
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:440)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	... 10 more
Caused by: java.lang.ClassNotFoundException: codechicken.multipart.BlockMultipart
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 35 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 37 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 182228432 bytes (173 MB) / 536870912 bytes (512 MB) up to 10737418240 bytes (10240 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UC	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UE	Mekanism{9.1.1} [Mekanism] (Mekanism-1.7.10-9.1.1.1031.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 528.02' Renderer: 'NVIDIA GeForce RTX 4070 Ti/PCIe/SSE2'

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

1.7.10-Forge10.13.4.1614-1.7.10

### Mekanism version

Older

**Comment by pupnewfster** [comment]
The 1.7.10 version requires that you install forge multipart https://www.curseforge.com/minecraft/mc-mods/forge-multi-part. You may need to delete an existing version if there is one from your mods folder (and also from the folder that is created inside the mods folder) as they may be outdated.

**Comment by pepdron** [comment]
so it didnt work
1. i got rid of the mekanism
2. started minecraft without mods
3. put in the 2 mods (mekanism, forge mulit part)
4. started it
5. crash again while loading in same load data 2/7

**Comment by pepdron** [comment]
> The 1.7.10 version requires that you install forge multipart https://www.curseforge.com/minecraft/mc-mods/forge-multi-part. You may need to delete an existing version if there is one from your mods folder (and also from the folder that is created inside the mods folder) as they may be outdated.

so it didnt work

1. i got rid of the mekanism
2. started minecraft without mods (it started)
3. shut it down 
4. put in the 2 mods (mekanism, forge mulit part)
5. started it
6. crash again while loading in same load data 2/7

**Comment by pupnewfster** [comment]
I never said to remove mekanism, I said to remove any existing version of forge multipart from two different potential folder locations.

**Comment by pepdron** [comment]
> I never said to remove mekanism, I said to remove any existing version of forge multipart from two different potential folder locations.
but i puted it in again

**Comment by pupnewfster** [comment]
My point is you never specified/confirmed that you actually removed any existing versions of forge multipart from either of the two folders I mentioned it may be in

**Comment by pepdron** [comment]
> My point is you never specified/confirmed that you actually removed any existing versions of forge multipart from either of the two folders I mentioned it may be in

so again 
i removed all mods started it it worked without mods on forge
then i puted in mekanism and the forge multi part
and then started it and it crashed while loading

**Comment by pupnewfster** [comment]
Is it the same error as before? Or is it different and just crashing due to not installing any dependencies that forge multipart has and lists
