### ISSUE TITLE
Digital miner crashing servers

### ISSUE THREAD

**Issue by dave8898** [mekanism/Mekanism#7736]
### Issue description

In the crash reports it says that the miner is the cause for a ticking entity which causes the crash

here is the text

---- Minecraft Crash Report ----
// But it works on my machine.

Time: 2023-02-18 14:45:59
Description: Ticking block entity

java.lang.IllegalArgumentException: duplicate element: [30, -54]
	at java.util.ImmutableCollections$Set12.<init>(ImmutableCollections.java:791) ~[?:?] {}
	at java.util.Set.of(Set.java:487) ~[?:?] {re:computing_frames,re:mixin}
	at mekanism.common.tile.machine.TileEntityDigitalMiner.getChunkSet(TileEntityDigitalMiner.java:1029) ~[Mekanism-1.19.2-10.3.7.476.jar%23166!/:10.3.7] {re:classloading}
	at mekanism.common.tile.component.TileComponentChunkLoader.getTileChunks(TileComponentChunkLoader.java:220) ~[Mekanism-1.19.2-10.3.7.476.jar%23166!/:10.3.7] {re:classloading}
	at mekanism.common.tile.component.TileComponentChunkLoader.refreshChunkTickets(TileComponentChunkLoader.java:130) ~[Mekanism-1.19.2-10.3.7.476.jar%23166!/:10.3.7] {re:classloading}
	at mekanism.common.tile.component.TileComponentChunkLoader.refreshChunkTickets(TileComponentChunkLoader.java:96) ~[Mekanism-1.19.2-10.3.7.476.jar%23166!/:10.3.7] {re:classloading}
	at mekanism.common.tile.machine.TileEntityDigitalMiner.updateTargetChunk(TileEntityDigitalMiner.java:1012) ~[Mekanism-1.19.2-10.3.7.476.jar%23166!/:10.3.7] {re:classloading}
	at mekanism.common.tile.machine.TileEntityDigitalMiner.tryMineBlock(TileEntityDigitalMiner.java:438) ~[Mekanism-1.19.2-10.3.7.476.jar%23166!/:10.3.7] {re:classloading}
	at mekanism.common.tile.machine.TileEntityDigitalMiner.onUpdateServer(TileEntityDigitalMiner.java:229) ~[Mekanism-1.19.2-10.3.7.476.jar%23166!/:10.3.7] {re:classloading}
	at mekanism.common.tile.base.TileEntityMekanism.tickServer(TileEntityMekanism.java:574) ~[Mekanism-1.19.2-10.3.7.476.jar%23166!/:10.3.7] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[server-1.19.2-20220805.130853-srg.jar%23183!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[server-1.19.2-20220805.130853-srg.jar%23183!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:446) ~[server-1.19.2-20220805.130853-srg.jar%23183!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel,pl:mixin:APP:enhancedcelestials.mixins.json:MixinWorld,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[server-1.19.2-20220805.130853-srg.jar%23183!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:corgilib.mixins.json:MixinServerLevel,pl:mixin:APP:zombieawareness.mixins.json:MixinPlaySound,pl:mixin:APP:zombieawareness.mixins.json:MixinLevelEvent,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[server-1.19.2-20220805.130853-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.ImmutableCollections$Set12.<init>(ImmutableCollections.java:791) ~[?:?] {}
	at java.util.Set.of(Set.java:487) ~[?:?] {re:computing_frames,re:mixin}
	at mekanism.common.tile.machine.TileEntityDigitalMiner.getChunkSet(TileEntityDigitalMiner.java:1029) ~[Mekanism-1.19.2-10.3.7.476.jar%23166!/:10.3.7] {re:classloading}
	at mekanism.common.tile.component.TileComponentChunkLoader.getTileChunks(TileComponentChunkLoader.java:220) ~[Mekanism-1.19.2-10.3.7.476.jar%23166!/:10.3.7] {re:classloading}
	at mekanism.common.tile.component.TileComponentChunkLoader.refreshChunkTickets(TileComponentChunkLoader.java:130) ~[Mekanism-1.19.2-10.3.7.476.jar%23166!/:10.3.7] {re:classloading}
	at mekanism.common.tile.component.TileComponentChunkLoader.refreshChunkTickets(TileComponentChunkLoader.java:96) ~[Mekanism-1.19.2-10.3.7.476.jar%23166!/:10.3.7] {re:classloading}
	at mekanism.common.tile.machine.TileEntityDigitalMiner.updateTargetChunk(TileEntityDigitalMiner.java:1012) ~[Mekanism-1.19.2-10.3.7.476.jar%23166!/:10.3.7] {re:classloading}
	at mekanism.common.tile.machine.TileEntityDigitalMiner.tryMineBlock(TileEntityDigitalMiner.java:438) ~[Mekanism-1.19.2-10.3.7.476.jar%23166!/:10.3.7] {re:classloading}
	at mekanism.common.tile.machine.TileEntityDigitalMiner.onUpdateServer(TileEntityDigitalMiner.java:229) ~[Mekanism-1.19.2-10.3.7.476.jar%23166!/:10.3.7] {re:classloading}
	at mekanism.common.tile.base.TileEntityMekanism.tickServer(TileEntityMekanism.java:574) ~[Mekanism-1.19.2-10.3.7.476.jar%23166!/:10.3.7] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[server-1.19.2-20220805.130853-srg.jar%23183!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[server-1.19.2-20220805.130853-srg.jar%23183!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:446) ~[server-1.19.2-20220805.130853-srg.jar%23183!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel,pl:mixin:APP:enhancedcelestials.mixins.json:MixinWorld,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[server-1.19.2-20220805.130853-srg.jar%23183!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:corgilib.mixins.json:MixinServerLevel,pl:mixin:APP:zombieawareness.mixins.json:MixinPlaySound,pl:mixin:APP:zombieawareness.mixins.json:MixinLevelEvent,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
-- Block entity being ticked --
Details:
	Name: mekanism:digital_miner // mekanism.common.tile.machine.TileEntityDigitalMiner
	Block: Block{mekanism:digital_miner}[active=true,facing=east,fluid_logged=empty]
	Block location: World: (494,250,-859), Section: (at 14,10,5 in 30,15,-54; chunk contains blocks 480,-64,-864 to 495,319,-849), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,-64,-1024 to 511,319,-513)
	Block: Block{mekanism:digital_miner}[active=true,facing=east,fluid_logged=empty]
	Block location: World: (494,250,-859), Section: (at 14,10,5 in 30,15,-54; chunk contains blocks 480,-64,-864 to 495,319,-849), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,-64,-1024 to 511,319,-513)
Stacktrace:
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[server-1.19.2-20220805.130853-srg.jar%23183!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[server-1.19.2-20220805.130853-srg.jar%23183!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:446) ~[server-1.19.2-20220805.130853-srg.jar%23183!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel,pl:mixin:APP:enhancedcelestials.mixins.json:MixinWorld,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[server-1.19.2-20220805.130853-srg.jar%23183!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:corgilib.mixins.json:MixinServerLevel,pl:mixin:APP:zombieawareness.mixins.json:MixinPlaySound,pl:mixin:APP:zombieawareness.mixins.json:MixinLevelEvent,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[server-1.19.2-20220805.130853-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

-- Affected level --
Details:
	All players: 3 total; [ServerPlayer['DogeKingYT'/159492, l='ServerLevel[Zombies city]', x=510.73, y=68.00, z=-851.91], ServerPlayer['Agent_GoodBoi'/151223, l='ServerLevel[Zombies city]', x=6893.63, y=273.00, z=9528.32], ServerPlayer['M8seMilk'/124749, l='ServerLevel[Zombies city]', x=6890.47, y=272.00, z=9546.19]]
	Chunk stats: 7060
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,74,32), Section: (at 0,10,0 in 0,4,2; chunk contains blocks 0,-64,32 to 15,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 16416673 game time, 1651311 day time
	Level name: Zombies city
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 611 (now: false), thunder time: 14132 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[server-1.19.2-20220805.130853-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23183!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 3.10.0-1160.36.2.el7.x86_64
	Java Version: 17.0.6, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 3144394944 bytes (2998 MiB) / 5582618624 bytes (5324 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 2
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 4.20
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 45334.53
	Virtual memory used (MB): 53107.22
	Swap memory total (MB): 13309.99
	Swap memory used (MB): 895.42
	JVM Flags: 3 total; -XX:ActiveProcessorCount=2 -Xmx8192M -Xms5324M
	Server Running: true
	Player Count: 3 / 69420; [ServerPlayer['DogeKingYT'/159492, l='ServerLevel[Zombies city]', x=510.73, y=68.00, z=-851.91], ServerPlayer['Agent_GoodBoi'/151223, l='ServerLevel[Zombies city]', x=6893.63, y=273.00, z=9528.32], ServerPlayer['M8seMilk'/124749, l='ServerLevel[Zombies city]', x=6890.47, y=272.00, z=9546.19]]
	Data Packs: vanilla, mod:tenshilib (incompatible), mod:farmersdelight (incompatible), mod:terrablender, mod:swingthroughgrass (incompatible), mod:cgm (incompatible), mod:projectvibrantjourneys (incompatible), mod:creativecore (incompatible), mod:mcwfences, mod:jei (incompatible), mod:spectrelib (incompatible), mod:incontrol (incompatible), mod:mekanism, mod:car (incompatible), mod:flywheel (incompatible), mod:ecologics (incompatible), mod:create, mod:xaerominimap, mod:comforts, mod:sereneseasons, mod:zombieawareness (incompatible), mod:toughasnails (incompatible), mod:additionalguns, mod:lostcities (incompatible), mod:badmobs (incompatible), mod:farsightedmobs (incompatible), mod:coroutil (incompatible), mod:mekanismtools, mod:simpleplanes (incompatible), mod:blood_and_gore, mod:mekanismgenerators, mod:enhancedcelestials (incompatible), mod:corgilib (incompatible), mod:framework (incompatible), mod:fallingtree, mod:firstaid (incompatible), mod:cloth_config (incompatible), mod:sound_physics_remastered (incompatible), mod:forge, mod:improvedmobs (incompatible), mod:geckolib3 (incompatible), mod:presencefootsteps, mod:travelersbackpack
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.2.4.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.4.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.2.4.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.2.4.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.4.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		server-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |DONE      |Manifest: NOSIGNATURE
		tenshilib-1.19-1.6.14-forge.jar                   |TenshiLib                     |tenshilib                     |1.19-1.6.14         |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.19-1.2.0.jar                     |Farmer's Delight              |farmersdelight                |1.19-1.2.0          |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.19.2-2.0.1.136.jar           |TerraBlender                  |terrablender                  |2.0.1.136           |DONE      |Manifest: NOSIGNATURE
		swingthroughgrass-1.19.2-1.10.0.jar               |SwingThroughGrass             |swingthroughgrass             |1.19.2-1.10.0       |DONE      |Manifest: NOSIGNATURE
		cgm-1.3.3-1.19.2.jar                              |MrCrayfish's Gun Mod          |cgm                           |1.3.3               |DONE      |Manifest: NOSIGNATURE
		projectvibrantjourneys-1.19.2-5.1.0.jar           |Project Vibrant Journeys      |projectvibrantjourneys        |1.19.2-5.1.0        |DONE      |Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.9.3_mc1.19.2.jar            |CreativeCore                  |creativecore                  |2.9.3               |DONE      |Manifest: NOSIGNATURE
		mcw-fences-1.0.7-mc1.19.2forge.jar                |Macaw's Fences and Walls      |mcwfences                     |1.0.7               |DONE      |Manifest: NOSIGNATURE
		jei-1.19.2-forge-11.5.2.1007.jar                  |Just Enough Items             |jei                           |11.5.2.1007         |DONE      |Manifest: NOSIGNATURE
		spectrelib-forge-0.10.0+1.19.jar                  |SpectreLib                    |spectrelib                    |0.10.0+1.19         |DONE      |Manifest: NOSIGNATURE
		incontrol-1.19-7.1.2.jar                          |InControl                     |incontrol                     |1.19-7.1.2          |DONE      |Manifest: NOSIGNATURE
		Mekanism-1.19.2-10.3.7.476.jar                    |Mekanism                      |mekanism                      |10.3.7              |DONE      |Manifest: NOSIGNATURE
		car-1.19.2-1.0.0 (1).jar                          |Ultimate Car Mod              |car                           |1.19.2-1.0.0        |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.19.2-0.6.8.a-14.jar              |Flywheel                      |flywheel                      |0.6.8.a-14          |DONE      |Manifest: NOSIGNATURE
		ecologics-forge-1.19.2-2.1.11.jar                 |Ecologics                     |ecologics                     |2.1.11              |DONE      |Manifest: NOSIGNATURE
		create-1.19.2-0.5.0.i.jar                         |Create                        |create                        |0.5.0.i             |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_22.17.1_Forge_1.19.1.jar           |Xaero's Minimap               |xaerominimap                  |22.17.1             |DONE      |Manifest: NOSIGNATURE
		comforts-forge-6.0.3+1.19.2.jar                   |Comforts                      |comforts                      |6.0.3+1.19.2        |DONE      |Manifest: NOSIGNATURE
		TravelersBackpack-1.19.2-8.2.13.jar               |Traveler's Backpack           |travelersbackpack             |8.2.13              |DONE      |Manifest: NOSIGNATURE
		SereneSeasons-1.19.2-8.1.0.24.jar                 |Serene Seasons                |sereneseasons                 |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		zombieawareness-1.19.2-1.12.3.jar                 |Zombie Awareness              |zombieawareness               |1.19.2-1.12.3       |DONE      |Manifest: NOSIGNATURE
		ToughAsNails-1.19-8.0.0.78.jar                    |Tough As Nails                |toughasnails                  |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		additional-guns-0.8.2-1.19.2.jar                  |Additional Guns               |additionalguns                |0.8.2               |DONE      |Manifest: NOSIGNATURE
		lostcities-1.19-6.0.12.jar                        |LostCities                    |lostcities                    |1.19-6.0.12         |DONE      |Manifest: NOSIGNATURE
		BadMobs-1.19.2-16.1.2.jar                         |BadMobs                       |badmobs                       |16.1.2              |DONE      |Manifest: NOSIGNATURE
		farsighted-mobs-forge-1.1-1.19.jar                |Farsighted Mobs               |farsightedmobs                |1.1                 |DONE      |Manifest: NOSIGNATURE
		coroutil-1.19.2-1.2.37.jar                        |CoroUtil                      |coroutil                      |1.19.2-1.2.37       |DONE      |Manifest: NOSIGNATURE
		MekanismTools-1.19.2-10.3.7.476.jar               |Mekanism: Tools               |mekanismtools                 |10.3.7              |DONE      |Manifest: NOSIGNATURE
		simpleplanes-1.19.2-5.2.1 (1).jar                 |Simple Planes                 |simpleplanes                  |1.19.2-5.2.1        |DONE      |Manifest: NOSIGNATURE
		bloodandgore1.19.2v1.1(beta).jar                  |Blood and Gore                |blood_and_gore                |1.0.0               |DONE      |Manifest: NOSIGNATURE
		MekanismGenerators-1.19.2-10.3.7.476.jar          |Mekanism: Generators          |mekanismgenerators            |10.3.7              |DONE      |Manifest: NOSIGNATURE
		Enhanced_Celestials-forge-1.19.2-2.1.0.2.jar      |Enhanced Celestials           |enhancedcelestials            |2.1.0.2             |DONE      |Manifest: NOSIGNATURE
		CorgiLib-forge-1.19.2-1.0.0.21.jar                |CorgiLib                      |corgilib                      |1.0.0.21            |DONE      |Manifest: NOSIGNATURE
		framework-0.4.2-1.19.2.jar                        |Framework                     |framework                     |0.4.2               |DONE      |Manifest: NOSIGNATURE
		FallingTree-1.19.2-3.10.0.jar                     |FallingTree                   |fallingtree                   |3.10.0              |DONE      |Manifest: 3c:8e:df:6c:df:a6:2a:9f:af:64:ea:04:9a:cf:65:92:3b:54:93:0e:96:50:b4:52:e1:13:42:18:2b:ae:40:29
		firstaid-1.12.0.jar                               |First Aid                     |firstaid                      |1.12.0              |DONE      |Manifest: NOSIGNATURE
		cloth-config-8.2.88-forge (1).jar                 |Cloth Config v8 API           |cloth_config                  |8.2.88              |DONE      |Manifest: NOSIGNATURE
		soundphysics-forge-1.19.2-1.0.18.jar              |Sound Physics Remastered      |sound_physics_remastered      |1.19.2-1.0.18       |DONE      |Manifest: NOSIGNATURE
		forge-1.19.2-43.2.4-universal.jar                 |Forge                         |forge                         |43.2.4              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		improvedmobs-1.19-1.11.0-forge (1).jar            |Improved Mobs Mod             |improvedmobs                  |1.19-1.11.0         |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.19-3.1.39.jar                    |GeckoLib                      |geckolib3                     |3.1.39              |DONE      |Manifest: NOSIGNATURE
		PresenceFootsteps-1.19.2-1.6.4-forge.jar          |Presence Footsteps (Forge)    |presencefootsteps             |1.19.2-1.6.4        |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 9aa1f5ce-1536-4376-a0e6-3da1269bd557
	FML: 43.2
	Forge: net.minecraftforge:43.2.4

### Minecraft version

1.19.2 (Latest)

### Forge version

1.19.2

### Mekanism version

10.3.7

**Comment by UnknownSerhan** [comment]
Update to 10.3.8
