### ISSUE TITLE
Transmitter saving logs errors relating to stack size changing by wrong amount

### ISSUE THREAD

**Issue by sprocketaudio** [mekanism/Mekanism#7741]
### Issue description

I run a restart command every 4 hours on our multiplayer server which has max 10 people playing at a time and 30-40 daily (and has had a lot of people come and go) - last wipe was about 1 month ago. Before the last wipe, and now again with this current world, we see a mekanim crash everytime the auto server restart fires. When it does this, it then fails to restart until we manually kill the process. 

[20Feb2023 13:00:05.552] [Server thread/ERROR] [mekanism.common.Mekanism/]: Stack size changed by a different amount (18561) than requested (110097).
java.lang.Exception: null
	at mekanism.common.util.MekanismUtils.logMismatchedStackSize(MekanismUtils.java:123) ~[Mekanism-1.19.2-10.3.5.473.jar%23604!/:10.3.5]
	
Full crash server log included (doest create a crash log). - Starts at timestamp - [20Feb2023 13:00:02.603]

[2023-02-20-8.log](https://github.com/mekanism/Mekanism/files/10792075/2023-02-20-8.log)

### Steps to reproduce

Start server.
Wait until server resstart 4 hours later.
Mek crashes when it tried to shutdown.

### Minecraft version

1.19.2 (Latest)

### Forge version

42.2.3

### Mekanism version

10.3.5

**Comment by atlgeek007** [comment]
I am also receiving this issue when my server stops.

**Comment by pupnewfster** [comment]
Sorry for it taking a bit of time to actually get a chance to look into this closer but I think the issue with the server not stopping properly actually is related to this:
```
Caused by: java.lang.RuntimeException: Cable added to position BlockPos{x=12067, y=51, z=11232}, but there was already one there?
	at TRANSFORMER/powah@4.0.6/owmii.powah.block.cable.CableNet.addCable(CableNet.java:24)
```

Where powah is having an error that causes the chunk to fail to save and I am guessing server shutdown to break. Though I am going to look into this a bit further to see if I can track down the cause of the errors that mek is logging relating to saving transmitter contents and their quantities.

**Comment by nvrsbr** [comment]
Getting this error spamming console.

**[mekanism.common.Mekanism/]: Energy value changed by a different amount (2.1720) than requested (zero).**
