### ISSUE TITLE
[Crush][1.19.2] Client crushes when rendering a bucket of hydrogen in inventory

### ISSUE THREAD

**Issue by LisMorozniy** [mekanism/Mekanism#7755]
### Issue description

Client crushes when rendering a bucket of hydrogen(maybe other buckets of gases too) in inventory. Issue seems to not be related to JEI or OptiFine(deleted both, issue stays)

### Steps to reproduce

1. Load to the world
2. Try to see a bucket of hydrogen in inventory or in JEI tab

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.4

### Mekanism version

10.3.8 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/d3KFgjAf

**Comment by Jorue23** [comment]
can you send a crash log without optifine installed?

**Comment by Jorue23** [comment]
How did you get that bucket of hydrogen? Isn't it impossible to put a gas into a bucket?

**Comment by LisMorozniy** [comment]
Crush without optifine. 
https://pastebin.com/y6RngZgx
I think it is bucket of liquid hydrogen, but it is called just "bucket of hydrogen"

**Comment by LisMorozniy** [comment]
I didn't "get" it, I just search for "bucket" in creative search or in JEI and it crashes. Crash from JEI tab highlighted that it was bucket of hydrogen causing the crash. Here is the crash on JEI tab.
https://pastebin.com/qq8bWMtm

**Comment by pupnewfster** [comment]
Can you please provide your latest log as well as my suspicion is something is going on way earlier than when the crash actually happens so there is likely some useful details in the latest log that are missing from the crash report.

**Comment by LisMorozniy** [comment]
[01:23:21] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.ReportedException: Rendering screen
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:909) ~[client-1.19.2-20220805.130853-srg.jar%23423!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23423!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23423!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23423!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23423!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.4.jar%2395!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:64) ~[forge-1.19.2-43.2.4-universal.jar%23428!/:?]
	at net.minecraftforge.fluids.capability.wrappers.FluidBucketWrapper.getFluid(FluidBucketWrapper.java:66) ~[forge-1.19.2-43.2.4-universal.jar%23428!/:?]
	at net.minecraftforge.fluids.capability.wrappers.FluidBucketWrapper.drain(FluidBucketWrapper.java:158) ~[forge-1.19.2-43.2.4-universal.jar%23428!/:?]
	at net.minecraftforge.fluids.FluidUtil.lambda$getFluidContained$4(FluidUtil.java:436) ~[forge-1.19.2-43.2.4-universal.jar%23428!/:?]
	at net.minecraftforge.common.util.LazyOptional.map(LazyOptional.java:195) ~[forge-1.19.2-43.2.4-universal.jar%23428!/:?]
	at net.minecraftforge.fluids.FluidUtil.getFluidContained(FluidUtil.java:436) ~[forge-1.19.2-43.2.4-universal.jar%23428!/:?]
	at net.minecraftforge.client.model.DynamicFluidContainerModel$ContainedFluidOverrideHandler.m_173464_(DynamicFluidContainerModel.java:272) ~[forge-1.19.2-43.2.4-universal.jar%23428!/:?]
	at net.minecraft.client.renderer.entity.ItemRenderer.m_174264_(ItemRenderer.java:220) ~[client-1.19.2-20220805.130853-srg.jar%23423!/:?]
	at net.minecraft.client.renderer.entity.ItemRenderer.m_174235_(ItemRenderer.java:296) ~[client-1.19.2-20220805.130853-srg.jar%23423!/:?]
	at net.minecraft.client.renderer.entity.ItemRenderer.m_174277_(ItemRenderer.java:291) ~[client-1.19.2-20220805.130853-srg.jar%23423!/:?]
	at net.minecraft.client.renderer.entity.ItemRenderer.m_174229_(ItemRenderer.java:287) ~[client-1.19.2-20220805.130853-srg.jar%23423!/:?]
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_97799_(AbstractContainerScreen.java:248) ~[client-1.19.2-20220805.130853-srg.jar%23423!/:?]
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_6305_(AbstractContainerScreen.java:108) ~[client-1.19.2-20220805.130853-srg.jar%23423!/:?]
	at net.minecraft.client.gui.screens.inventory.EffectRenderingInventoryScreen.m_6305_(EffectRenderingInventoryScreen.java:28) ~[client-1.19.2-20220805.130853-srg.jar%23423!/:?]
	at net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen.m_6305_(CreativeModeInventoryScreen.java:605) ~[client-1.19.2-20220805.130853-srg.jar%23423!/:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:440) ~[forge-1.19.2-43.2.4-universal.jar%23428!/:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:433) ~[forge-1.19.2-43.2.4-universal.jar%23428!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:896) ~[client-1.19.2-20220805.130853-srg.jar%23423!/:?]
	... 17 more
[01:23:21] [Render thread/FATAL]: Preparing crash report with UUID 15408416-dd51-49b4-9a14-0e8fabff60c0
[01:23:21] [Render thread/FATAL]: Preparing crash report with UUID cd49805e-9abe-4669-b67a-b2a566f796c4

**Comment by LisMorozniy** [comment]
UPD: Issue only occurs when dynamic crosshair mod is installed with mekanism. When mekanism is off everything fine and vice versa.
New crush report: https://pastebin.com/pRQwDCsL
latest log: https://pastebin.com/wq6QFLpN

**Comment by pupnewfster** [comment]
Guessing it should be fixed by [this change](https://github.com/Crendgrim/DynamicCrosshair/commit/bfee8c5b54e37cad1e75f50c55c43039e99c9c8c) of theirs so guessing you need to update that mod or wait for them to release an update
