### ISSUE TITLE
Crash during contact with laser

### ISSUE THREAD

**Issue by Diemoerm** [mekanism/Mekanism#7823]
### Issue description

[17:41:58] [Server thread/INFO]: [Diemo_mustard: �ѽ��Լ�����Ϸģʽ����Ϊ����ģʽ]
[17:41:58] [Render thread/INFO]: [System] [CHAT] �ѽ��Լ�����Ϸģʽ����Ϊ����ģʽ
[17:41:58] [Server thread/ERROR]: Exception caught during firing event: Cannot invoke "net.minecraftforge.common.capabilities.Capability.isRegistered()" because "capability" is null
	Index: 3
	Listeners:
		0: HIGHEST
		1: ASM: class dev.xkmc.l2library.init.events.attack.AttackEventHandler onActuallyHurtPre(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		2: net.minecraftforge.eventbus.EventBus$$Lambda$1502/0x0000000801320000@aa8ea35
		3: ASM: class jackiecrazy.footwork.handler.EntityHandler pain(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		4: HIGH
		5: ASM: class cofh.core.event.ArcheryEvents handleLivingHurtEvent(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		6: NORMAL
		7: ASM: class mods.thecomputerizer.musictriggers.server.ServerEvents livingDamage(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		8: ASM: class net.mcreator.unusualend.procedures.WitherOrbHitProcedure onEntityAttacked(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		9: ASM: class net.mcreator.unusualend.procedures.UltraInstinctChorusProcedure onEntityAttacked(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		10: ASM: class net.mcreator.unusualend.procedures.GolemOrbUseProcedure onEntityAttacked(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		11: ASM: class net.mcreator.unusualend.procedures.FireflyInstakillProcedure onEntityAttacked(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		12: ASM: class net.mcreator.unusualend.procedures.EndermitesInfectProcedure onEntityAttacked(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		13: ASM: class net.mcreator.unusualend.procedures.EnderlingTpProcedure onEntityAttacked(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		14: ASM: class net.mcreator.unusualend.procedures.CooldownEndstoneGolemProcedure onEntityAttacked(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		15: ASM: class net.mcreator.unusualend.procedures.BolokFuryProcedure onEntityAttacked(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		16: ASM: class com.rosemods.windswept.core.other.events.WindsweptEntityEvents onEntityHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		17: ASM: class net.thirdlife.iterrpg.procedures.MeleeDamageIncreaseProcedure hurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		18: ASM: class com.tiviacz.pizzacraft.items.KnifeItem$KnifeEvents onKnifeBackstab(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		19: ASM: net.orcinus.galosphere.events.MobEvents@52156a3a onLivingDamage(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		20: ASM: class vectorwing.farmersdelight.common.item.enchantment.BackstabbingEnchantment$BackstabbingEvent onKnifeBackstab(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		21: ASM: se.mickelus.tetra.effect.ItemEffectHandler@7335aaa onLivingHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		22: ASM: com.github.L_Ender.cataclysm.event.ServerEventHandler@46c4b1e onLivingDamage(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		23: ASM: class dev.xkmc.twilightdelight.events.GeneralEventHandlers onKnightmetalToolDamage(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		24: net.minecraftforge.eventbus.EventBus$$Lambda$1502/0x0000000801320000@67b843a6
		25: net.minecraftforge.eventbus.EventBus$$Lambda$1502/0x0000000801320000@77704073
		26: ASM: class com.hollingsworth.arsnouveau.common.potions.GravityEffect entityHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		27: ASM: class com.hollingsworth.arsnouveau.common.event.ReactiveEvents livingHitEvent(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		28: ASM: class com.hollingsworth.arsnouveau.common.event.FamiliarEvents livingHurtEvent(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		29: ASM: class com.hollingsworth.arsnouveau.common.event.EventHandler entityHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		30: ASM: class com.hollingsworth.arsnouveau.common.event.EventHandler livingHurtEvent(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		31: ASM: class com.hollingsworth.arsnouveau.common.camera.CameraEvents onDamageTaken(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		32: ASM: class twilightforest.events.ToolEvents onKnightmetalToolDamage(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		33: ASM: class twilightforest.events.ToolEvents onMinotaurAxeCharge(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		34: ASM: class com.teamabnormals.atmospheric.core.other.AtmosphericEvents livingHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		35: ASM: class twilightforest.events.EntityEvents entityHurts(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		36: ASM: class com.brutalbosses.event.EventHandler applyProjectileDamageBoost(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		37: net.minecraftforge.eventbus.EventBus$$Lambda$1502/0x0000000801320000@2f681c9c
		38: net.minecraftforge.eventbus.EventBus$$Lambda$1502/0x0000000801320000@62dcb206
		39: net.minecraftforge.eventbus.EventBus$$Lambda$1502/0x0000000801320000@475c7888
		40: ASM: mekanism.common.CommonPlayerTickHandler@12c297b1 onLivingHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		41: net.minecraftforge.eventbus.EventBus$$Lambda$1502/0x0000000801320000@32dacbc8
		42: net.minecraftforge.eventbus.EventBus$$Lambda$1502/0x0000000801320000@5db9bdf3
		43: net.minecraftforge.eventbus.EventBus$$Lambda$1502/0x0000000801320000@5af268c0
		44: LOWEST
		45: ASM: class dev.xkmc.l2library.init.events.attack.AttackEventHandler onActuallyHurtPost(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
java.lang.NullPointerException: Cannot invoke "net.minecraftforge.common.capabilities.Capability.isRegistered()" because "capability" is null
	at TRANSFORMER/mekanism@10.3.8/mekanism.common.capabilities.ItemCapabilityWrapper.getCapability(ItemCapabilityWrapper.java:43)
	at TRANSFORMER/forge@43.2.14/net.minecraftforge.common.capabilities.CapabilityDispatcher.getCapability(CapabilityDispatcher.java:89)
	at TRANSFORMER/forge@43.2.14/net.minecraftforge.common.capabilities.CapabilityProvider.getCapability(CapabilityProvider.java:183)
	at TRANSFORMER/forge@43.2.14/net.minecraftforge.common.capabilities.ICapabilityProvider.getCapability(ICapabilityProvider.java:33)
	at TRANSFORMER/footwork@2.6/jackiecrazy.footwork.handler.EntityHandler.pain(EntityHandler.java:106)
	at TRANSFORMER/footwork@2.6/jackiecrazy.footwork.handler.__EntityHandler_pain_LivingHurtEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@43.2.14/net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:343)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.player.Player.m_6475_(Player.java:927)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.LivingEntity.m_6469_(LivingEntity.java:1073)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.player.Player.m_6469_(Player.java:862)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerPlayer.m_6469_(ServerPlayer.java:671)
	at TRANSFORMER/mekanism@10.3.8/mekanism.common.tile.laser.TileEntityBasicLaser.onUpdateServer(TileEntityBasicLaser.java:236)
	at TRANSFORMER/mekanism@10.3.8/mekanism.common.tile.base.TileEntityMekanism.tickServer(TileEntityMekanism.java:574)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.Level.redirect$edo000$redirectTick(Level.java:5538)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.Level.m_46463_(Level.java:446)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244)
	at java.base/java.lang.Thread.run(Thread.java:833)

[17:41:58] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:870) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraftforge.common.capabilities.Capability.isRegistered()" because "capability" is null
	at mekanism.common.capabilities.ItemCapabilityWrapper.getCapability(ItemCapabilityWrapper.java:43) ~[%5BX%5DMekanism-1.19.2-10.3.8.477.jar%23806!/:10.3.8]
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.getCapability(CapabilityDispatcher.java:89) ~[forge-1.19.2-43.2.14-universal.jar%23816!/:?]
	at net.minecraftforge.common.capabilities.CapabilityProvider.getCapability(CapabilityProvider.java:183) ~[forge-1.19.2-43.2.14-universal.jar%23816!/:?]
	at net.minecraftforge.common.capabilities.ICapabilityProvider.getCapability(ICapabilityProvider.java:33) ~[forge-1.19.2-43.2.14-universal.jar%23816!/:?]
	at jackiecrazy.footwork.handler.EntityHandler.pain(EntityHandler.java:106) ~[%5BB%5Dfootwork-2.6.jar%23529!/:2.6]
	at jackiecrazy.footwork.handler.__EntityHandler_pain_LivingHurtEvent.invoke(.dynamic) ~[%5BB%5Dfootwork-2.6.jar%23529!/:2.6]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2385!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2385!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2385!/:?]
	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:343) ~[forge-1.19.2-43.2.14-universal.jar%23816!/:?]
	at net.minecraft.world.entity.player.Player.m_6475_(Player.java:927) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.world.entity.LivingEntity.m_6469_(LivingEntity.java:1073) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.world.entity.player.Player.m_6469_(Player.java:862) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.server.level.ServerPlayer.m_6469_(ServerPlayer.java:671) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at mekanism.common.tile.laser.TileEntityBasicLaser.onUpdateServer(TileEntityBasicLaser.java:236) ~[%5BX%5DMekanism-1.19.2-10.3.8.477.jar%23806!/:10.3.8]
	at mekanism.common.tile.base.TileEntityMekanism.tickServer(TileEntityMekanism.java:574) ~[%5BX%5DMekanism-1.19.2-10.3.8.477.jar%23806!/:10.3.8]
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.world.level.Level.redirect$edo000$redirectTick(Level.java:5538) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.world.level.Level.m_46463_(Level.java:446) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	... 5 more
[17:41:58] [Server thread/FATAL]: Preparing crash report with UUID ffed5297-4ad9-4ae5-ab48-d62c100f07db
[17:41:58] [Server thread/ERROR]: This crash report has been saved to: H:\ModPack\HMCL\.minecraft\versions\1.19.2\crash-reports\crash-2023-07-17_17.41.58-server.txt
[17:41:58] [Server thread/INFO]: Stopping server
[17:41:58] [Server thread/INFO]: Saving players
[17:41:58] [Server thread/INFO]: Diemo_mustard lost connection: �������ѹر�
[17:41:58] [Server thread/INFO]: Diemo_mustard�˳�����Ϸ
[17:41:58] [Render thread/FATAL]: Preparing crash report with UUID db0b187e-1409-42dd-b58c-de2194dd1e18

### Steps to reproduce

1.Place laser and provide fe
2.Standing in front of the laser in survival mode
3.Game Crash

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.14

### Mekanism version

10.3.9 (Latest)

**Comment by Jorue23** [comment]
Please provide the crash report mentioned in the console log

**Comment by Diemoerm** [comment]
https://pastebin.com/X04804FJ

**Comment by Diemoerm** [comment]
> Please provide the crash report mentioned in the console log

https://pastebin.com/X04804FJ

**Comment by pupnewfster** [comment]
Footwork API is passing a [null cap](https://github.com/Jackiecrazy/footwork/blob/master/src/main/java/jackiecrazy/footwork/capability/weaponry/CombatManipulator.java#L9) to us and querying if we provide it when caps are nonnull.
