### ISSUE TITLE
Walkie Talkies not working correctly [1.19.2]

### ISSUE THREAD

**Issue by Klairm** [mekanism/Mekanism#7907]
### Issue description

If I don't come from a fresh start of the server, voice won't work, and after some minutes or hours I would need to restart the server manually and make all the users close the game completely to make walkies work.

Basically, when I and other users join the server and try to use the walkie talkie won't work, even tho that the server logs shows voice-server connection accepted, but when I restart manually the server, then me and the other users close the game completely and join again, walkie talkie will work again, but after some time it will again stop working. 

### Steps to reproduce

1. Enter server
2. Try to speak with someone using walkie talkies
3. No sound in any end
4. Restart manually the server
5. Each user of the server has to close the game completely (just leaving the server won't work)
6. Now voice works, but after some time  it will stop working again

### Minecraft version

1.19.x or earlier (No longer being developed)

### (Neo)Forge version

43.3.2 Forge

### Mekanism version

Older

### Other relevant versions

Mekanism 10.3.9

**Comment by Klairm** [comment]
It's weird because on the server log I don't see any errors, and acording to this source https://github.com/mekanism/Mekanism/blob/1.19.x/src/additions/java/mekanism/additions/common/voice/VoiceConnection.java if any error ocurred while sending the data there should be a message

**Comment by Klairm** [comment]
Something important I just noticed, when stopping the server the manager seems to be null, therefore appears this message:
```
[12:25:26] [Voice Server Client Listen Thread/ERROR] [me.co.Mekanism/]: VoiceServer: Error while stopping server-based connection.
java.lang.NullPointerException: Cannot invoke "mekanism.additions.common.voice.VoiceServerManager.removeConnection(mekanism.additions.common.voice.VoiceConnection)" because "mekanism.additions.common.MekanismAdditions.voiceManager" is null
        at mekanism.additions.common.voice.VoiceConnection.kill(VoiceConnection.java:105) ~[MekanismAdditions-1.19.2-10.3.9.13.jar%23168!/:10.3.9] {re:classloading}
        at mekanism.additions.common.voice.VoiceConnection.lambda$run$0(VoiceConnection.java:90) ~[MekanismAdditions-1.19.2-10.3.9.13.jar%23168!/:10.3.9] {re:classloading}
        at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
[12:25:28] [Voice Server Client Listen Thread/ERROR] [me.co.Mekanism/]: VoiceServer: Error while stopping server-based connection.
java.lang.NullPointerException: Cannot invoke "mekanism.additions.common.voice.VoiceServerManager.removeConnection(mekanism.additions.common.voice.VoiceConnection)" because "mekanism.additions.common.MekanismAdditions.voiceManager" is null
        at mekanism.additions.common.voice.VoiceConnection.kill(VoiceConnection.java:105) ~[MekanismAdditions-1.19.2-10.3.9.13.jar%23168!/:10.3.9] {re:classloading}
        at mekanism.additions.common.voice.VoiceConnection.lambda$run$0(VoiceConnection.java:90) ~[MekanismAdditions-1.19.2-10.3.9.13.jar%23168!/:10.3.9] {re:classloading}
        at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}

```
