### ISSUE TITLE
mekanism does'nt work

### ISSUE THREAD

**Issue by SenaxP** [mekanism/Mekanism#7969]
### Issue description

when i add the mod "mcmt" in my forge server the mekanism mod no longer works as it should, the interface of any block opens and closes instantly

Here is the error message in the logs : 
Exception ticking TE at BlockPos{x=125, y=97, z=-2}
net.minecraft.ReportedException: Ticking block entity
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:691)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:766)
        at TRANSFORMER/jmt_mcmt@0.24.2-118/org.jmt.mcmt.asmdest.ASMHookTerminator.lambda$callTileEntityTick$8(ASMHookTerminator.java:309)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.util.ConcurrentModificationException
        at java.base/java.util.HashMap$HashIterator.remove(Unknown Source)
        at java.base/java.util.Collection.removeIf(Unknown Source)
        at TRANSFORMER/mekanism@10.2.5/mekanism.common.lib.math.voxel.VoxelPlane.merge(VoxelPlane.java:74)
        at TRANSFORMER/mekanism@10.2.5/mekanism.common.lib.multiblock.Structure.lambda$add$3(Structure.java:155)
        at java.base/java.util.TreeMap.forEach(Unknown Source)
        at TRANSFORMER/mekanism@10.2.5/mekanism.common.lib.multiblock.Structure.add(Structure.java:151)
        at TRANSFORMER/mekanism@10.2.5/mekanism.common.lib.multiblock.Structure.mergeIfNecessary(Structure.java:303)
        at TRANSFORMER/mekanism@10.2.5/mekanism.common.lib.multiblock.Structure.lambda$validate$5(Structure.java:270)
        at TRANSFORMER/mekanism@10.2.5/mekanism.common.lib.multiblock.FormationProtocol.explore(FormationProtocol.java:131)
        at TRANSFORMER/mekanism@10.2.5/mekanism.common.lib.multiblock.FormationProtocol.explore(FormationProtocol.java:111)
        at TRANSFORMER/mekanism@10.2.5/mekanism.common.lib.multiblock.Structure.validate(Structure.java:236)
        at TRANSFORMER/mekanism@10.2.5/mekanism.common.lib.multiblock.Structure.tick(Structure.java:120)
        at TRANSFORMER/mekanism@10.2.5/mekanism.common.tile.prefab.TileEntityMultiblock.onUpdateServer(TileEntityMultiblock.java:123)
        at TRANSFORMER/mekanism@10.2.5/mekanism.common.tile.base.TileEntityMekanism.tickServer(TileEntityMekanism.java:570)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673)
        ... 8 more

### Steps to reproduce

1. create a forge server with the verson 40.2.14 and 1.18.2 minecraft version
2. add mcmt mod avec mekanism 
    (mcmt mod => https://www.curseforge.com/minecraft/mc-mods/mcmt-multithreading/files/3984627)
3. start the server 

### Minecraft version

1.19.x or earlier (No longer being developed)

### (Neo)Forge version

40.2.14

### Mekanism version

Older

### Other relevant versions

mcmt 1.18.2 0.24.2
https://www.curseforge.com/minecraft/mc-mods/mcmt-multithreading/files/3984627

**Comment by thiakil** [comment]
You should read the first paragraph on that mods curseforge description again
