### ISSUE TITLE
Mekanism nbt file

### ISSUE THREAD

**Issue by Mateo-Manchola12** [mekanism/Mekanism#8014]
### Issue description

I was creating a mekanism structure with diferents machines in creative for my word, after make the design y create a scheme with the creates mod, but when i try to use the scheme in the schematicannon it says some like "incompatible block, check the logs"(in the past i have this error coz i leave the creatuve bin and a creative fluid tank but in this it dsnt have anything of this), here is the logs and the NBT create archive

`[03mar.2024 22:04:51.776] [Server thread/ERROR] [com.simibubi.create.Create/]: Failed to load Schematic for Printing
java.lang.NullPointerException: Cannot read field "f_8325_" because the return value of "net.minecraft.world.level.Level.m_7726_()" is null
	at net.minecraftforge.network.PacketDistributor.lambda$trackingChunk$9(PacketDistributor.java:241) ~[forge-1.19.2-43.3.0-universal.jar%23252!/:?]
	at net.minecraftforge.network.PacketDistributor$PacketTarget.send(PacketDistributor.java:165) ~[forge-1.19.2-43.3.0-universal.jar%23252!/:?]
	at net.minecraftforge.network.simple.SimpleChannel.send(SimpleChannel.java:107) ~[forge-1.19.2-43.3.0-universal.jar%23252!/:?]
	at mekanism.common.network.BasePacketHandler.sendToAllTracking(BasePacketHandler.java:210) ~[Mekanism-1.19.2-10.3.9.13.jar%23224!/:10.3.9]
	at mekanism.common.network.BasePacketHandler.sendToAllTracking(BasePacketHandler.java:200) ~[Mekanism-1.19.2-10.3.9.13.jar%23224!/:10.3.9]
	at mekanism.common.tile.base.TileEntityUpdateable.sendUpdatePacket(TileEntityUpdateable.java:158) ~[Mekanism-1.19.2-10.3.9.13.jar%23224!/:10.3.9]
	at mekanism.common.tile.base.TileEntityUpdateable.sendUpdatePacket(TileEntityUpdateable.java:146) ~[Mekanism-1.19.2-10.3.9.13.jar%23224!/:10.3.9]
	at mekanism.common.content.network.transmitter.Transmitter.refreshConnections(Transmitter.java:536) ~[Mekanism-1.19.2-10.3.9.13.jar%23224!/:10.3.9]
	at mekanism.common.content.network.transmitter.Transmitter.onNeighborTileChange(Transmitter.java:578) ~[Mekanism-1.19.2-10.3.9.13.jar%23224!/:10.3.9]
	at mekanism.common.tile.transmitter.TileEntityTransmitter.onNeighborTileChange(TileEntityTransmitter.java:124) ~[Mekanism-1.19.2-10.3.9.13.jar%23224!/:10.3.9]
	at mekanism.common.block.transmitter.BlockTransmitter.onNeighborChange(BlockTransmitter.java:92) ~[Mekanism-1.19.2-10.3.9.13.jar%23224!/:10.3.9]
	at net.minecraftforge.common.extensions.IForgeBlockState.onNeighborChange(IForgeBlockState.java:381) ~[forge-1.19.2-43.3.0-universal.jar%23252!/:?]
	at mekanism.common.util.WorldUtils.lambda$notifyNeighborsOfChange$3(WorldUtils.java:582) ~[Mekanism-1.19.2-10.3.9.13.jar%23224!/:10.3.9]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at mekanism.common.util.WorldUtils.lambda$notifyNeighborsOfChange$4(WorldUtils.java:581) ~[Mekanism-1.19.2-10.3.9.13.jar%23224!/:10.3.9]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at mekanism.common.util.WorldUtils.notifyNeighborsOfChange(WorldUtils.java:578) ~[Mekanism-1.19.2-10.3.9.13.jar%23224!/:10.3.9]
	at mekanism.common.tile.component.TileComponentConfig.lambda$read$4(TileComponentConfig.java:299) ~[Mekanism-1.19.2-10.3.9.13.jar%23224!/:10.3.9]
	at mekanism.common.util.NBTUtils.setCompoundIfPresent(NBTUtils.java:112) ~[Mekanism-1.19.2-10.3.9.13.jar%23224!/:10.3.9]
	at mekanism.common.tile.component.TileComponentConfig.read(TileComponentConfig.java:280) ~[Mekanism-1.19.2-10.3.9.13.jar%23224!/:10.3.9]
	at mekanism.common.tile.base.TileEntityMekanism.m_142466_(TileEntityMekanism.java:655) ~[Mekanism-1.19.2-10.3.9.13.jar%23224!/:10.3.9]
	at mekanism.common.tile.prefab.TileEntityProgressMachine.m_142466_(TileEntityProgressMachine.java:57) ~[Mekanism-1.19.2-10.3.9.13.jar%23224!/:10.3.9]
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.m_230328_(StructureTemplate.java:251) ~[client-1.19.2-20220805.130853-srg.jar%23247!/:?]
	at com.simibubi.create.content.schematics.SchematicPrinter.loadSchematic(SchematicPrinter.java:101) ~[create-1.19.2-0.5.1.f.jar%23208!/:0.5.1.f]
	at com.simibubi.create.content.schematics.cannon.SchematicannonBlockEntity.initializePrinter(SchematicannonBlockEntity.java:450) ~[create-1.19.2-0.5.1.f.jar%23208!/:0.5.1.f]
	at com.simibubi.create.content.schematics.cannon.SchematicannonBlockEntity.tickPaperPrinter(SchematicannonBlockEntity.java:684) ~[create-1.19.2-0.5.1.f.jar%23208!/:0.5.1.f]
	at com.simibubi.create.content.schematics.cannon.SchematicannonBlockEntity.tick(SchematicannonBlockEntity.java:278) ~[create-1.19.2-0.5.1.f.jar%23208!/:0.5.1.f]
	at com.simibubi.create.foundation.blockEntity.SmartBlockEntityTicker.m_155252_(SmartBlockEntityTicker.java:15) ~[create-1.19.2-0.5.1.f.jar%23208!/:0.5.1.f]
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[client-1.19.2-20220805.130853-srg.jar%23247!/:?]
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[client-1.19.2-20220805.130853-srg.jar%23247!/:?]
	at net.minecraft.world.level.Level.m_46463_(Level.java:446) ~[client-1.19.2-20220805.130853-srg.jar%23247!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[client-1.19.2-20220805.130853-srg.jar%23247!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23247!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23247!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:118) ~[client-1.19.2-20220805.130853-srg.jar%23247!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23247!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23247!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]`
[prueba_13478.zip](https://github.com/mekanism/Mekanism/files/14476118/prueba_13478.zip)

### Minecraft version

1.20.1 or earlier (No longer being developed)

### NeoForge version

im using 1.19.2-forge-43.3.0

### Mekanism version

Older

### Other relevant versions

Mekanism-1.19.2-10.3.9.13
MekanismGenerators-1.19.2-10.3.9.13
MekanismTools-1.19.2-10.3.9.13
create-1.19.2-0.5.1.f
createaddition-1.19.2-1.2.1

**Comment by thiakil** [comment]
Looks like create isn't fully setting up the fake World/Level as expected.
