### ISSUE TITLE
provideEnergy - java.lang.Exception: null

### ISSUE THREAD

**Issue by mikaba-eu** [mekanism/Mekanism#8076]
### Issue description

We play ATM-8 on our server and the server spams
```
[16May2024 13:22:01.195] [Server thread/ERROR] [mekanism.common.Mekanism/]: Energy value changed by a different amount (1.0054) than requested (zero).
java.lang.Exception: null
	at mekanism.common.util.MekanismUtils.logExpectedZero(MekanismUtils.java:132) ~[Mekanism-1.19.2-10.3.9.13.jar%23678!/:10.3.9]
	at mekanism.common.tile.TileEntityChargepad.provideEnergy(TileEntityChargepad.java:109) ~[Mekanism-1.19.2-10.3.9.13.jar%23678!/:10.3.9]
	at mekanism.common.tile.TileEntityChargepad.chargeHandler(TileEntityChargepad.java:89) ~[Mekanism-1.19.2-10.3.9.13.jar%23678!/:10.3.9]
	at mekanism.common.tile.TileEntityChargepad.onUpdateServer(TileEntityChargepad.java:73) ~[Mekanism-1.19.2-10.3.9.13.jar%23678!/:10.3.9]
	at mekanism.common.tile.base.TileEntityMekanism.tickServer(TileEntityMekanism.java:570) ~[Mekanism-1.19.2-10.3.9.13.jar%23678!/:10.3.9]
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.mixinextras$bridge$m_155252_$7(LevelChunk.java) ~[server-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at com.bawnorton.neruina.handler.NeruinaTickHandler.safelyTickBlockEntity$notTheCauseOfTickLag(NeruinaTickHandler.java:96) ~[neruina-1.3.0-forge+1.18.2-1.20.1.jar%23705!/:?]
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.wrapOperation$bli000$catchTickingBlockEntity(LevelChunk.java:811) ~[server-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[server-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[server-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.world.level.Level.redirect$beh000$redirectTick(MixinLevel.java:2538) ~[server-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.world.level.Level.m_46463_(MixinLevel.java:446) ~[server-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[server-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[server-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23839!/:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
```

### Steps to reproduce

We don't know exactly. We have a lot of player bases and there is no known way for us to find the block / chunk that cause that issue.

### Minecraft version

1.20.1 or earlier (No longer being developed)

### NeoForge version

1.19.2-43.3.0

### Mekanism version

Older

### Other relevant versions

Mekanism Version: 1.19.2-10.3.9.13

**Comment by thiakil** [comment]
Something it was charging said it could accept more than it actually did.

You can ignore it
