### ISSUE TITLE
Texture is required if use_mob_texture is false

### ISSUE THREAD

**Issue by bookerthegeek** [mekanism/Mekanism#8256]
### Heyo!

Saw this in the log, thought you might want to know about it.

```
[09:41:41] [Worker-ResourceReload-3/ERROR] [de.ft.mo.ft.cl.ma.EntityIcons/]: Failed to parse entity icon settings for mekanismadditions:baby_bogged
java.lang.IllegalStateException: Texture is required if use_mob_texture is false
	at MC-BOOTSTRAP/datafixerupper@8.0.16/com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287) ~[datafixerupper-8.0.16.jar%23106!/:?] {re:mixin}
	at MC-BOOTSTRAP/datafixerupper@8.0.16/com.mojang.serialization.DataResult.getOrThrow(DataResult.java:81) ~[datafixerupper-8.0.16.jar%23106!/:?] {re:mixin}
	at TRANSFORMER/ftbchunks@2101.1.3/dev.ftb.mods.ftbchunks.client.mapicon.EntityIcons.getEntitySetting(EntityIcons.java:145) ~[ftb-chunks-neoforge-2101.1.3.jar%23517!/:2101.1.3] {re:classloading}
	at TRANSFORMER/ftbchunks@2101.1.3/dev.ftb.mods.ftbchunks.client.mapicon.EntityIcons.prepare(EntityIcons.java:81) ~[ftb-chunks-neoforge-2101.1.3.jar%23517!/:2101.1.3] {re:classloading}
	at TRANSFORMER/ftbchunks@2101.1.3/dev.ftb.mods.ftbchunks.client.mapicon.EntityIcons.prepare(EntityIcons.java:42) ~[ftb-chunks-neoforge-2101.1.3.jar%23517!/:2101.1.3] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.packs.resources.SimplePreparableReloadListener.lambda$reload$0(SimplePreparableReloadListener.java:17) ~[client-1.21.1-20240808.144430-srg.jar%23430!/:?] {re:mixin,re:computing_frames,re:classloading}
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:?] {}
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:?] {}
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?] {re:mixin,re:computing_frames}
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?] {re:mixin,re:computing_frames}
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?] {re:mixin}
```

### Steps to reproduce

- Install the mod
- Start MC
- Look at thelog

### Minecraft version

1.21.1 (Latest)

### NeoForge version

21.1.75

### Mekanism version

10.7.7 (Latest)

**Comment by thiakil** [comment]
That's a bug for your pack or FTBChunks
